package com.path.vo.alert.event;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlType;

/**
 * @AutoGenerated Code
 * @description class CommunicationMode
 */

@XmlType(propOrder={})
public class CommunicationMode 
{
	private String communicationType;
	private String defaultSubject;
	private String defaultBody;
	private BigDecimal reportId;
	private BigDecimal queryId;
	private String activatedYN;

	public void setCommunicationType(String communicationType)
	{
	   this.communicationType = communicationType;
	}
	public String getCommunicationType()
	{
	   return communicationType;
	}
	public void setDefaultSubject(String defaultSubject)
	{
	   this.defaultSubject = defaultSubject;
	}
	public String getDefaultSubject()
	{
	   return defaultSubject;
	}
	public void setDefaultBody(String defaultBody)
	{
	   this.defaultBody = defaultBody;
	}
	public String getDefaultBody()
	{
	   return defaultBody;
	}
	public void setReportId(BigDecimal reportId)
	{
	   this.reportId = reportId;
	}
	public BigDecimal getReportId()
	{
	   return reportId;
	}
	public void setQueryId(BigDecimal queryId)
	{
	   this.queryId = queryId;
	}
	public BigDecimal getQueryId()
	{
	   return queryId;
	}
	public void setActivatedYN(String activatedYN)
	{
	   this.activatedYN = activatedYN;
	}
	public String getActivatedYN()
	{
	   return activatedYN;
	}
}
