package com.path.vo.alert.event;
import com.path.vo.common.header.ServiceContextAllVO;
import java.math.BigDecimal;

import com.path.vo.common.DynamicFilter;
import com.path.vo.common.ImBaseRequest;
import javax.xml.bind.annotation.XmlType;

/**
 * @AutoGenerated Code
 * @description class ReturnEventsListReq extends ImBaseRequest
 */

@XmlType(propOrder={})
public class ReturnEventsListReq extends ImBaseRequest
{
	private ServiceContextAllVO serviceContext = new ServiceContextAllVO();
	private BigDecimal companyCode;
	private String status;
	private String eventType;
	private String descriptionEnglish;
	private String communicationType;
	private String descriptionArabic;
	private DynamicFilter dynamicFilter = new DynamicFilter();

	public void setServiceContext(ServiceContextAllVO serviceContext)
	{
	   this.serviceContext = serviceContext;
	}
	public ServiceContextAllVO getServiceContext()
	{
	   return serviceContext;
	}
	public void setCompanyCode(BigDecimal companyCode)
	{
	   this.companyCode = companyCode;
	}
	public BigDecimal getCompanyCode()
	{
	   return companyCode;
	}
	public void setStatus(String status)
	{
	   this.status = status;
	}
	public String getStatus()
	{
	   return status;
	}
	public void setEventType(String eventType)
	{
	   this.eventType = eventType;
	}
	public String getEventType()
	{
	   return eventType;
	}
	public void setDescriptionEnglish(String descriptionEnglish)
	{
	   this.descriptionEnglish = descriptionEnglish;
	}
	public String getDescriptionEnglish()
	{
	   return descriptionEnglish;
	}
	public void setCommunicationType(String communicationType)
	{
	   this.communicationType = communicationType;
	}
	public String getCommunicationType()
	{
	   return communicationType;
	}
	public void setDescriptionArabic(String descriptionArabic)
	{
	   this.descriptionArabic = descriptionArabic;
	}
	public String getDescriptionArabic()
	{
	   return descriptionArabic;
	}
	public void setDynamicFilter(DynamicFilter dynamicFilter)
	{
	   this.dynamicFilter = dynamicFilter;
	}
	public DynamicFilter getDynamicFilter()
	{
	   return dynamicFilter;
	}
}
