package com.path.vo.alert.event;
import java.math.BigDecimal;
import com.path.vo.common.header.ServiceResponseVO;
import com.path.vo.common.header.ResponseContextVO;
import com.path.vo.common.header.ResponseServiceContextVO;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;

import java.util.ArrayList;
import java.util.List;
import com.path.vo.alert.event.CommunicationMode;
import com.path.vo.common.ImBaseRequest;
import javax.xml.bind.annotation.XmlType;

/**
 * @AutoGenerated Code
 * @description class ReturnEventDetailsResp extends ImBaseRequest
 */

@XmlType(propOrder={})
public class ReturnEventDetailsResp extends ImBaseRequest
{
	private ServiceResponseVO serviceResponse = new ServiceResponseVO();
	private ResponseContextVO responseContext = new ResponseContextVO();
	private ResponseServiceContextVO responseServiceContext = new ResponseServiceContextVO();
	private BigDecimal eventId;
	private BigDecimal companyCode;
	private String status;
	private String eventType;
	private String descriptionEnglish;
	private String descriptionArabic;
	private List<CommunicationMode> communicationModeList = new ArrayList<CommunicationMode>();

	public void setServiceResponse(ServiceResponseVO serviceResponse)
	{
	   this.serviceResponse = serviceResponse;
	}
	public ServiceResponseVO getServiceResponse()
	{
	   return serviceResponse;
	}
	public void setResponseContext(ResponseContextVO responseContext)
	{
	   this.responseContext = responseContext;
	}
	public ResponseContextVO getResponseContext()
	{
	   return responseContext;
	}
	public void setResponseServiceContext(ResponseServiceContextVO responseServiceContext)
	{
	   this.responseServiceContext = responseServiceContext;
	}
	public ResponseServiceContextVO getResponseServiceContext()
	{
	   return responseServiceContext;
	}
	public void setEventId(BigDecimal eventId)
	{
	   this.eventId = eventId;
	}
	public BigDecimal getEventId()
	{
	   return eventId;
	}
	public void setCompanyCode(BigDecimal companyCode)
	{
	   this.companyCode = companyCode;
	}
	public BigDecimal getCompanyCode()
	{
	   return companyCode;
	}
	public void setStatus(String status)
	{
	   this.status = status;
	}
	public String getStatus()
	{
	   return status;
	}
	public void setEventType(String eventType)
	{
	   this.eventType = eventType;
	}
	public String getEventType()
	{
	   return eventType;
	}
	public void setDescriptionEnglish(String descriptionEnglish)
	{
	   this.descriptionEnglish = descriptionEnglish;
	}
	public String getDescriptionEnglish()
	{
	   return descriptionEnglish;
	}
	public void setDescriptionArabic(String descriptionArabic)
	{
	   this.descriptionArabic = descriptionArabic;
	}
	public String getDescriptionArabic()
	{
	   return descriptionArabic;
	}
	public void setCommunicationModeList(List<CommunicationMode> communicationModeList)
	{
	   this.communicationModeList = communicationModeList;
	}
	@XmlElementWrapper(name = "communicationModeList")
  	@XmlElement(name = "communicationMode")
	public List<CommunicationMode> getCommunicationModeList()
	{
	   return communicationModeList;
	}
}
