package com.path.vo.alert.notification;
import java.math.BigDecimal;
import com.path.vo.common.header.ServiceResponseVO;
import com.path.vo.common.header.ResponseContextVO;
import com.path.vo.common.header.ResponseServiceContextVO;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlElement;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import com.path.vo.common.ImBaseRequest;
import javax.xml.bind.annotation.XmlType;

/**
 * @AutoGenerated Code
 * @description class SendAlertNotificationResp extends ImBaseRequest
 */

@XmlType(propOrder={})
public class SendAlertNotificationResp extends ImBaseRequest
{
	private ServiceResponseVO serviceResponse = new ServiceResponseVO();
	private ResponseContextVO responseContext = new ResponseContextVO();
	private ResponseServiceContextVO responseServiceContext = new ResponseServiceContextVO();
	private BigDecimal eventId;
	private String eventName;
	private BigDecimal companyCode;
	private BigDecimal branchCode;
	private List<BigDecimal> cifList = new ArrayList<BigDecimal>();
	private List<BigDecimal> subscriberIdsList = new ArrayList<BigDecimal>();
	private List<String> channelUserIdsList = new ArrayList<String>();
	private List<String> facebookSocialIdsList = new ArrayList<String>();
	private List<String> twitterSocialIdsList = new ArrayList<String>();
	private List<String> imalUserIdsList = new ArrayList<String>();
	private List<String> emailsList = new ArrayList<String>();
	private List<String> mobilesList = new ArrayList<String>();
	private List<Account> accountsList = new ArrayList<Account>();
	private List<BigDecimal> groupIdsList = new ArrayList<BigDecimal>();
	private HashMap<String,String> tagEvent = new HashMap<String,String>();

	public void setServiceResponse(ServiceResponseVO serviceResponse)
	{
	   this.serviceResponse = serviceResponse;
	}
	public ServiceResponseVO getServiceResponse()
	{
	   return serviceResponse;
	}
	public void setResponseContext(ResponseContextVO responseContext)
	{
	   this.responseContext = responseContext;
	}
	public ResponseContextVO getResponseContext()
	{
	   return responseContext;
	}
	public void setResponseServiceContext(ResponseServiceContextVO responseServiceContext)
	{
	   this.responseServiceContext = responseServiceContext;
	}
	public ResponseServiceContextVO getResponseServiceContext()
	{
	   return responseServiceContext;
	}
	public void setEventId(BigDecimal eventId)
	{
	   this.eventId = eventId;
	}
	public BigDecimal getEventId()
	{
	   return eventId;
	}
	public void setEventName(String eventName)
	{
	   this.eventName = eventName;
	}
	public String getEventName()
	{
	   return eventName;
	}
	public void setCompanyCode(BigDecimal companyCode)
	{
	   this.companyCode = companyCode;
	}
	public BigDecimal getCompanyCode()
	{
	   return companyCode;
	}
	public void setBranchCode(BigDecimal branchCode)
	{
	   this.branchCode = branchCode;
	}
	public BigDecimal getBranchCode()
	{
	   return branchCode;
	}
	public void setCifList(List<BigDecimal> cifList)
	{
	   this.cifList = cifList;
	}
	@XmlElementWrapper(name = "cifList")
  	@XmlElement(name = "cif")
	public List<BigDecimal> getCifList()
	{
	   return cifList;
	}
	public void setSubscriberIdsList(List<BigDecimal> subscriberIdsList)
	{
	   this.subscriberIdsList = subscriberIdsList;
	}
	@XmlElementWrapper(name = "subscriberIdsList")
  	@XmlElement(name = "subscriberId")
	public List<BigDecimal> getSubscriberIdsList()
	{
	   return subscriberIdsList;
	}
	public void setChannelUserIdsList(List<String> channelUserIdsList)
	{
	   this.channelUserIdsList = channelUserIdsList;
	}
	@XmlElementWrapper(name = "channelUserIdsList")
  	@XmlElement(name = "channelUserId")
	public List<String> getChannelUserIdsList()
	{
	   return channelUserIdsList;
	}
	public void setFacebookSocialIdsList(List<String> facebookSocialIdsList)
	{
	   this.facebookSocialIdsList = facebookSocialIdsList;
	}
	@XmlElementWrapper(name = "facebookSocialIdsList")
  	@XmlElement(name = "facebookSocialId")
	public List<String> getFacebookSocialIdsList()
	{
	   return facebookSocialIdsList;
	}
	public void setTwitterSocialIdsList(List<String> twitterSocialIdsList)
	{
	   this.twitterSocialIdsList = twitterSocialIdsList;
	}
	@XmlElementWrapper(name = "twitterSocialIdsList")
  	@XmlElement(name = "twitterSocialId")
	public List<String> getTwitterSocialIdsList()
	{
	   return twitterSocialIdsList;
	}
	public void setImalUserIdsList(List<String> imalUserIdsList)
	{
	   this.imalUserIdsList = imalUserIdsList;
	}
	@XmlElementWrapper(name = "imalUserIdsList")
  	@XmlElement(name = "imalUserId")
	public List<String> getImalUserIdsList()
	{
	   return imalUserIdsList;
	}
	public void setEmailsList(List<String> emailsList)
	{
	   this.emailsList = emailsList;
	}
	@XmlElementWrapper(name = "emailsList")
  	@XmlElement(name = "email")
	public List<String> getEmailsList()
	{
	   return emailsList;
	}
	public void setMobilesList(List<String> mobilesList)
	{
	   this.mobilesList = mobilesList;
	}
	@XmlElementWrapper(name = "mobilesList")
  	@XmlElement(name = "mobile")
	public List<String> getMobilesList()
	{
	   return mobilesList;
	}
	public void setAccountsList(List<Account> accountsList)
	{
	   this.accountsList = accountsList;
	}
	@XmlElementWrapper(name = "accountsList")
  	@XmlElement(name = "account")
	public List<Account> getAccountsList()
	{
	   return accountsList;
	}
	public void setGroupIdsList(List<BigDecimal> groupIdsList)
	{
	   this.groupIdsList = groupIdsList;
	}
	@XmlElementWrapper(name = "groupIdsList")
  	@XmlElement(name = "groupId")
	public List<BigDecimal> getGroupIdsList()
	{
	   return groupIdsList;
	}
	public HashMap<String, String> getTagEvent() {
		return tagEvent;
	}
	public void setTagEvent(HashMap<String, String> tagEvent) {
		this.tagEvent = tagEvent;
	}
}
