package com.path.vo.alert.subscription;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlType;

/**
 * @AutoGenerated Code
 * @description class CommunicationMode
 */

@XmlType(propOrder={})
public class CommunicationMode 
{
	private String mode;
	private BigDecimal enabled;

	public void setMode(String mode)
	{
	   this.mode = mode;
	}
	public String getMode()
	{
	   return mode;
	}
	public void setEnabled(BigDecimal enabled)
	{
	   this.enabled = enabled;
	}
	public BigDecimal getEnabled()
	{
	   return enabled;
	}
}
