package com.path.vo.alert.subscription;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import com.path.vo.common.header.ServiceContextAllVO;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;

import com.path.vo.common.ImBaseRequest;
import javax.xml.bind.annotation.XmlType;

/**
 * @AutoGenerated Code
 * @description class CreateSingleSubscriptionSPReq extends ImBaseRequest
 */

@XmlType(propOrder={})
public class CreateSingleSubscriptionSPReq extends ImBaseRequest
{
	private ServiceContextAllVO serviceContext = new ServiceContextAllVO();
	private BigDecimal companyCode;
	private BigDecimal subscriberId;
	private BigDecimal subscriptionPackageId;
	private String autoApproveFlag;
	private List<Account> exludeAccountList = new ArrayList<Account>();

	public void setServiceContext(ServiceContextAllVO serviceContext)
	{
	   this.serviceContext = serviceContext;
	}
	public ServiceContextAllVO getServiceContext()
	{
	   return serviceContext;
	}
	public void setCompanyCode(BigDecimal companyCode)
	{
	   this.companyCode = companyCode;
	}
	@XmlElement(required = true)
	public BigDecimal getCompanyCode()
	{
	   return companyCode;
	}
	public void setSubscriberId(BigDecimal subscriberId)
	{
	   this.subscriberId = subscriberId;
	}
	@XmlElement(required = true)
	public BigDecimal getSubscriberId()
	{
	   return subscriberId;
	}
	public void setSubscriptionPackageId(BigDecimal subscriptionPackageId)
	{
	   this.subscriptionPackageId = subscriptionPackageId;
	}
	@XmlElement(required = true)
	public BigDecimal getSubscriptionPackageId()
	{
	   return subscriptionPackageId;
	}
	public void setAutoApproveFlag(String autoApproveFlag)
	{
	   this.autoApproveFlag = autoApproveFlag;
	}
	public String getAutoApproveFlag()
	{
	   return autoApproveFlag;
	}
	public void setExludeAccountList(List<Account> exludeAccountList)
	{
	   this.exludeAccountList = exludeAccountList;
	}
	@XmlElementWrapper(name = "exludeAccountList")
  	@XmlElement(name = "account")
	public List<Account> getExludeAccountList()
	{
	   return exludeAccountList;
	}
}
