package com.path.vo.alert.subscription;
import java.math.BigDecimal;
import com.path.vo.common.header.ServiceResponseVO;
import com.path.vo.common.header.ResponseContextVO;
import com.path.vo.common.header.ResponseServiceContextVO;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;

import java.util.ArrayList;
import java.util.List;
import com.path.vo.alert.subscription.Event;
import com.path.vo.common.ImBaseRequest;
import javax.xml.bind.annotation.XmlType;

/**
 * @AutoGenerated Code
 * @description class ReturnSubscriptionDetailsResp extends ImBaseRequest
 */

@XmlType(propOrder={})
public class ReturnSubscriptionDetailsResp extends ImBaseRequest
{
	private ServiceResponseVO serviceResponse = new ServiceResponseVO();
	private ResponseContextVO responseContext = new ResponseContextVO();
	private ResponseServiceContextVO responseServiceContext = new ResponseServiceContextVO();
	private BigDecimal companyCode;
	private BigDecimal subscriberId;
	private BigDecimal cifNumber;
	private String imalUserId;
	private String channelEndUserId;
	private List<Event> eventsList = new ArrayList<Event>();

	public void setServiceResponse(ServiceResponseVO serviceResponse)
	{
	   this.serviceResponse = serviceResponse;
	}
	public ServiceResponseVO getServiceResponse()
	{
	   return serviceResponse;
	}
	public void setResponseContext(ResponseContextVO responseContext)
	{
	   this.responseContext = responseContext;
	}
	public ResponseContextVO getResponseContext()
	{
	   return responseContext;
	}
	public void setResponseServiceContext(ResponseServiceContextVO responseServiceContext)
	{
	   this.responseServiceContext = responseServiceContext;
	}
	public ResponseServiceContextVO getResponseServiceContext()
	{
	   return responseServiceContext;
	}
	public void setCompanyCode(BigDecimal companyCode)
	{
	   this.companyCode = companyCode;
	}
	public BigDecimal getCompanyCode()
	{
	   return companyCode;
	}
	public void setSubscriberId(BigDecimal subscriberId)
	{
	   this.subscriberId = subscriberId;
	}
	public BigDecimal getSubscriberId()
	{
	   return subscriberId;
	}
	public void setCifNumber(BigDecimal cifNumber)
	{
	   this.cifNumber = cifNumber;
	}
	public BigDecimal getCifNumber()
	{
	   return cifNumber;
	}
	public void setImalUserId(String imalUserId)
	{
	   this.imalUserId = imalUserId;
	}
	public String getImalUserId()
	{
	   return imalUserId;
	}
	public void setChannelEndUserId(String channelEndUserId)
	{
	   this.channelEndUserId = channelEndUserId;
	}
	public String getChannelEndUserId()
	{
	   return channelEndUserId;
	}
	public void setEventsList(List<Event> eventsList)
	{
	   this.eventsList = eventsList;
	}
	@XmlElementWrapper(name = "eventsList")
  	@XmlElement(name = "event")
	public List<Event> getEventsList()
	{
	   return eventsList;
	}
}
