package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ALRT_PKGVOKey extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_PKG.PKG_ID
     */
    private BigDecimal PKG_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PKG.PKG_ID
     *
     * @return the value of ALRT_PKG.PKG_ID
     */
    public BigDecimal getPKG_ID() {
        return PKG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PKG.PKG_ID
     *
     * @param PKG_ID the value for ALRT_PKG.PKG_ID
     */
    public void setPKG_ID(BigDecimal PKG_ID) {
        this.PKG_ID = PKG_ID;
    }
}