package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class ALRT_REPORT_QUERY_ARGVO extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY_ARG.ARG_ID
     */
    private BigDecimal ARG_ID;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY_ARG.REP_QUER_ID
     */
    private BigDecimal REP_QUER_ID;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY_ARG.QUERY_ID
     */
    private BigDecimal QUERY_ID;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY_ARG.ARG_NAME
     */
    private String ARG_NAME;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY_ARG.ARG_TYPE
     */
    private String ARG_TYPE;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY_ARG.MAPPING_ARG
     */
    private String MAPPING_ARG;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY_ARG.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY_ARG.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY_ARG.SERVER_CREATED_DATE
     */
    private Date SERVER_CREATED_DATE;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY_ARG.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY_ARG.ARG_ID
     *
     * @return the value of ALRT_REPORT_QUERY_ARG.ARG_ID
     */
    public BigDecimal getARG_ID() {
        return ARG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY_ARG.ARG_ID
     *
     * @param ARG_ID the value for ALRT_REPORT_QUERY_ARG.ARG_ID
     */
    public void setARG_ID(BigDecimal ARG_ID) {
        this.ARG_ID = ARG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY_ARG.REP_QUER_ID
     *
     * @return the value of ALRT_REPORT_QUERY_ARG.REP_QUER_ID
     */
    public BigDecimal getREP_QUER_ID() {
        return REP_QUER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY_ARG.REP_QUER_ID
     *
     * @param REP_QUER_ID the value for ALRT_REPORT_QUERY_ARG.REP_QUER_ID
     */
    public void setREP_QUER_ID(BigDecimal REP_QUER_ID) {
        this.REP_QUER_ID = REP_QUER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY_ARG.QUERY_ID
     *
     * @return the value of ALRT_REPORT_QUERY_ARG.QUERY_ID
     */
    public BigDecimal getQUERY_ID() {
        return QUERY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY_ARG.QUERY_ID
     *
     * @param QUERY_ID the value for ALRT_REPORT_QUERY_ARG.QUERY_ID
     */
    public void setQUERY_ID(BigDecimal QUERY_ID) {
        this.QUERY_ID = QUERY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY_ARG.ARG_NAME
     *
     * @return the value of ALRT_REPORT_QUERY_ARG.ARG_NAME
     */
    public String getARG_NAME() {
        return ARG_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY_ARG.ARG_NAME
     *
     * @param ARG_NAME the value for ALRT_REPORT_QUERY_ARG.ARG_NAME
     */
    public void setARG_NAME(String ARG_NAME) {
        this.ARG_NAME = ARG_NAME == null ? null : ARG_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY_ARG.ARG_TYPE
     *
     * @return the value of ALRT_REPORT_QUERY_ARG.ARG_TYPE
     */
    public String getARG_TYPE() {
        return ARG_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY_ARG.ARG_TYPE
     *
     * @param ARG_TYPE the value for ALRT_REPORT_QUERY_ARG.ARG_TYPE
     */
    public void setARG_TYPE(String ARG_TYPE) {
        this.ARG_TYPE = ARG_TYPE == null ? null : ARG_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY_ARG.MAPPING_ARG
     *
     * @return the value of ALRT_REPORT_QUERY_ARG.MAPPING_ARG
     */
    public String getMAPPING_ARG() {
        return MAPPING_ARG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY_ARG.MAPPING_ARG
     *
     * @param MAPPING_ARG the value for ALRT_REPORT_QUERY_ARG.MAPPING_ARG
     */
    public void setMAPPING_ARG(String MAPPING_ARG) {
        this.MAPPING_ARG = MAPPING_ARG == null ? null : MAPPING_ARG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY_ARG.CREATED_BY
     *
     * @return the value of ALRT_REPORT_QUERY_ARG.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY_ARG.CREATED_BY
     *
     * @param CREATED_BY the value for ALRT_REPORT_QUERY_ARG.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY_ARG.CREATED_DATE
     *
     * @return the value of ALRT_REPORT_QUERY_ARG.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY_ARG.CREATED_DATE
     *
     * @param CREATED_DATE the value for ALRT_REPORT_QUERY_ARG.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY_ARG.SERVER_CREATED_DATE
     *
     * @return the value of ALRT_REPORT_QUERY_ARG.SERVER_CREATED_DATE
     */
    public Date getSERVER_CREATED_DATE() {
        return SERVER_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY_ARG.SERVER_CREATED_DATE
     *
     * @param SERVER_CREATED_DATE the value for ALRT_REPORT_QUERY_ARG.SERVER_CREATED_DATE
     */
    public void setSERVER_CREATED_DATE(Date SERVER_CREATED_DATE) {
        this.SERVER_CREATED_DATE = SERVER_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY_ARG.DATE_UPDATED
     *
     * @return the value of ALRT_REPORT_QUERY_ARG.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY_ARG.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for ALRT_REPORT_QUERY_ARG.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}