package com.path.dbmaps.vo;

import java.util.Date;

public class ALRT_SUBSCRIPTION_PARAMVO extends ALRT_SUBSCRIPTION_PARAMVOKey {
    /**
     * This field corresponds to the database column ALRT_SUBSCRIPTION_PARAM.FIXED_OPERATOR
     */
    private String FIXED_OPERATOR;

    /**
     * This field corresponds to the database column ALRT_SUBSCRIPTION_PARAM.FROM_VALUE
     */
    private String FROM_VALUE;

    /**
     * This field corresponds to the database column ALRT_SUBSCRIPTION_PARAM.TO_VALUE
     */
    private String TO_VALUE;

    /**
     * This field corresponds to the database column ALRT_SUBSCRIPTION_PARAM.OLD_FIXED_OPERATOR
     */
    private String OLD_FIXED_OPERATOR;

    /**
     * This field corresponds to the database column ALRT_SUBSCRIPTION_PARAM.OLD_FROM_VALUE
     */
    private String OLD_FROM_VALUE;

    /**
     * This field corresponds to the database column ALRT_SUBSCRIPTION_PARAM.OLD_TO_VALUE
     */
    private String OLD_TO_VALUE;

 /**
     * This field corresponds to the database column ALRT_SUBSCRIPTION_PARAM.DATE_UPDATED
     */
    private Date DATE_UPDATED;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUBSCRIPTION_PARAM.FIXED_OPERATOR
     *
     * @return the value of ALRT_SUBSCRIPTION_PARAM.FIXED_OPERATOR
     */
    public String getFIXED_OPERATOR() {
        return FIXED_OPERATOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUBSCRIPTION_PARAM.FIXED_OPERATOR
     *
     * @param FIXED_OPERATOR the value for ALRT_SUBSCRIPTION_PARAM.FIXED_OPERATOR
     */
    public void setFIXED_OPERATOR(String FIXED_OPERATOR) {
        this.FIXED_OPERATOR = FIXED_OPERATOR == null ? null : FIXED_OPERATOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUBSCRIPTION_PARAM.FROM_VALUE
     *
     * @return the value of ALRT_SUBSCRIPTION_PARAM.FROM_VALUE
     */
    public String getFROM_VALUE() {
        return FROM_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUBSCRIPTION_PARAM.FROM_VALUE
     *
     * @param FROM_VALUE the value for ALRT_SUBSCRIPTION_PARAM.FROM_VALUE
     */
    public void setFROM_VALUE(String FROM_VALUE) {
        this.FROM_VALUE = FROM_VALUE == null ? null : FROM_VALUE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUBSCRIPTION_PARAM.TO_VALUE
     *
     * @return the value of ALRT_SUBSCRIPTION_PARAM.TO_VALUE
     */
    public String getTO_VALUE() {
        return TO_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUBSCRIPTION_PARAM.TO_VALUE
     *
     * @param TO_VALUE the value for ALRT_SUBSCRIPTION_PARAM.TO_VALUE
     */
    public void setTO_VALUE(String TO_VALUE) {
        this.TO_VALUE = TO_VALUE == null ? null : TO_VALUE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUBSCRIPTION_PARAM.OLD_FIXED_OPERATOR
     *
     * @return the value of ALRT_SUBSCRIPTION_PARAM.OLD_FIXED_OPERATOR
     */
    public String getOLD_FIXED_OPERATOR() {
        return OLD_FIXED_OPERATOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUBSCRIPTION_PARAM.OLD_FIXED_OPERATOR
     *
     * @param OLD_FIXED_OPERATOR the value for ALRT_SUBSCRIPTION_PARAM.OLD_FIXED_OPERATOR
     */
    public void setOLD_FIXED_OPERATOR(String OLD_FIXED_OPERATOR) {
        this.OLD_FIXED_OPERATOR = OLD_FIXED_OPERATOR == null ? null : OLD_FIXED_OPERATOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUBSCRIPTION_PARAM.OLD_FROM_VALUE
     *
     * @return the value of ALRT_SUBSCRIPTION_PARAM.OLD_FROM_VALUE
     */
    public String getOLD_FROM_VALUE() {
        return OLD_FROM_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUBSCRIPTION_PARAM.OLD_FROM_VALUE
     *
     * @param OLD_FROM_VALUE the value for ALRT_SUBSCRIPTION_PARAM.OLD_FROM_VALUE
     */
    public void setOLD_FROM_VALUE(String OLD_FROM_VALUE) {
        this.OLD_FROM_VALUE = OLD_FROM_VALUE == null ? null : OLD_FROM_VALUE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUBSCRIPTION_PARAM.OLD_TO_VALUE
     *
     * @return the value of ALRT_SUBSCRIPTION_PARAM.OLD_TO_VALUE
     */
    public String getOLD_TO_VALUE() {
        return OLD_TO_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUBSCRIPTION_PARAM.OLD_TO_VALUE
     *
     * @param OLD_TO_VALUE the value for ALRT_SUBSCRIPTION_PARAM.OLD_TO_VALUE
     */
    public void setOLD_TO_VALUE(String OLD_TO_VALUE) {
        this.OLD_TO_VALUE = OLD_TO_VALUE == null ? null : OLD_TO_VALUE.trim();
    }
     /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUBSCRIPTION_PARAM.DATE_UPDATED
     *
     * @return the value of ALRT_SUBSCRIPTION_PARAM.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUBSCRIPTION_PARAM.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for ALRT_SUBSCRIPTION_PARAM.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}