package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ALRT_EVT_COMM_INTRNLVO extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_EVT_COMM_INTRNL.EVT_COMM_INTRNL_ID
     */
    private BigDecimal EVT_COMM_INTRNL_ID;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_INTRNL.EVT_ID
     */
    private BigDecimal EVT_ID;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_INTRNL.SENDER_USR_ID
     */
    private String SENDER_USR_ID;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_INTRNL.SENDER_USR_EXPR
     */
    private String SENDER_USR_EXPR;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_INTRNL.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_INTRNL.COMP_DESC
     */
    private String COMP_DESC;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_INTRNL.COMP_CODE_EXPR
     */
    private String COMP_CODE_EXPR;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_INTRNL.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_INTRNL.BRANCH_DESC
     */
    private String BRANCH_DESC;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_INTRNL.BRANCH_CODE_EXPR
     */
    private String BRANCH_CODE_EXPR;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_INTRNL.APP_NAME
     */
    private String APP_NAME;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_INTRNL.APP_NAME_EXPR
     */
    private String APP_NAME_EXPR;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_INTRNL.TODO_KEY
     */
    private String TODO_KEY;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_INTRNL.TODO_PROG_REF
     */
    private String TODO_PROG_REF;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_INTRNL.TODO_PROG_REF_DESC
     */
    private String TODO_PROG_REF_DESC;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_INTRNL.TODO_ALRT
     */
    private String TODO_ALRT;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_INTRNL.TODO_ALRT_DESC
     */
    private String TODO_ALRT_DESC;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_INTRNL.ACTIVATED_YN
     */
    private String ACTIVATED_YN;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_INTRNL.EVT_COMM_INTRNL_ID
     *
     * @return the value of ALRT_EVT_COMM_INTRNL.EVT_COMM_INTRNL_ID
     */
    public BigDecimal getEVT_COMM_INTRNL_ID() {
        return EVT_COMM_INTRNL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_INTRNL.EVT_COMM_INTRNL_ID
     *
     * @param EVT_COMM_INTRNL_ID the value for ALRT_EVT_COMM_INTRNL.EVT_COMM_INTRNL_ID
     */
    public void setEVT_COMM_INTRNL_ID(BigDecimal EVT_COMM_INTRNL_ID) {
        this.EVT_COMM_INTRNL_ID = EVT_COMM_INTRNL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_INTRNL.EVT_ID
     *
     * @return the value of ALRT_EVT_COMM_INTRNL.EVT_ID
     */
    public BigDecimal getEVT_ID() {
        return EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_INTRNL.EVT_ID
     *
     * @param EVT_ID the value for ALRT_EVT_COMM_INTRNL.EVT_ID
     */
    public void setEVT_ID(BigDecimal EVT_ID) {
        this.EVT_ID = EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_INTRNL.SENDER_USR_ID
     *
     * @return the value of ALRT_EVT_COMM_INTRNL.SENDER_USR_ID
     */
    public String getSENDER_USR_ID() {
        return SENDER_USR_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_INTRNL.SENDER_USR_ID
     *
     * @param SENDER_USR_ID the value for ALRT_EVT_COMM_INTRNL.SENDER_USR_ID
     */
    public void setSENDER_USR_ID(String SENDER_USR_ID) {
        this.SENDER_USR_ID = SENDER_USR_ID == null ? null : SENDER_USR_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_INTRNL.SENDER_USR_EXPR
     *
     * @return the value of ALRT_EVT_COMM_INTRNL.SENDER_USR_EXPR
     */
    public String getSENDER_USR_EXPR() {
        return SENDER_USR_EXPR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_INTRNL.SENDER_USR_EXPR
     *
     * @param SENDER_USR_EXPR the value for ALRT_EVT_COMM_INTRNL.SENDER_USR_EXPR
     */
    public void setSENDER_USR_EXPR(String SENDER_USR_EXPR) {
        this.SENDER_USR_EXPR = SENDER_USR_EXPR == null ? null : SENDER_USR_EXPR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_INTRNL.COMP_CODE
     *
     * @return the value of ALRT_EVT_COMM_INTRNL.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_INTRNL.COMP_CODE
     *
     * @param COMP_CODE the value for ALRT_EVT_COMM_INTRNL.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_INTRNL.COMP_DESC
     *
     * @return the value of ALRT_EVT_COMM_INTRNL.COMP_DESC
     */
    public String getCOMP_DESC() {
        return COMP_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_INTRNL.COMP_DESC
     *
     * @param COMP_DESC the value for ALRT_EVT_COMM_INTRNL.COMP_DESC
     */
    public void setCOMP_DESC(String COMP_DESC) {
        this.COMP_DESC = COMP_DESC == null ? null : COMP_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_INTRNL.COMP_CODE_EXPR
     *
     * @return the value of ALRT_EVT_COMM_INTRNL.COMP_CODE_EXPR
     */
    public String getCOMP_CODE_EXPR() {
        return COMP_CODE_EXPR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_INTRNL.COMP_CODE_EXPR
     *
     * @param COMP_CODE_EXPR the value for ALRT_EVT_COMM_INTRNL.COMP_CODE_EXPR
     */
    public void setCOMP_CODE_EXPR(String COMP_CODE_EXPR) {
        this.COMP_CODE_EXPR = COMP_CODE_EXPR == null ? null : COMP_CODE_EXPR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_INTRNL.BRANCH_CODE
     *
     * @return the value of ALRT_EVT_COMM_INTRNL.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_INTRNL.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for ALRT_EVT_COMM_INTRNL.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_INTRNL.BRANCH_DESC
     *
     * @return the value of ALRT_EVT_COMM_INTRNL.BRANCH_DESC
     */
    public String getBRANCH_DESC() {
        return BRANCH_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_INTRNL.BRANCH_DESC
     *
     * @param BRANCH_DESC the value for ALRT_EVT_COMM_INTRNL.BRANCH_DESC
     */
    public void setBRANCH_DESC(String BRANCH_DESC) {
        this.BRANCH_DESC = BRANCH_DESC == null ? null : BRANCH_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_INTRNL.BRANCH_CODE_EXPR
     *
     * @return the value of ALRT_EVT_COMM_INTRNL.BRANCH_CODE_EXPR
     */
    public String getBRANCH_CODE_EXPR() {
        return BRANCH_CODE_EXPR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_INTRNL.BRANCH_CODE_EXPR
     *
     * @param BRANCH_CODE_EXPR the value for ALRT_EVT_COMM_INTRNL.BRANCH_CODE_EXPR
     */
    public void setBRANCH_CODE_EXPR(String BRANCH_CODE_EXPR) {
        this.BRANCH_CODE_EXPR = BRANCH_CODE_EXPR == null ? null : BRANCH_CODE_EXPR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_INTRNL.APP_NAME
     *
     * @return the value of ALRT_EVT_COMM_INTRNL.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_INTRNL.APP_NAME
     *
     * @param APP_NAME the value for ALRT_EVT_COMM_INTRNL.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_INTRNL.APP_NAME_EXPR
     *
     * @return the value of ALRT_EVT_COMM_INTRNL.APP_NAME_EXPR
     */
    public String getAPP_NAME_EXPR() {
        return APP_NAME_EXPR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_INTRNL.APP_NAME_EXPR
     *
     * @param APP_NAME_EXPR the value for ALRT_EVT_COMM_INTRNL.APP_NAME_EXPR
     */
    public void setAPP_NAME_EXPR(String APP_NAME_EXPR) {
        this.APP_NAME_EXPR = APP_NAME_EXPR == null ? null : APP_NAME_EXPR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_INTRNL.TODO_KEY
     *
     * @return the value of ALRT_EVT_COMM_INTRNL.TODO_KEY
     */
    public String getTODO_KEY() {
        return TODO_KEY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_INTRNL.TODO_KEY
     *
     * @param TODO_KEY the value for ALRT_EVT_COMM_INTRNL.TODO_KEY
     */
    public void setTODO_KEY(String TODO_KEY) {
        this.TODO_KEY = TODO_KEY == null ? null : TODO_KEY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_INTRNL.TODO_PROG_REF
     *
     * @return the value of ALRT_EVT_COMM_INTRNL.TODO_PROG_REF
     */
    public String getTODO_PROG_REF() {
        return TODO_PROG_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_INTRNL.TODO_PROG_REF
     *
     * @param TODO_PROG_REF the value for ALRT_EVT_COMM_INTRNL.TODO_PROG_REF
     */
    public void setTODO_PROG_REF(String TODO_PROG_REF) {
        this.TODO_PROG_REF = TODO_PROG_REF == null ? null : TODO_PROG_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_INTRNL.TODO_PROG_REF_DESC
     *
     * @return the value of ALRT_EVT_COMM_INTRNL.TODO_PROG_REF_DESC
     */
    public String getTODO_PROG_REF_DESC() {
        return TODO_PROG_REF_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_INTRNL.TODO_PROG_REF_DESC
     *
     * @param TODO_PROG_REF_DESC the value for ALRT_EVT_COMM_INTRNL.TODO_PROG_REF_DESC
     */
    public void setTODO_PROG_REF_DESC(String TODO_PROG_REF_DESC) {
        this.TODO_PROG_REF_DESC = TODO_PROG_REF_DESC == null ? null : TODO_PROG_REF_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_INTRNL.TODO_ALRT
     *
     * @return the value of ALRT_EVT_COMM_INTRNL.TODO_ALRT
     */
    public String getTODO_ALRT() {
        return TODO_ALRT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_INTRNL.TODO_ALRT
     *
     * @param TODO_ALRT the value for ALRT_EVT_COMM_INTRNL.TODO_ALRT
     */
    public void setTODO_ALRT(String TODO_ALRT) {
        this.TODO_ALRT = TODO_ALRT == null ? null : TODO_ALRT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_INTRNL.TODO_ALRT_DESC
     *
     * @return the value of ALRT_EVT_COMM_INTRNL.TODO_ALRT_DESC
     */
    public String getTODO_ALRT_DESC() {
        return TODO_ALRT_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_INTRNL.TODO_ALRT_DESC
     *
     * @param TODO_ALRT_DESC the value for ALRT_EVT_COMM_INTRNL.TODO_ALRT_DESC
     */
    public void setTODO_ALRT_DESC(String TODO_ALRT_DESC) {
        this.TODO_ALRT_DESC = TODO_ALRT_DESC == null ? null : TODO_ALRT_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_INTRNL.ACTIVATED_YN
     *
     * @return the value of ALRT_EVT_COMM_INTRNL.ACTIVATED_YN
     */
    public String getACTIVATED_YN() {
        return ACTIVATED_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_INTRNL.ACTIVATED_YN
     *
     * @param ACTIVATED_YN the value for ALRT_EVT_COMM_INTRNL.ACTIVATED_YN
     */
    public void setACTIVATED_YN(String ACTIVATED_YN) {
        this.ACTIVATED_YN = ACTIVATED_YN == null ? null : ACTIVATED_YN.trim();
    }
}