package com.path.dbmaps.vo;

public class ALRT_EMAIL_TEMPLATEVOWithBLOBs extends ALRT_EMAIL_TEMPLATEVO {
    /**
     * This field corresponds to the database column ALRT_EMAIL_TEMPLATE.TEMPLATE_FILE
     */
    private byte[] TEMPLATE_FILE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EMAIL_TEMPLATE.TEMPLATE_FILE
     *
     * @return the value of ALRT_EMAIL_TEMPLATE.TEMPLATE_FILE
     */
    public byte[] getTEMPLATE_FILE() {
        return TEMPLATE_FILE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EMAIL_TEMPLATE.TEMPLATE_FILE
     *
     * @param TEMPLATE_FILE the value for ALRT_EMAIL_TEMPLATE.TEMPLATE_FILE
     */
    public void setTEMPLATE_FILE(byte[] TEMPLATE_FILE) {
        this.TEMPLATE_FILE = TEMPLATE_FILE;
    }
}