package com.path.dbmaps.vo;

public class ALRT_FIXED_PARAMVOWithBLOBs extends ALRT_FIXED_PARAMVO {
    /**
     * This field corresponds to the database column ALRT_FIXED_PARAM.FROM_VALUE
     */
    private String FROM_VALUE;

    /**
     * This field corresponds to the database column ALRT_FIXED_PARAM.TO_VALUE
     */
    private String TO_VALUE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_FIXED_PARAM.FROM_VALUE
     *
     * @return the value of ALRT_FIXED_PARAM.FROM_VALUE
     */
    public String getFROM_VALUE() {
        return FROM_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_FIXED_PARAM.FROM_VALUE
     *
     * @param FROM_VALUE the value for ALRT_FIXED_PARAM.FROM_VALUE
     */
    public void setFROM_VALUE(String FROM_VALUE) {
        this.FROM_VALUE = FROM_VALUE == null ? null : FROM_VALUE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_FIXED_PARAM.TO_VALUE
     *
     * @return the value of ALRT_FIXED_PARAM.TO_VALUE
     */
    public String getTO_VALUE() {
        return TO_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_FIXED_PARAM.TO_VALUE
     *
     * @param TO_VALUE the value for ALRT_FIXED_PARAM.TO_VALUE
     */
    public void setTO_VALUE(String TO_VALUE) {
        this.TO_VALUE = TO_VALUE == null ? null : TO_VALUE.trim();
    }
}