package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ALRT_EVTVOKey extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_EVT.EVT_ID
     */
    private BigDecimal EVT_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT.EVT_ID
     *
     * @return the value of ALRT_EVT.EVT_ID
     */
    public BigDecimal getEVT_ID() {
        return EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT.EVT_ID
     *
     * @param EVT_ID the value for ALRT_EVT.EVT_ID
     */
    public void setEVT_ID(BigDecimal EVT_ID) {
        this.EVT_ID = EVT_ID;
    }
}