package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class ALRT_CONTROLVO extends ALRT_CONTROLVOKey {
    /**
     * This field corresponds to the database column ALRT_CONTROL.CTRL_VALUE
     */
    private BigDecimal CTRL_VALUE;

    /**
     * This field corresponds to the database column ALRT_CONTROL.CTRL_DESCRIPTION
     */
    private String CTRL_DESCRIPTION;

    /**
     * This field corresponds to the database column ALRT_CONTROL.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column ALRT_CONTROL.CTRL_VALUE_CHARACTER
     */
    private String CTRL_VALUE_CHARACTER;
    
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_CONTROL.CTRL_VALUE
     *
     * @return the value of ALRT_CONTROL.CTRL_VALUE
     */
    public BigDecimal getCTRL_VALUE() {
        return CTRL_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_CONTROL.CTRL_VALUE
     *
     * @param CTRL_VALUE the value for ALRT_CONTROL.CTRL_VALUE
     */
    public void setCTRL_VALUE(BigDecimal CTRL_VALUE) {
        this.CTRL_VALUE = CTRL_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_CONTROL.CTRL_DESCRIPTION
     *
     * @return the value of ALRT_CONTROL.CTRL_DESCRIPTION
     */
    public String getCTRL_DESCRIPTION() {
        return CTRL_DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_CONTROL.CTRL_DESCRIPTION
     *
     * @param CTRL_DESCRIPTION the value for ALRT_CONTROL.CTRL_DESCRIPTION
     */
    public void setCTRL_DESCRIPTION(String CTRL_DESCRIPTION) {
        this.CTRL_DESCRIPTION = CTRL_DESCRIPTION == null ? null : CTRL_DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_CONTROL.COMP_CODE
     *
     * @return the value of ALRT_CONTROL.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_CONTROL.COMP_CODE
     *
     * @param COMP_CODE the value for ALRT_CONTROL.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_CONTROL.CTRL_VALUE_CHARACTER
     *
     * @return the value of ALRT_CONTROL.CTRL_VALUE_CHARACTER
     */
    public String getCTRL_VALUE_CHARACTER() {
		return CTRL_VALUE_CHARACTER;
	}
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_CONTROL.CTRL_VALUE_CHARACTER
     *
     * @param CTRL_VALUE_CHARACTER the value for ALRT_CONTROL.CTRL_VALUE_CHARACTER
     */
	public void setCTRL_VALUE_CHARACTER(String CTRL_VALUE_CHARACTER) {
		this.CTRL_VALUE_CHARACTER = CTRL_VALUE_CHARACTER;
	}
}