package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ALRT_SUB_EVT_TMPVO extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.EVT_ID
     */
    private BigDecimal EVT_ID;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.SUB_ID
     */
    private BigDecimal SUB_ID;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.ID
     */
    private BigDecimal ID;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.REL_ID
     */
    private BigDecimal REL_ID;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.REL_TYPE
     */
    private String REL_TYPE;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.EVT_DESC_ENG
     */
    private String EVT_DESC_ENG;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.EVT_TYPE
     */
    private String EVT_TYPE;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.SUB_TYPE
     */
    private String SUB_TYPE;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.SUB_EVT_STATUS
     */
    private String SUB_EVT_STATUS;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.FULL_NAME_ENG
     */
    private String FULL_NAME_ENG;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.SESSION_ID
     */
    private String SESSION_ID;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.EMAIL_YN
     */
    private String EMAIL_YN;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.FILE_YN
     */
    private String FILE_YN;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.FACEBOOK_PRIVATE_WALL_YN
     */
    private String FACEBOOK_PRIVATE_WALL_YN;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.INBOX_YN
     */
    private String INBOX_YN;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.MOBILE_PUSH_NOTIFICATION_YN
     */
    private String MOBILE_PUSH_NOTIFICATION_YN;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.SMS_YN
     */
    private String SMS_YN;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.TWITTER_DIRECT_MESSAGE_YN
     */
    private String TWITTER_DIRECT_MESSAGE_YN;
    
    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.SRC_CONTACT_TYPE
     */
    private String SRC_CONTACT_TYPE;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.USR_ID
     */
    private String USR_ID;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.MOBILE_PHONE
     */
    private String MOBILE_PHONE;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.EMAIL_ID
     */
    private String EMAIL_ID;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.CHANNEL_END_USR_ID
     */
    private String CHANNEL_END_USR_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.EVT_ID
     *
     * @return the value of ALRT_SUB_EVT_TMP.EVT_ID
     */
    public BigDecimal getEVT_ID() {
        return EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.EVT_ID
     *
     * @param EVT_ID the value for ALRT_SUB_EVT_TMP.EVT_ID
     */
    public void setEVT_ID(BigDecimal EVT_ID) {
        this.EVT_ID = EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.SUB_ID
     *
     * @return the value of ALRT_SUB_EVT_TMP.SUB_ID
     */
    public BigDecimal getSUB_ID() {
        return SUB_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.SUB_ID
     *
     * @param SUB_ID the value for ALRT_SUB_EVT_TMP.SUB_ID
     */
    public void setSUB_ID(BigDecimal SUB_ID) {
        this.SUB_ID = SUB_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.ID
     *
     * @return the value of ALRT_SUB_EVT_TMP.ID
     */
    public BigDecimal getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.ID
     *
     * @param ID the value for ALRT_SUB_EVT_TMP.ID
     */
    public void setID(BigDecimal ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.REL_ID
     *
     * @return the value of ALRT_SUB_EVT_TMP.REL_ID
     */
    public BigDecimal getREL_ID() {
        return REL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.REL_ID
     *
     * @param REL_ID the value for ALRT_SUB_EVT_TMP.REL_ID
     */
    public void setREL_ID(BigDecimal REL_ID) {
        this.REL_ID = REL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.REL_TYPE
     *
     * @return the value of ALRT_SUB_EVT_TMP.REL_TYPE
     */
    public String getREL_TYPE() {
        return REL_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.REL_TYPE
     *
     * @param REL_TYPE the value for ALRT_SUB_EVT_TMP.REL_TYPE
     */
    public void setREL_TYPE(String REL_TYPE) {
        this.REL_TYPE = REL_TYPE == null ? null : REL_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.EVT_DESC_ENG
     *
     * @return the value of ALRT_SUB_EVT_TMP.EVT_DESC_ENG
     */
    public String getEVT_DESC_ENG() {
        return EVT_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.EVT_DESC_ENG
     *
     * @param EVT_DESC_ENG the value for ALRT_SUB_EVT_TMP.EVT_DESC_ENG
     */
    public void setEVT_DESC_ENG(String EVT_DESC_ENG) {
        this.EVT_DESC_ENG = EVT_DESC_ENG == null ? null : EVT_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.EVT_TYPE
     *
     * @return the value of ALRT_SUB_EVT_TMP.EVT_TYPE
     */
    public String getEVT_TYPE() {
        return EVT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.EVT_TYPE
     *
     * @param EVT_TYPE the value for ALRT_SUB_EVT_TMP.EVT_TYPE
     */
    public void setEVT_TYPE(String EVT_TYPE) {
        this.EVT_TYPE = EVT_TYPE == null ? null : EVT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.SUB_TYPE
     *
     * @return the value of ALRT_SUB_EVT_TMP.SUB_TYPE
     */
    public String getSUB_TYPE() {
        return SUB_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.SUB_TYPE
     *
     * @param SUB_TYPE the value for ALRT_SUB_EVT_TMP.SUB_TYPE
     */
    public void setSUB_TYPE(String SUB_TYPE) {
        this.SUB_TYPE = SUB_TYPE == null ? null : SUB_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.SUB_EVT_STATUS
     *
     * @return the value of ALRT_SUB_EVT_TMP.SUB_EVT_STATUS
     */
    public String getSUB_EVT_STATUS() {
        return SUB_EVT_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.SUB_EVT_STATUS
     *
     * @param SUB_EVT_STATUS the value for ALRT_SUB_EVT_TMP.SUB_EVT_STATUS
     */
    public void setSUB_EVT_STATUS(String SUB_EVT_STATUS) {
        this.SUB_EVT_STATUS = SUB_EVT_STATUS == null ? null : SUB_EVT_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.FULL_NAME_ENG
     *
     * @return the value of ALRT_SUB_EVT_TMP.FULL_NAME_ENG
     */
    public String getFULL_NAME_ENG() {
        return FULL_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.FULL_NAME_ENG
     *
     * @param FULL_NAME_ENG the value for ALRT_SUB_EVT_TMP.FULL_NAME_ENG
     */
    public void setFULL_NAME_ENG(String FULL_NAME_ENG) {
        this.FULL_NAME_ENG = FULL_NAME_ENG == null ? null : FULL_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.SESSION_ID
     *
     * @return the value of ALRT_SUB_EVT_TMP.SESSION_ID
     */
    public String getSESSION_ID() {
        return SESSION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.SESSION_ID
     *
     * @param SESSION_ID the value for ALRT_SUB_EVT_TMP.SESSION_ID
     */
    public void setSESSION_ID(String SESSION_ID) {
        this.SESSION_ID = SESSION_ID == null ? null : SESSION_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.EMAIL_YN
     *
     * @return the value of ALRT_SUB_EVT_TMP.EMAIL_YN
     */
    public String getEMAIL_YN() {
        return EMAIL_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.EMAIL_YN
     *
     * @param EMAIL_YN the value for ALRT_SUB_EVT_TMP.EMAIL_YN
     */
    public void setEMAIL_YN(String EMAIL_YN) {
        this.EMAIL_YN = EMAIL_YN == null ? null : EMAIL_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.FILE_YN
     *
     * @return the value of ALRT_SUB_EVT_TMP.FILE_YN
     */
    public String getFILE_YN() {
        return FILE_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.FILE_YN
     *
     * @param FILE_YN the value for ALRT_SUB_EVT_TMP.FILE_YN
     */
    public void setFILE_YN(String FILE_YN) {
        this.FILE_YN = FILE_YN == null ? null : FILE_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.FACEBOOK_PRIVATE_WALL_YN
     *
     * @return the value of ALRT_SUB_EVT_TMP.FACEBOOK_PRIVATE_WALL_YN
     */
    public String getFACEBOOK_PRIVATE_WALL_YN() {
        return FACEBOOK_PRIVATE_WALL_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.FACEBOOK_PRIVATE_WALL_YN
     *
     * @param FACEBOOK_PRIVATE_WALL_YN the value for ALRT_SUB_EVT_TMP.FACEBOOK_PRIVATE_WALL_YN
     */
    public void setFACEBOOK_PRIVATE_WALL_YN(String FACEBOOK_PRIVATE_WALL_YN) {
        this.FACEBOOK_PRIVATE_WALL_YN = FACEBOOK_PRIVATE_WALL_YN == null ? null : FACEBOOK_PRIVATE_WALL_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.INBOX_YN
     *
     * @return the value of ALRT_SUB_EVT_TMP.INBOX_YN
     */
    public String getINBOX_YN() {
        return INBOX_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.INBOX_YN
     *
     * @param INBOX_YN the value for ALRT_SUB_EVT_TMP.INBOX_YN
     */
    public void setINBOX_YN(String INBOX_YN) {
        this.INBOX_YN = INBOX_YN == null ? null : INBOX_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.MOBILE_PUSH_NOTIFICATION_YN
     *
     * @return the value of ALRT_SUB_EVT_TMP.MOBILE_PUSH_NOTIFICATION_YN
     */
    public String getMOBILE_PUSH_NOTIFICATION_YN() {
        return MOBILE_PUSH_NOTIFICATION_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.MOBILE_PUSH_NOTIFICATION_YN
     *
     * @param MOBILE_PUSH_NOTIFICATION_YN the value for ALRT_SUB_EVT_TMP.MOBILE_PUSH_NOTIFICATION_YN
     */
    public void setMOBILE_PUSH_NOTIFICATION_YN(String MOBILE_PUSH_NOTIFICATION_YN) {
        this.MOBILE_PUSH_NOTIFICATION_YN = MOBILE_PUSH_NOTIFICATION_YN == null ? null : MOBILE_PUSH_NOTIFICATION_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.SMS_YN
     *
     * @return the value of ALRT_SUB_EVT_TMP.SMS_YN
     */
    public String getSMS_YN() {
        return SMS_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.SMS_YN
     *
     * @param SMS_YN the value for ALRT_SUB_EVT_TMP.SMS_YN
     */
    public void setSMS_YN(String SMS_YN) {
        this.SMS_YN = SMS_YN == null ? null : SMS_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.TWITTER_DIRECT_MESSAGE_YN
     *
     * @return the value of ALRT_SUB_EVT_TMP.TWITTER_DIRECT_MESSAGE_YN
     */
    public String getTWITTER_DIRECT_MESSAGE_YN() {
        return TWITTER_DIRECT_MESSAGE_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.TWITTER_DIRECT_MESSAGE_YN
     *
     * @param TWITTER_DIRECT_MESSAGE_YN the value for ALRT_SUB_EVT_TMP.TWITTER_DIRECT_MESSAGE_YN
     */
    public void setTWITTER_DIRECT_MESSAGE_YN(String TWITTER_DIRECT_MESSAGE_YN) {
        this.TWITTER_DIRECT_MESSAGE_YN = TWITTER_DIRECT_MESSAGE_YN == null ? null : TWITTER_DIRECT_MESSAGE_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.SRC_CONTACT_TYPE
     *
     * @return the value of ALRT_SUB_EVT_TMP.SRC_CONTACT_TYPE
     */
	public String getSRC_CONTACT_TYPE() {
		return SRC_CONTACT_TYPE;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.SRC_CONTACT_TYPE
     *
     * @param SRC_CONTACT_TYPE the value for ALRT_SUB_EVT_TMP.SRC_CONTACT_TYPE
     */
    public void setSRC_CONTACT_TYPE(String SRC_CONTACT_TYPE) {
        this.SRC_CONTACT_TYPE = SRC_CONTACT_TYPE == null ? null : SRC_CONTACT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.CIF_NO
     *
     * @return the value of ALRT_SUB_EVT_TMP.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.CIF_NO
     *
     * @param CIF_NO the value for ALRT_SUB_EVT_TMP.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.USR_ID
     *
     * @return the value of ALRT_SUB_EVT_TMP.USR_ID
     */
    public String getUSR_ID() {
        return USR_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.USR_ID
     *
     * @param USR_ID the value for ALRT_SUB_EVT_TMP.USR_ID
     */
    public void setUSR_ID(String USR_ID) {
        this.USR_ID = USR_ID == null ? null : USR_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.MOBILE_PHONE
     *
     * @return the value of ALRT_SUB_EVT_TMP.MOBILE_PHONE
     */
    public String getMOBILE_PHONE() {
        return MOBILE_PHONE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.MOBILE_PHONE
     *
     * @param MOBILE_PHONE the value for ALRT_SUB_EVT_TMP.MOBILE_PHONE
     */
    public void setMOBILE_PHONE(String MOBILE_PHONE) {
        this.MOBILE_PHONE = MOBILE_PHONE == null ? null : MOBILE_PHONE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.EMAIL_ID
     *
     * @return the value of ALRT_SUB_EVT_TMP.EMAIL_ID
     */
    public String getEMAIL_ID() {
        return EMAIL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.EMAIL_ID
     *
     * @param EMAIL_ID the value for ALRT_SUB_EVT_TMP.EMAIL_ID
     */
    public void setEMAIL_ID(String EMAIL_ID) {
        this.EMAIL_ID = EMAIL_ID == null ? null : EMAIL_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.CHANNEL_END_USR_ID
     *
     * @return the value of ALRT_SUB_EVT_TMP.CHANNEL_END_USR_ID
     */
    public String getCHANNEL_END_USR_ID() {
        return CHANNEL_END_USR_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.CHANNEL_END_USR_ID
     *
     * @param CHANNEL_END_USR_ID the value for ALRT_SUB_EVT_TMP.CHANNEL_END_USR_ID
     */
    public void setCHANNEL_END_USR_ID(String CHANNEL_END_USR_ID) {
        this.CHANNEL_END_USR_ID = CHANNEL_END_USR_ID == null ? null : CHANNEL_END_USR_ID.trim();
    }
}