package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ALRT_TAGS_DEFVO extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_TAGS_DEF.ALRT_TAGS_DEF_ID
     */
    private BigDecimal ALRT_TAGS_DEF_ID;

    /**
     * This field corresponds to the database column ALRT_TAGS_DEF.TAG_NAME
     */
    private String TAG_NAME;

    /**
     * This field corresponds to the database column ALRT_TAGS_DEF.TAG_DESCRIPTION
     */
    private String TAG_DESCRIPTION;

    /**
     * This field corresponds to the database column ALRT_TAGS_DEF.IS_CUSTOM_YN
     */
    private String IS_CUSTOM_YN;

    /**
     * This field corresponds to the database column ALRT_TAGS_DEF.COLUMN_NAME
     */
    private String COLUMN_NAME;

    /**
     * This field corresponds to the database column ALRT_TAGS_DEF.EVT_ID
     */
    private BigDecimal EVT_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_TAGS_DEF.ALRT_TAGS_DEF_ID
     *
     * @return the value of ALRT_TAGS_DEF.ALRT_TAGS_DEF_ID
     */
    public BigDecimal getALRT_TAGS_DEF_ID() {
        return ALRT_TAGS_DEF_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_TAGS_DEF.ALRT_TAGS_DEF_ID
     *
     * @param ALRT_TAGS_DEF_ID the value for ALRT_TAGS_DEF.ALRT_TAGS_DEF_ID
     */
    public void setALRT_TAGS_DEF_ID(BigDecimal ALRT_TAGS_DEF_ID) {
        this.ALRT_TAGS_DEF_ID = ALRT_TAGS_DEF_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_TAGS_DEF.TAG_NAME
     *
     * @return the value of ALRT_TAGS_DEF.TAG_NAME
     */
    public String getTAG_NAME() {
        return TAG_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_TAGS_DEF.TAG_NAME
     *
     * @param TAG_NAME the value for ALRT_TAGS_DEF.TAG_NAME
     */
    public void setTAG_NAME(String TAG_NAME) {
        this.TAG_NAME = TAG_NAME == null ? null : TAG_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_TAGS_DEF.TAG_DESCRIPTION
     *
     * @return the value of ALRT_TAGS_DEF.TAG_DESCRIPTION
     */
    public String getTAG_DESCRIPTION() {
        return TAG_DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_TAGS_DEF.TAG_DESCRIPTION
     *
     * @param TAG_DESCRIPTION the value for ALRT_TAGS_DEF.TAG_DESCRIPTION
     */
    public void setTAG_DESCRIPTION(String TAG_DESCRIPTION) {
        this.TAG_DESCRIPTION = TAG_DESCRIPTION == null ? null : TAG_DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_TAGS_DEF.IS_CUSTOM_YN
     *
     * @return the value of ALRT_TAGS_DEF.IS_CUSTOM_YN
     */
    public String getIS_CUSTOM_YN() {
        return IS_CUSTOM_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_TAGS_DEF.IS_CUSTOM_YN
     *
     * @param IS_CUSTOM_YN the value for ALRT_TAGS_DEF.IS_CUSTOM_YN
     */
    public void setIS_CUSTOM_YN(String IS_CUSTOM_YN) {
        this.IS_CUSTOM_YN = IS_CUSTOM_YN == null ? null : IS_CUSTOM_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_TAGS_DEF.COLUMN_NAME
     *
     * @return the value of ALRT_TAGS_DEF.COLUMN_NAME
     */
    public String getCOLUMN_NAME() {
        return COLUMN_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_TAGS_DEF.COLUMN_NAME
     *
     * @param COLUMN_NAME the value for ALRT_TAGS_DEF.COLUMN_NAME
     */
    public void setCOLUMN_NAME(String COLUMN_NAME) {
        this.COLUMN_NAME = COLUMN_NAME == null ? null : COLUMN_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_TAGS_DEF.EVT_ID
     *
     * @return the value of ALRT_TAGS_DEF.EVT_ID
     */
    public BigDecimal getEVT_ID() {
        return EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_TAGS_DEF.EVT_ID
     *
     * @param EVT_ID the value for ALRT_TAGS_DEF.EVT_ID
     */
    public void setEVT_ID(BigDecimal EVT_ID) {
        this.EVT_ID = EVT_ID;
    }
}