package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ALRT_SUB_EVT_TMPVOKey extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.EVT_ID
     */
    private BigDecimal EVT_ID;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_TMP.SUB_ID
     */
    private BigDecimal SUB_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.EVT_ID
     *
     * @return the value of ALRT_SUB_EVT_TMP.EVT_ID
     */
    public BigDecimal getEVT_ID() {
        return EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.EVT_ID
     *
     * @param EVT_ID the value for ALRT_SUB_EVT_TMP.EVT_ID
     */
    public void setEVT_ID(BigDecimal EVT_ID) {
        this.EVT_ID = EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_TMP.SUB_ID
     *
     * @return the value of ALRT_SUB_EVT_TMP.SUB_ID
     */
    public BigDecimal getSUB_ID() {
        return SUB_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_TMP.SUB_ID
     *
     * @param SUB_ID the value for ALRT_SUB_EVT_TMP.SUB_ID
     */
    public void setSUB_ID(BigDecimal SUB_ID) {
        this.SUB_ID = SUB_ID;
    }
}