package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ALRT_EVT_GRPVOKey extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_EVT_GRP.EVT_ID
     */
    private BigDecimal EVT_ID;

    /**
     * This field corresponds to the database column ALRT_EVT_GRP.GRP_ID
     */
    private BigDecimal GRP_ID;

    /**
     * This field corresponds to the database column ALRT_EVT_GRP.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_GRP.EVT_ID
     *
     * @return the value of ALRT_EVT_GRP.EVT_ID
     */
    public BigDecimal getEVT_ID() {
        return EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_GRP.EVT_ID
     *
     * @param EVT_ID the value for ALRT_EVT_GRP.EVT_ID
     */
    public void setEVT_ID(BigDecimal EVT_ID) {
        this.EVT_ID = EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_GRP.GRP_ID
     *
     * @return the value of ALRT_EVT_GRP.GRP_ID
     */
    public BigDecimal getGRP_ID() {
        return GRP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_GRP.GRP_ID
     *
     * @param GRP_ID the value for ALRT_EVT_GRP.GRP_ID
     */
    public void setGRP_ID(BigDecimal GRP_ID) {
        this.GRP_ID = GRP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_GRP.LINE_NO
     *
     * @return the value of ALRT_EVT_GRP.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_GRP.LINE_NO
     *
     * @param LINE_NO the value for ALRT_EVT_GRP.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }
}