package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ALRT_SUB_MULT_TMPVOKey extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.ID
     */
    private BigDecimal ID;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.SESSION_ID
     */
    private String SESSION_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.ID
     *
     * @return the value of ALRT_SUB_MULT_TMP.ID
     */
    public BigDecimal getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.ID
     *
     * @param ID the value for ALRT_SUB_MULT_TMP.ID
     */
    public void setID(BigDecimal ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.SESSION_ID
     *
     * @return the value of ALRT_SUB_MULT_TMP.SESSION_ID
     */
    public String getSESSION_ID() {
        return SESSION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.SESSION_ID
     *
     * @param SESSION_ID the value for ALRT_SUB_MULT_TMP.SESSION_ID
     */
    public void setSESSION_ID(String SESSION_ID) {
        this.SESSION_ID = SESSION_ID == null ? null : SESSION_ID.trim();
    }
}