package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ALRT_GRPVOKey extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_GRP.GRP_ID
     */
    private BigDecimal GRP_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_GRP.GRP_ID
     *
     * @return the value of ALRT_GRP.GRP_ID
     */
    public BigDecimal getGRP_ID() {
        return GRP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_GRP.GRP_ID
     *
     * @param GRP_ID the value for ALRT_GRP.GRP_ID
     */
    public void setGRP_ID(BigDecimal GRP_ID) {
        this.GRP_ID = GRP_ID;
    }
}