package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;

public class ALRT_CONTROLVOKey extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_CONTROL.CTRL_REFERENCE
     */
    private String CTRL_REFERENCE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_CONTROL.CTRL_REFERENCE
     *
     * @return the value of ALRT_CONTROL.CTRL_REFERENCE
     */
    public String getCTRL_REFERENCE() {
        return CTRL_REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_CONTROL.CTRL_REFERENCE
     *
     * @param CTRL_REFERENCE the value for ALRT_CONTROL.CTRL_REFERENCE
     */
    public void setCTRL_REFERENCE(String CTRL_REFERENCE) {
        this.CTRL_REFERENCE = CTRL_REFERENCE == null ? null : CTRL_REFERENCE.trim();
    }
}