package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class ALRT_SUB_MULT_TMPVO extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.ID
     */
    private BigDecimal ID;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.SESSION_ID
     */
    private String SESSION_ID;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.GL_CODE
     */
    private BigDecimal GL_CODE;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.CIF_SUB_NO
     */
    private BigDecimal CIF_SUB_NO;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.SL_NO
     */
    private BigDecimal SL_NO;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.USR_ID
     */
    private String USR_ID;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.MOBILE_PHONE
     */
    private String MOBILE_PHONE;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.EMAIL_ID
     */
    private String EMAIL_ID;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.SUB_TYPE
     */
    private String SUB_TYPE;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.DATE_AUTHORIZED
     */
    private Date DATE_AUTHORIZED;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.AUTHORIZED_BY
     */
    private String AUTHORIZED_BY;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.LONG_NAME_ARAB
     */
    private String LONG_NAME_ARAB;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.MIDDLE_NAME_ARAB
     */
    private String MIDDLE_NAME_ARAB;

    /**
     * This field corresponds to the database column ALRT_SUB_MULT_TMP.MIDDLE_NAME_ENG
     */
    private String MIDDLE_NAME_ENG;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.ID
     *
     * @return the value of ALRT_SUB_MULT_TMP.ID
     */
    public BigDecimal getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.ID
     *
     * @param ID the value for ALRT_SUB_MULT_TMP.ID
     */
    public void setID(BigDecimal ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.SESSION_ID
     *
     * @return the value of ALRT_SUB_MULT_TMP.SESSION_ID
     */
    public String getSESSION_ID() {
        return SESSION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.SESSION_ID
     *
     * @param SESSION_ID the value for ALRT_SUB_MULT_TMP.SESSION_ID
     */
    public void setSESSION_ID(String SESSION_ID) {
        this.SESSION_ID = SESSION_ID == null ? null : SESSION_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.COMP_CODE
     *
     * @return the value of ALRT_SUB_MULT_TMP.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.COMP_CODE
     *
     * @param COMP_CODE the value for ALRT_SUB_MULT_TMP.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.BRANCH_CODE
     *
     * @return the value of ALRT_SUB_MULT_TMP.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for ALRT_SUB_MULT_TMP.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.CURRENCY_CODE
     *
     * @return the value of ALRT_SUB_MULT_TMP.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for ALRT_SUB_MULT_TMP.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.GL_CODE
     *
     * @return the value of ALRT_SUB_MULT_TMP.GL_CODE
     */
    public BigDecimal getGL_CODE() {
        return GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.GL_CODE
     *
     * @param GL_CODE the value for ALRT_SUB_MULT_TMP.GL_CODE
     */
    public void setGL_CODE(BigDecimal GL_CODE) {
        this.GL_CODE = GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.CIF_SUB_NO
     *
     * @return the value of ALRT_SUB_MULT_TMP.CIF_SUB_NO
     */
    public BigDecimal getCIF_SUB_NO() {
        return CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.CIF_SUB_NO
     *
     * @param CIF_SUB_NO the value for ALRT_SUB_MULT_TMP.CIF_SUB_NO
     */
    public void setCIF_SUB_NO(BigDecimal CIF_SUB_NO) {
        this.CIF_SUB_NO = CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.SL_NO
     *
     * @return the value of ALRT_SUB_MULT_TMP.SL_NO
     */
    public BigDecimal getSL_NO() {
        return SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.SL_NO
     *
     * @param SL_NO the value for ALRT_SUB_MULT_TMP.SL_NO
     */
    public void setSL_NO(BigDecimal SL_NO) {
        this.SL_NO = SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.CIF_NO
     *
     * @return the value of ALRT_SUB_MULT_TMP.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.CIF_NO
     *
     * @param CIF_NO the value for ALRT_SUB_MULT_TMP.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.USR_ID
     *
     * @return the value of ALRT_SUB_MULT_TMP.USR_ID
     */
    public String getUSR_ID() {
        return USR_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.USR_ID
     *
     * @param USR_ID the value for ALRT_SUB_MULT_TMP.USR_ID
     */
    public void setUSR_ID(String USR_ID) {
        this.USR_ID = USR_ID == null ? null : USR_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.MOBILE_PHONE
     *
     * @return the value of ALRT_SUB_MULT_TMP.MOBILE_PHONE
     */
    public String getMOBILE_PHONE() {
        return MOBILE_PHONE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.MOBILE_PHONE
     *
     * @param MOBILE_PHONE the value for ALRT_SUB_MULT_TMP.MOBILE_PHONE
     */
    public void setMOBILE_PHONE(String MOBILE_PHONE) {
        this.MOBILE_PHONE = MOBILE_PHONE == null ? null : MOBILE_PHONE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.EMAIL_ID
     *
     * @return the value of ALRT_SUB_MULT_TMP.EMAIL_ID
     */
    public String getEMAIL_ID() {
        return EMAIL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.EMAIL_ID
     *
     * @param EMAIL_ID the value for ALRT_SUB_MULT_TMP.EMAIL_ID
     */
    public void setEMAIL_ID(String EMAIL_ID) {
        this.EMAIL_ID = EMAIL_ID == null ? null : EMAIL_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.SUB_TYPE
     *
     * @return the value of ALRT_SUB_MULT_TMP.SUB_TYPE
     */
    public String getSUB_TYPE() {
        return SUB_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.SUB_TYPE
     *
     * @param SUB_TYPE the value for ALRT_SUB_MULT_TMP.SUB_TYPE
     */
    public void setSUB_TYPE(String SUB_TYPE) {
        this.SUB_TYPE = SUB_TYPE == null ? null : SUB_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.DATE_UPDATED
     *
     * @return the value of ALRT_SUB_MULT_TMP.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for ALRT_SUB_MULT_TMP.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.DATE_CREATED
     *
     * @return the value of ALRT_SUB_MULT_TMP.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.DATE_CREATED
     *
     * @param DATE_CREATED the value for ALRT_SUB_MULT_TMP.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.CREATED_BY
     *
     * @return the value of ALRT_SUB_MULT_TMP.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.CREATED_BY
     *
     * @param CREATED_BY the value for ALRT_SUB_MULT_TMP.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.DATE_MODIFIED
     *
     * @return the value of ALRT_SUB_MULT_TMP.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for ALRT_SUB_MULT_TMP.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.MODIFIED_BY
     *
     * @return the value of ALRT_SUB_MULT_TMP.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for ALRT_SUB_MULT_TMP.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.DATE_AUTHORIZED
     *
     * @return the value of ALRT_SUB_MULT_TMP.DATE_AUTHORIZED
     */
    public Date getDATE_AUTHORIZED() {
        return DATE_AUTHORIZED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.DATE_AUTHORIZED
     *
     * @param DATE_AUTHORIZED the value for ALRT_SUB_MULT_TMP.DATE_AUTHORIZED
     */
    public void setDATE_AUTHORIZED(Date DATE_AUTHORIZED) {
        this.DATE_AUTHORIZED = DATE_AUTHORIZED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.AUTHORIZED_BY
     *
     * @return the value of ALRT_SUB_MULT_TMP.AUTHORIZED_BY
     */
    public String getAUTHORIZED_BY() {
        return AUTHORIZED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.AUTHORIZED_BY
     *
     * @param AUTHORIZED_BY the value for ALRT_SUB_MULT_TMP.AUTHORIZED_BY
     */
    public void setAUTHORIZED_BY(String AUTHORIZED_BY) {
        this.AUTHORIZED_BY = AUTHORIZED_BY == null ? null : AUTHORIZED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.BRIEF_NAME_ARAB
     *
     * @return the value of ALRT_SUB_MULT_TMP.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for ALRT_SUB_MULT_TMP.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.BRIEF_NAME_ENG
     *
     * @return the value of ALRT_SUB_MULT_TMP.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for ALRT_SUB_MULT_TMP.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.LONG_NAME_ARAB
     *
     * @return the value of ALRT_SUB_MULT_TMP.LONG_NAME_ARAB
     */
    public String getLONG_NAME_ARAB() {
        return LONG_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.LONG_NAME_ARAB
     *
     * @param LONG_NAME_ARAB the value for ALRT_SUB_MULT_TMP.LONG_NAME_ARAB
     */
    public void setLONG_NAME_ARAB(String LONG_NAME_ARAB) {
        this.LONG_NAME_ARAB = LONG_NAME_ARAB == null ? null : LONG_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.LONG_NAME_ENG
     *
     * @return the value of ALRT_SUB_MULT_TMP.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG() {
        return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for ALRT_SUB_MULT_TMP.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG) {
        this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.MIDDLE_NAME_ARAB
     *
     * @return the value of ALRT_SUB_MULT_TMP.MIDDLE_NAME_ARAB
     */
    public String getMIDDLE_NAME_ARAB() {
        return MIDDLE_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.MIDDLE_NAME_ARAB
     *
     * @param MIDDLE_NAME_ARAB the value for ALRT_SUB_MULT_TMP.MIDDLE_NAME_ARAB
     */
    public void setMIDDLE_NAME_ARAB(String MIDDLE_NAME_ARAB) {
        this.MIDDLE_NAME_ARAB = MIDDLE_NAME_ARAB == null ? null : MIDDLE_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_MULT_TMP.MIDDLE_NAME_ENG
     *
     * @return the value of ALRT_SUB_MULT_TMP.MIDDLE_NAME_ENG
     */
    public String getMIDDLE_NAME_ENG() {
        return MIDDLE_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_MULT_TMP.MIDDLE_NAME_ENG
     *
     * @param MIDDLE_NAME_ENG the value for ALRT_SUB_MULT_TMP.MIDDLE_NAME_ENG
     */
    public void setMIDDLE_NAME_ENG(String MIDDLE_NAME_ENG) {
        this.MIDDLE_NAME_ENG = MIDDLE_NAME_ENG == null ? null : MIDDLE_NAME_ENG.trim();
    }
}