package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class ALRT_SUBVO extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_SUB.ID
     */
    private BigDecimal ID;

    /**
     * This field corresponds to the database column ALRT_SUB.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column ALRT_SUB.USR_ID
     */
    private String USR_ID;

    /**
     * This field corresponds to the database column ALRT_SUB.SUB_TYPE
     */
    private String SUB_TYPE;

    /**
     * This field corresponds to the database column ALRT_SUB.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column ALRT_SUB.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column ALRT_SUB.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column ALRT_SUB.GL_CODE
     */
    private BigDecimal GL_CODE;

    /**
     * This field corresponds to the database column ALRT_SUB.CIF_SUB_NO
     */
    private BigDecimal CIF_SUB_NO;

    /**
     * This field corresponds to the database column ALRT_SUB.MOBILE_PHONE
     */
    private String MOBILE_PHONE;

    /**
     * This field corresponds to the database column ALRT_SUB.EMAIL_ID
     */
    private String EMAIL_ID;

    /**
     * This field corresponds to the database column ALRT_SUB.SL_NO
     */
    private BigDecimal SL_NO;

    /**
     * This field corresponds to the database column ALRT_SUB.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column ALRT_SUB.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column ALRT_SUB.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column ALRT_SUB.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column ALRT_SUB.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column ALRT_SUB.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column ALRT_SUB.DATE_DELETED
     */
    private Date DATE_DELETED;

    /**
     * This field corresponds to the database column ALRT_SUB.AUTHORIZED_BY
     */
    private String AUTHORIZED_BY;

    /**
     * This field corresponds to the database column ALRT_SUB.DATE_AUTHORIZED
     */
    private Date DATE_AUTHORIZED;

    /**
     * This field corresponds to the database column ALRT_SUB.NB_MSG
     */
    private BigDecimal NB_MSG;

    /**
     * This field corresponds to the database column ALRT_SUB.CHARGEABLE
     */
    private BigDecimal CHARGEABLE;

    /**
     * This field corresponds to the database column ALRT_SUB.NOTIFIED
     */
    private BigDecimal NOTIFIED;

    /**
     * This field corresponds to the database column ALRT_SUB.LANG
     */
    private String LANG;

    /**
     * This field corresponds to the database column ALRT_SUB.OLD_MOBILE_PHONE
     */
    private String OLD_MOBILE_PHONE;

    /**
     * This field corresponds to the database column ALRT_SUB.SUSPEND_ALL_SUBSCRIPTIONS
     */
    private BigDecimal SUSPEND_ALL_SUBSCRIPTIONS;

    /**
     * This field corresponds to the database column ALRT_SUB.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column ALRT_SUB.CHANNEL_END_USR_ID
     */
    private String CHANNEL_END_USR_ID;

    /**
     * This field corresponds to the database column ALRT_SUB.FACEBOOK_SOCIAL_ID
     */
    private String FACEBOOK_SOCIAL_ID;

    /**
     * This field corresponds to the database column ALRT_SUB.TWITTER_SOCIAL_ID
     */
    private String TWITTER_SOCIAL_ID;
    
    /**
     * This field corresponds to the database column ALRT_SUB.DEFAULT_BRIEF_NAME
     */
    private String DEFAULT_BRIEF_NAME;
    
    /**
     * This field corresponds to the database column ALRT_SUB.DEFAULT_MIDDLE_NAME
     */
    private String DEFAULT_MIDDLE_NAME;
    
    /**
     * This field corresponds to the database column ALRT_SUB.DEFAULT_LONG_NAME
     */
    private String DEFAULT_LONG_NAME;
    
    /**
     * This field corresponds to the database column ALRT_SUB.DEFAULT_ADDRESS
     */
    private String DEFAULT_ADDRESS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.ID
     *
     * @return the value of ALRT_SUB.ID
     */
    public BigDecimal getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.ID
     *
     * @param ID the value for ALRT_SUB.ID
     */
    public void setID(BigDecimal ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.CIF_NO
     *
     * @return the value of ALRT_SUB.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.CIF_NO
     *
     * @param CIF_NO the value for ALRT_SUB.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.USR_ID
     *
     * @return the value of ALRT_SUB.USR_ID
     */
    public String getUSR_ID() {
        return USR_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.USR_ID
     *
     * @param USR_ID the value for ALRT_SUB.USR_ID
     */
    public void setUSR_ID(String USR_ID) {
        this.USR_ID = USR_ID == null ? null : USR_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.SUB_TYPE
     *
     * @return the value of ALRT_SUB.SUB_TYPE
     */
    public String getSUB_TYPE() {
        return SUB_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.SUB_TYPE
     *
     * @param SUB_TYPE the value for ALRT_SUB.SUB_TYPE
     */
    public void setSUB_TYPE(String SUB_TYPE) {
        this.SUB_TYPE = SUB_TYPE == null ? null : SUB_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.COMP_CODE
     *
     * @return the value of ALRT_SUB.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.COMP_CODE
     *
     * @param COMP_CODE the value for ALRT_SUB.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.BRANCH_CODE
     *
     * @return the value of ALRT_SUB.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for ALRT_SUB.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.CURRENCY_CODE
     *
     * @return the value of ALRT_SUB.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for ALRT_SUB.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.GL_CODE
     *
     * @return the value of ALRT_SUB.GL_CODE
     */
    public BigDecimal getGL_CODE() {
        return GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.GL_CODE
     *
     * @param GL_CODE the value for ALRT_SUB.GL_CODE
     */
    public void setGL_CODE(BigDecimal GL_CODE) {
        this.GL_CODE = GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.CIF_SUB_NO
     *
     * @return the value of ALRT_SUB.CIF_SUB_NO
     */
    public BigDecimal getCIF_SUB_NO() {
        return CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.CIF_SUB_NO
     *
     * @param CIF_SUB_NO the value for ALRT_SUB.CIF_SUB_NO
     */
    public void setCIF_SUB_NO(BigDecimal CIF_SUB_NO) {
        this.CIF_SUB_NO = CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.MOBILE_PHONE
     *
     * @return the value of ALRT_SUB.MOBILE_PHONE
     */
    public String getMOBILE_PHONE() {
        return MOBILE_PHONE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.MOBILE_PHONE
     *
     * @param MOBILE_PHONE the value for ALRT_SUB.MOBILE_PHONE
     */
    public void setMOBILE_PHONE(String MOBILE_PHONE) {
        this.MOBILE_PHONE = MOBILE_PHONE == null ? null : MOBILE_PHONE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.EMAIL_ID
     *
     * @return the value of ALRT_SUB.EMAIL_ID
     */
    public String getEMAIL_ID() {
        return EMAIL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.EMAIL_ID
     *
     * @param EMAIL_ID the value for ALRT_SUB.EMAIL_ID
     */
    public void setEMAIL_ID(String EMAIL_ID) {
        this.EMAIL_ID = EMAIL_ID == null ? null : EMAIL_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.SL_NO
     *
     * @return the value of ALRT_SUB.SL_NO
     */
    public BigDecimal getSL_NO() {
        return SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.SL_NO
     *
     * @param SL_NO the value for ALRT_SUB.SL_NO
     */
    public void setSL_NO(BigDecimal SL_NO) {
        this.SL_NO = SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.STATUS
     *
     * @return the value of ALRT_SUB.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.STATUS
     *
     * @param STATUS the value for ALRT_SUB.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.CREATED_BY
     *
     * @return the value of ALRT_SUB.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.CREATED_BY
     *
     * @param CREATED_BY the value for ALRT_SUB.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.DATE_CREATED
     *
     * @return the value of ALRT_SUB.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.DATE_CREATED
     *
     * @param DATE_CREATED the value for ALRT_SUB.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.MODIFIED_BY
     *
     * @return the value of ALRT_SUB.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for ALRT_SUB.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.DATE_MODIFIED
     *
     * @return the value of ALRT_SUB.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for ALRT_SUB.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.DELETED_BY
     *
     * @return the value of ALRT_SUB.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.DELETED_BY
     *
     * @param DELETED_BY the value for ALRT_SUB.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.DATE_DELETED
     *
     * @return the value of ALRT_SUB.DATE_DELETED
     */
    public Date getDATE_DELETED() {
        return DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.DATE_DELETED
     *
     * @param DATE_DELETED the value for ALRT_SUB.DATE_DELETED
     */
    public void setDATE_DELETED(Date DATE_DELETED) {
        this.DATE_DELETED = DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.AUTHORIZED_BY
     *
     * @return the value of ALRT_SUB.AUTHORIZED_BY
     */
    public String getAUTHORIZED_BY() {
        return AUTHORIZED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.AUTHORIZED_BY
     *
     * @param AUTHORIZED_BY the value for ALRT_SUB.AUTHORIZED_BY
     */
    public void setAUTHORIZED_BY(String AUTHORIZED_BY) {
        this.AUTHORIZED_BY = AUTHORIZED_BY == null ? null : AUTHORIZED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.DATE_AUTHORIZED
     *
     * @return the value of ALRT_SUB.DATE_AUTHORIZED
     */
    public Date getDATE_AUTHORIZED() {
        return DATE_AUTHORIZED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.DATE_AUTHORIZED
     *
     * @param DATE_AUTHORIZED the value for ALRT_SUB.DATE_AUTHORIZED
     */
    public void setDATE_AUTHORIZED(Date DATE_AUTHORIZED) {
        this.DATE_AUTHORIZED = DATE_AUTHORIZED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.NB_MSG
     *
     * @return the value of ALRT_SUB.NB_MSG
     */
    public BigDecimal getNB_MSG() {
        return NB_MSG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.NB_MSG
     *
     * @param NB_MSG the value for ALRT_SUB.NB_MSG
     */
    public void setNB_MSG(BigDecimal NB_MSG) {
        this.NB_MSG = NB_MSG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.CHARGEABLE
     *
     * @return the value of ALRT_SUB.CHARGEABLE
     */
    public BigDecimal getCHARGEABLE() {
        return CHARGEABLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.CHARGEABLE
     *
     * @param CHARGEABLE the value for ALRT_SUB.CHARGEABLE
     */
    public void setCHARGEABLE(BigDecimal CHARGEABLE) {
        this.CHARGEABLE = CHARGEABLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.NOTIFIED
     *
     * @return the value of ALRT_SUB.NOTIFIED
     */
    public BigDecimal getNOTIFIED() {
        return NOTIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.NOTIFIED
     *
     * @param NOTIFIED the value for ALRT_SUB.NOTIFIED
     */
    public void setNOTIFIED(BigDecimal NOTIFIED) {
        this.NOTIFIED = NOTIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.LANG
     *
     * @return the value of ALRT_SUB.LANG
     */
    public String getLANG() {
        return LANG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.LANG
     *
     * @param LANG the value for ALRT_SUB.LANG
     */
    public void setLANG(String LANG) {
        this.LANG = LANG == null ? null : LANG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.OLD_MOBILE_PHONE
     *
     * @return the value of ALRT_SUB.OLD_MOBILE_PHONE
     */
    public String getOLD_MOBILE_PHONE() {
        return OLD_MOBILE_PHONE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.OLD_MOBILE_PHONE
     *
     * @param OLD_MOBILE_PHONE the value for ALRT_SUB.OLD_MOBILE_PHONE
     */
    public void setOLD_MOBILE_PHONE(String OLD_MOBILE_PHONE) {
        this.OLD_MOBILE_PHONE = OLD_MOBILE_PHONE == null ? null : OLD_MOBILE_PHONE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.SUSPEND_ALL_SUBSCRIPTIONS
     *
     * @return the value of ALRT_SUB.SUSPEND_ALL_SUBSCRIPTIONS
     */
    public BigDecimal getSUSPEND_ALL_SUBSCRIPTIONS() {
        return SUSPEND_ALL_SUBSCRIPTIONS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.SUSPEND_ALL_SUBSCRIPTIONS
     *
     * @param SUSPEND_ALL_SUBSCRIPTIONS the value for ALRT_SUB.SUSPEND_ALL_SUBSCRIPTIONS
     */
    public void setSUSPEND_ALL_SUBSCRIPTIONS(BigDecimal SUSPEND_ALL_SUBSCRIPTIONS) {
        this.SUSPEND_ALL_SUBSCRIPTIONS = SUSPEND_ALL_SUBSCRIPTIONS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.DATE_UPDATED
     *
     * @return the value of ALRT_SUB.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for ALRT_SUB.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.CHANNEL_END_USR_ID
     *
     * @return the value of ALRT_SUB.CHANNEL_END_USR_ID
     */
    public String getCHANNEL_END_USR_ID() {
        return CHANNEL_END_USR_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.CHANNEL_END_USR_ID
     *
     * @param CHANNEL_END_USR_ID the value for ALRT_SUB.CHANNEL_END_USR_ID
     */
    public void setCHANNEL_END_USR_ID(String CHANNEL_END_USR_ID) {
        this.CHANNEL_END_USR_ID = CHANNEL_END_USR_ID == null ? null : CHANNEL_END_USR_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.FACEBOOK_SOCIAL_ID
     *
     * @return the value of ALRT_SUB.FACEBOOK_SOCIAL_ID
     */
    public String getFACEBOOK_SOCIAL_ID() {
        return FACEBOOK_SOCIAL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.FACEBOOK_SOCIAL_ID
     *
     * @param FACEBOOK_SOCIAL_ID the value for ALRT_SUB.FACEBOOK_SOCIAL_ID
     */
    public void setFACEBOOK_SOCIAL_ID(String FACEBOOK_SOCIAL_ID) {
        this.FACEBOOK_SOCIAL_ID = FACEBOOK_SOCIAL_ID == null ? null : FACEBOOK_SOCIAL_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.TWITTER_SOCIAL_ID
     *
     * @return the value of ALRT_SUB.TWITTER_SOCIAL_ID
     */
    public String getTWITTER_SOCIAL_ID() {
        return TWITTER_SOCIAL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.TWITTER_SOCIAL_ID
     *
     * @param TWITTER_SOCIAL_ID the value for ALRT_SUB.TWITTER_SOCIAL_ID
     */
    public void setTWITTER_SOCIAL_ID(String TWITTER_SOCIAL_ID) {
        this.TWITTER_SOCIAL_ID = TWITTER_SOCIAL_ID == null ? null : TWITTER_SOCIAL_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.DEFAULT_BRIEF_NAME
     *
     * @return the value of ALRT_SUB.DEFAULT_BRIEF_NAME
     */
	public String getDEFAULT_BRIEF_NAME() {
		return DEFAULT_BRIEF_NAME;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.DEFAULT_BRIEF_NAME
     *
     * @param DEFAULT_BRIEF_NAME the value for ALRT_SUB.DEFAULT_BRIEF_NAME
     */
	public void setDEFAULT_BRIEF_NAME(String DEFAULT_BRIEF_NAME) {
		this.DEFAULT_BRIEF_NAME = DEFAULT_BRIEF_NAME == null ? null : DEFAULT_BRIEF_NAME.trim();
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.DEFAULT_MIDDLE_NAME
     *
     * @return the value of ALRT_SUB.DEFAULT_MIDDLE_NAME
     */
	public String getDEFAULT_MIDDLE_NAME() {
		return DEFAULT_MIDDLE_NAME;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.DEFAULT_MIDDLE_NAME
     *
     * @param DEFAULT_MIDDLE_NAME the value for ALRT_SUB.DEFAULT_MIDDLE_NAME
     */
	public void setDEFAULT_MIDDLE_NAME(String DEFAULT_MIDDLE_NAME) {
		this.DEFAULT_MIDDLE_NAME = DEFAULT_MIDDLE_NAME == null ? null : DEFAULT_MIDDLE_NAME.trim();
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.DEFAULT_LONG_NAME
     *
     * @return the value of ALRT_SUB.DEFAULT_LONG_NAME
     */
	public String getDEFAULT_LONG_NAME() {
		return DEFAULT_LONG_NAME;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.DEFAULT_LONG_NAME
     *
     * @param DEFAULT_LONG_NAME the value for ALRT_SUB.DEFAULT_LONG_NAME
     */
	public void setDEFAULT_LONG_NAME(String DEFAULT_LONG_NAME) {
		this.DEFAULT_LONG_NAME = DEFAULT_LONG_NAME == null ? null : DEFAULT_LONG_NAME.trim();
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB.DEFAULT_ADDRESS
     *
     * @return the value of ALRT_SUB.DEFAULT_ADDRESS
     */
	public String getDEFAULT_ADDRESS() {
		return DEFAULT_ADDRESS;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB.DEFAULT_ADDRESS
     *
     * @param DEFAULT_ADDRESS the value for ALRT_SUB.DEFAULT_ADDRESS
     */
	public void setDEFAULT_ADDRESS(String DEFAULT_ADDRESS) {
		this.DEFAULT_ADDRESS = DEFAULT_ADDRESS == null ? null : DEFAULT_ADDRESS.trim();
	}
}