package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class ALRT_FIXED_EVT_PARAM_CONDVO extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_FIXED_EVT_PARAM_COND.EVT_ID
     */
    private BigDecimal EVT_ID;

    /**
     * This field corresponds to the database column ALRT_FIXED_EVT_PARAM_COND.ID
     */
    private BigDecimal ID;

    /**
     * This field corresponds to the database column ALRT_FIXED_EVT_PARAM_COND.OLD_NEW_VAL_LIST
     */
    private String OLD_NEW_VAL_LIST;

    /**
     * This field corresponds to the database column ALRT_FIXED_EVT_PARAM_COND.PARAM_COLUMN_NAME
     */
    private String PARAM_COLUMN_NAME;

    /**
     * This field corresponds to the database column ALRT_FIXED_EVT_PARAM_COND.OPERATOR_TYPE
     */
    private String OPERATOR_TYPE;

    /**
     * This field corresponds to the database column ALRT_FIXED_EVT_PARAM_COND.PARAM_VALUE
     */
    private String PARAM_VALUE;

    /**
     * This field corresponds to the database column ALRT_FIXED_EVT_PARAM_COND.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column ALRT_FIXED_EVT_PARAM_COND.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column ALRT_FIXED_EVT_PARAM_COND.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column ALRT_FIXED_EVT_PARAM_COND.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_FIXED_EVT_PARAM_COND.EVT_ID
     *
     * @return the value of ALRT_FIXED_EVT_PARAM_COND.EVT_ID
     */
    public BigDecimal getEVT_ID() {
        return EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_FIXED_EVT_PARAM_COND.EVT_ID
     *
     * @param EVT_ID the value for ALRT_FIXED_EVT_PARAM_COND.EVT_ID
     */
    public void setEVT_ID(BigDecimal EVT_ID) {
        this.EVT_ID = EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_FIXED_EVT_PARAM_COND.ID
     *
     * @return the value of ALRT_FIXED_EVT_PARAM_COND.ID
     */
    public BigDecimal getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_FIXED_EVT_PARAM_COND.ID
     *
     * @param ID the value for ALRT_FIXED_EVT_PARAM_COND.ID
     */
    public void setID(BigDecimal ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_FIXED_EVT_PARAM_COND.OLD_NEW_VAL_LIST
     *
     * @return the value of ALRT_FIXED_EVT_PARAM_COND.OLD_NEW_VAL_LIST
     */
    public String getOLD_NEW_VAL_LIST() {
        return OLD_NEW_VAL_LIST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_FIXED_EVT_PARAM_COND.OLD_NEW_VAL_LIST
     *
     * @param OLD_NEW_VAL_LIST the value for ALRT_FIXED_EVT_PARAM_COND.OLD_NEW_VAL_LIST
     */
    public void setOLD_NEW_VAL_LIST(String OLD_NEW_VAL_LIST) {
        this.OLD_NEW_VAL_LIST = OLD_NEW_VAL_LIST == null ? null : OLD_NEW_VAL_LIST.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_FIXED_EVT_PARAM_COND.PARAM_COLUMN_NAME
     *
     * @return the value of ALRT_FIXED_EVT_PARAM_COND.PARAM_COLUMN_NAME
     */
    public String getPARAM_COLUMN_NAME() {
        return PARAM_COLUMN_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_FIXED_EVT_PARAM_COND.PARAM_COLUMN_NAME
     *
     * @param PARAM_COLUMN_NAME the value for ALRT_FIXED_EVT_PARAM_COND.PARAM_COLUMN_NAME
     */
    public void setPARAM_COLUMN_NAME(String PARAM_COLUMN_NAME) {
        this.PARAM_COLUMN_NAME = PARAM_COLUMN_NAME == null ? null : PARAM_COLUMN_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_FIXED_EVT_PARAM_COND.OPERATOR_TYPE
     *
     * @return the value of ALRT_FIXED_EVT_PARAM_COND.OPERATOR_TYPE
     */
    public String getOPERATOR_TYPE() {
        return OPERATOR_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_FIXED_EVT_PARAM_COND.OPERATOR_TYPE
     *
     * @param OPERATOR_TYPE the value for ALRT_FIXED_EVT_PARAM_COND.OPERATOR_TYPE
     */
    public void setOPERATOR_TYPE(String OPERATOR_TYPE) {
        this.OPERATOR_TYPE = OPERATOR_TYPE == null ? null : OPERATOR_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_FIXED_EVT_PARAM_COND.PARAM_VALUE
     *
     * @return the value of ALRT_FIXED_EVT_PARAM_COND.PARAM_VALUE
     */
    public String getPARAM_VALUE() {
        return PARAM_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_FIXED_EVT_PARAM_COND.PARAM_VALUE
     *
     * @param PARAM_VALUE the value for ALRT_FIXED_EVT_PARAM_COND.PARAM_VALUE
     */
    public void setPARAM_VALUE(String PARAM_VALUE) {
        this.PARAM_VALUE = PARAM_VALUE == null ? null : PARAM_VALUE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_FIXED_EVT_PARAM_COND.CREATED_BY
     *
     * @return the value of ALRT_FIXED_EVT_PARAM_COND.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_FIXED_EVT_PARAM_COND.CREATED_BY
     *
     * @param CREATED_BY the value for ALRT_FIXED_EVT_PARAM_COND.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_FIXED_EVT_PARAM_COND.CREATED_DATE
     *
     * @return the value of ALRT_FIXED_EVT_PARAM_COND.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_FIXED_EVT_PARAM_COND.CREATED_DATE
     *
     * @param CREATED_DATE the value for ALRT_FIXED_EVT_PARAM_COND.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_FIXED_EVT_PARAM_COND.MODIFIED_BY
     *
     * @return the value of ALRT_FIXED_EVT_PARAM_COND.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_FIXED_EVT_PARAM_COND.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for ALRT_FIXED_EVT_PARAM_COND.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_FIXED_EVT_PARAM_COND.MODIFIED_DATE
     *
     * @return the value of ALRT_FIXED_EVT_PARAM_COND.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_FIXED_EVT_PARAM_COND.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for ALRT_FIXED_EVT_PARAM_COND.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }
}