package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ALRT_GRP_PKGVOKey extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_GRP_PKG.GRP_ID
     */
    private BigDecimal GRP_ID;

    /**
     * This field corresponds to the database column ALRT_GRP_PKG.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column ALRT_GRP_PKG.PKG_ID
     */
    private BigDecimal PKG_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_GRP_PKG.GRP_ID
     *
     * @return the value of ALRT_GRP_PKG.GRP_ID
     */
    public BigDecimal getGRP_ID() {
        return GRP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_GRP_PKG.GRP_ID
     *
     * @param GRP_ID the value for ALRT_GRP_PKG.GRP_ID
     */
    public void setGRP_ID(BigDecimal GRP_ID) {
        this.GRP_ID = GRP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_GRP_PKG.LINE_NO
     *
     * @return the value of ALRT_GRP_PKG.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_GRP_PKG.LINE_NO
     *
     * @param LINE_NO the value for ALRT_GRP_PKG.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_GRP_PKG.PKG_ID
     *
     * @return the value of ALRT_GRP_PKG.PKG_ID
     */
    public BigDecimal getPKG_ID() {
        return PKG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_GRP_PKG.PKG_ID
     *
     * @param PKG_ID the value for ALRT_GRP_PKG.PKG_ID
     */
    public void setPKG_ID(BigDecimal PKG_ID) {
        this.PKG_ID = PKG_ID;
    }
}