package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ALRT_SUB_EVTVOKey extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_SUB_EVT.ID
     */
    private BigDecimal ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT.ID
     *
     * @return the value of ALRT_SUB_EVT.ID
     */
    public BigDecimal getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT.ID
     *
     * @param ID the value for ALRT_SUB_EVT.ID
     */
    public void setID(BigDecimal ID) {
        this.ID = ID;
    }
}