package com.path.dbmaps.vo;

import java.math.BigDecimal;

import com.path.lib.vo.BaseVO;

public class ALRT_SUBVOKey extends BaseVO
{
    /**
     * This field corresponds to the database column ALRT_SUB.ID
     */
    private BigDecimal ID;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column ALRT_SUB.ID
     *
     * @return the value of ALRT_SUB.ID
     */
    public BigDecimal getID()
    {
	return ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column ALRT_SUB.ID
     *
     * @param ID the value for ALRT_SUB.ID
     */
    public void setID(BigDecimal ID)
    {
	this.ID = ID;
    }

}