package com.path.dbmaps.vo;

public class ALRT_FIXED_PARAMVO extends ALRT_FIXED_PARAMVOKey {
    /**
     * This field corresponds to the database column ALRT_FIXED_PARAM.FIXED_LABEL
     */
    private String FIXED_LABEL;

    /**
     * This field corresponds to the database column ALRT_FIXED_PARAM.PARAM_TYPE
     */
    private String PARAM_TYPE;

    /**
     * This field corresponds to the database column ALRT_FIXED_PARAM.FIXED_FLAG
     */
    private String FIXED_FLAG;

    /**
     * This field corresponds to the database column ALRT_FIXED_PARAM.FIXED_OPERATOR
     */
    private String FIXED_OPERATOR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_FIXED_PARAM.FIXED_LABEL
     *
     * @return the value of ALRT_FIXED_PARAM.FIXED_LABEL
     */
    public String getFIXED_LABEL() {
        return FIXED_LABEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_FIXED_PARAM.FIXED_LABEL
     *
     * @param FIXED_LABEL the value for ALRT_FIXED_PARAM.FIXED_LABEL
     */
    public void setFIXED_LABEL(String FIXED_LABEL) {
        this.FIXED_LABEL = FIXED_LABEL == null ? null : FIXED_LABEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_FIXED_PARAM.PARAM_TYPE
     *
     * @return the value of ALRT_FIXED_PARAM.PARAM_TYPE
     */
    public String getPARAM_TYPE() {
        return PARAM_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_FIXED_PARAM.PARAM_TYPE
     *
     * @param PARAM_TYPE the value for ALRT_FIXED_PARAM.PARAM_TYPE
     */
    public void setPARAM_TYPE(String PARAM_TYPE) {
        this.PARAM_TYPE = PARAM_TYPE == null ? null : PARAM_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_FIXED_PARAM.FIXED_FLAG
     *
     * @return the value of ALRT_FIXED_PARAM.FIXED_FLAG
     */
    public String getFIXED_FLAG() {
        return FIXED_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_FIXED_PARAM.FIXED_FLAG
     *
     * @param FIXED_FLAG the value for ALRT_FIXED_PARAM.FIXED_FLAG
     */
    public void setFIXED_FLAG(String FIXED_FLAG) {
        this.FIXED_FLAG = FIXED_FLAG == null ? null : FIXED_FLAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_FIXED_PARAM.FIXED_OPERATOR
     *
     * @return the value of ALRT_FIXED_PARAM.FIXED_OPERATOR
     */
    public String getFIXED_OPERATOR() {
        return FIXED_OPERATOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_FIXED_PARAM.FIXED_OPERATOR
     *
     * @param FIXED_OPERATOR the value for ALRT_FIXED_PARAM.FIXED_OPERATOR
     */
    public void setFIXED_OPERATOR(String FIXED_OPERATOR) {
        this.FIXED_OPERATOR = FIXED_OPERATOR == null ? null : FIXED_OPERATOR.trim();
    }
}