package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ALRT_FIXED_PARAMVOKey extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_FIXED_PARAM.FIXED_CODE
     */
    private BigDecimal FIXED_CODE;

    /**
     * This field corresponds to the database column ALRT_FIXED_PARAM.ID
     */
    private BigDecimal ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_FIXED_PARAM.FIXED_CODE
     *
     * @return the value of ALRT_FIXED_PARAM.FIXED_CODE
     */
    public BigDecimal getFIXED_CODE() {
        return FIXED_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_FIXED_PARAM.FIXED_CODE
     *
     * @param FIXED_CODE the value for ALRT_FIXED_PARAM.FIXED_CODE
     */
    public void setFIXED_CODE(BigDecimal FIXED_CODE) {
        this.FIXED_CODE = FIXED_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_FIXED_PARAM.ID
     *
     * @return the value of ALRT_FIXED_PARAM.ID
     */
    public BigDecimal getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_FIXED_PARAM.ID
     *
     * @param ID the value for ALRT_FIXED_PARAM.ID
     */
    public void setID(BigDecimal ID) {
        this.ID = ID;
    }
}