package com.path.dbmaps.vo;

import java.util.Date;

public class ALRT_EVT_PARAMSETVO extends ALRT_EVT_PARAMSETVOKey {
    /**
     * This field corresponds to the database column ALRT_EVT_PARAMSET.FIXED_OPERATOR
     */
    private String FIXED_OPERATOR;

    /**
     * This field corresponds to the database column ALRT_EVT_PARAMSET.FROM_VALUE
     */
    private String FROM_VALUE;

    /**
     * This field corresponds to the database column ALRT_EVT_PARAMSET.TO_VALUE
     */
    private String TO_VALUE;

    /**
     * This field corresponds to the database column ALRT_EVT_PARAMSET.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_PARAMSET.FIXED_OPERATOR
     *
     * @return the value of ALRT_EVT_PARAMSET.FIXED_OPERATOR
     */
    public String getFIXED_OPERATOR() {
        return FIXED_OPERATOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_PARAMSET.FIXED_OPERATOR
     *
     * @param FIXED_OPERATOR the value for ALRT_EVT_PARAMSET.FIXED_OPERATOR
     */
    public void setFIXED_OPERATOR(String FIXED_OPERATOR) {
        this.FIXED_OPERATOR = FIXED_OPERATOR == null ? null : FIXED_OPERATOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_PARAMSET.FROM_VALUE
     *
     * @return the value of ALRT_EVT_PARAMSET.FROM_VALUE
     */
    public String getFROM_VALUE() {
        return FROM_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_PARAMSET.FROM_VALUE
     *
     * @param FROM_VALUE the value for ALRT_EVT_PARAMSET.FROM_VALUE
     */
    public void setFROM_VALUE(String FROM_VALUE) {
        this.FROM_VALUE = FROM_VALUE == null ? null : FROM_VALUE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_PARAMSET.TO_VALUE
     *
     * @return the value of ALRT_EVT_PARAMSET.TO_VALUE
     */
    public String getTO_VALUE() {
        return TO_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_PARAMSET.TO_VALUE
     *
     * @param TO_VALUE the value for ALRT_EVT_PARAMSET.TO_VALUE
     */
    public void setTO_VALUE(String TO_VALUE) {
        this.TO_VALUE = TO_VALUE == null ? null : TO_VALUE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_PARAMSET.DATE_UPDATED
     *
     * @return the value of ALRT_EVT_PARAMSET.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_PARAMSET.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for ALRT_EVT_PARAMSET.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}