package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class ALRT_REPORT_QUERYVO extends ALRT_REPORT_QUERYVOKey {
    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY.QUERY_ID
     */
    private BigDecimal QUERY_ID;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY.QYERY_TYPE
     */
    private String QYERY_TYPE;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY.SERVER_CREATED_DATE
     */
    private Date SERVER_CREATED_DATE;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY.SERVER_MODIFIED_DATE
     */
    private Date SERVER_MODIFIED_DATE;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY.APPROVED_DATE
     */
    private Date APPROVED_DATE;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY.SERVER_APPROVED_DATE
     */
    private Date SERVER_APPROVED_DATE;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY.DELETED_DATE
     */
    private Date DELETED_DATE;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY.SERVER_DELETED_DATE
     */
    private Date SERVER_DELETED_DATE;

    /**
     * This field corresponds to the database column ALRT_REPORT_QUERY.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY.QUERY_ID
     *
     * @return the value of ALRT_REPORT_QUERY.QUERY_ID
     */
    public BigDecimal getQUERY_ID() {
        return QUERY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY.QUERY_ID
     *
     * @param QUERY_ID the value for ALRT_REPORT_QUERY.QUERY_ID
     */
    public void setQUERY_ID(BigDecimal QUERY_ID) {
        this.QUERY_ID = QUERY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY.QYERY_TYPE
     *
     * @return the value of ALRT_REPORT_QUERY.QYERY_TYPE
     */
    public String getQYERY_TYPE() {
        return QYERY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY.QYERY_TYPE
     *
     * @param QYERY_TYPE the value for ALRT_REPORT_QUERY.QYERY_TYPE
     */
    public void setQYERY_TYPE(String QYERY_TYPE) {
        this.QYERY_TYPE = QYERY_TYPE == null ? null : QYERY_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY.STATUS
     *
     * @return the value of ALRT_REPORT_QUERY.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY.STATUS
     *
     * @param STATUS the value for ALRT_REPORT_QUERY.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY.CREATED_BY
     *
     * @return the value of ALRT_REPORT_QUERY.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY.CREATED_BY
     *
     * @param CREATED_BY the value for ALRT_REPORT_QUERY.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY.CREATED_DATE
     *
     * @return the value of ALRT_REPORT_QUERY.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY.CREATED_DATE
     *
     * @param CREATED_DATE the value for ALRT_REPORT_QUERY.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY.SERVER_CREATED_DATE
     *
     * @return the value of ALRT_REPORT_QUERY.SERVER_CREATED_DATE
     */
    public Date getSERVER_CREATED_DATE() {
        return SERVER_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY.SERVER_CREATED_DATE
     *
     * @param SERVER_CREATED_DATE the value for ALRT_REPORT_QUERY.SERVER_CREATED_DATE
     */
    public void setSERVER_CREATED_DATE(Date SERVER_CREATED_DATE) {
        this.SERVER_CREATED_DATE = SERVER_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY.MODIFIED_BY
     *
     * @return the value of ALRT_REPORT_QUERY.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for ALRT_REPORT_QUERY.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY.MODIFIED_DATE
     *
     * @return the value of ALRT_REPORT_QUERY.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for ALRT_REPORT_QUERY.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY.SERVER_MODIFIED_DATE
     *
     * @return the value of ALRT_REPORT_QUERY.SERVER_MODIFIED_DATE
     */
    public Date getSERVER_MODIFIED_DATE() {
        return SERVER_MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY.SERVER_MODIFIED_DATE
     *
     * @param SERVER_MODIFIED_DATE the value for ALRT_REPORT_QUERY.SERVER_MODIFIED_DATE
     */
    public void setSERVER_MODIFIED_DATE(Date SERVER_MODIFIED_DATE) {
        this.SERVER_MODIFIED_DATE = SERVER_MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY.APPROVED_BY
     *
     * @return the value of ALRT_REPORT_QUERY.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY.APPROVED_BY
     *
     * @param APPROVED_BY the value for ALRT_REPORT_QUERY.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY.APPROVED_DATE
     *
     * @return the value of ALRT_REPORT_QUERY.APPROVED_DATE
     */
    public Date getAPPROVED_DATE() {
        return APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY.APPROVED_DATE
     *
     * @param APPROVED_DATE the value for ALRT_REPORT_QUERY.APPROVED_DATE
     */
    public void setAPPROVED_DATE(Date APPROVED_DATE) {
        this.APPROVED_DATE = APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY.SERVER_APPROVED_DATE
     *
     * @return the value of ALRT_REPORT_QUERY.SERVER_APPROVED_DATE
     */
    public Date getSERVER_APPROVED_DATE() {
        return SERVER_APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY.SERVER_APPROVED_DATE
     *
     * @param SERVER_APPROVED_DATE the value for ALRT_REPORT_QUERY.SERVER_APPROVED_DATE
     */
    public void setSERVER_APPROVED_DATE(Date SERVER_APPROVED_DATE) {
        this.SERVER_APPROVED_DATE = SERVER_APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY.DELETED_BY
     *
     * @return the value of ALRT_REPORT_QUERY.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY.DELETED_BY
     *
     * @param DELETED_BY the value for ALRT_REPORT_QUERY.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY.DELETED_DATE
     *
     * @return the value of ALRT_REPORT_QUERY.DELETED_DATE
     */
    public Date getDELETED_DATE() {
        return DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY.DELETED_DATE
     *
     * @param DELETED_DATE the value for ALRT_REPORT_QUERY.DELETED_DATE
     */
    public void setDELETED_DATE(Date DELETED_DATE) {
        this.DELETED_DATE = DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY.SERVER_DELETED_DATE
     *
     * @return the value of ALRT_REPORT_QUERY.SERVER_DELETED_DATE
     */
    public Date getSERVER_DELETED_DATE() {
        return SERVER_DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY.SERVER_DELETED_DATE
     *
     * @param SERVER_DELETED_DATE the value for ALRT_REPORT_QUERY.SERVER_DELETED_DATE
     */
    public void setSERVER_DELETED_DATE(Date SERVER_DELETED_DATE) {
        this.SERVER_DELETED_DATE = SERVER_DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_REPORT_QUERY.DATE_UPDATED
     *
     * @return the value of ALRT_REPORT_QUERY.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_REPORT_QUERY.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for ALRT_REPORT_QUERY.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}