package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ALRT_SUB_GRPVOKey extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_SUB_GRP.GRP_ID
     */
    private BigDecimal GRP_ID;

    /**
     * This field corresponds to the database column ALRT_SUB_GRP.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column ALRT_SUB_GRP.SUB_ID
     */
    private BigDecimal SUB_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_GRP.GRP_ID
     *
     * @return the value of ALRT_SUB_GRP.GRP_ID
     */
    public BigDecimal getGRP_ID() {
        return GRP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_GRP.GRP_ID
     *
     * @param GRP_ID the value for ALRT_SUB_GRP.GRP_ID
     */
    public void setGRP_ID(BigDecimal GRP_ID) {
        this.GRP_ID = GRP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_GRP.LINE_NO
     *
     * @return the value of ALRT_SUB_GRP.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_GRP.LINE_NO
     *
     * @param LINE_NO the value for ALRT_SUB_GRP.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_GRP.SUB_ID
     *
     * @return the value of ALRT_SUB_GRP.SUB_ID
     */
    public BigDecimal getSUB_ID() {
        return SUB_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_GRP.SUB_ID
     *
     * @param SUB_ID the value for ALRT_SUB_GRP.SUB_ID
     */
    public void setSUB_ID(BigDecimal SUB_ID) {
        this.SUB_ID = SUB_ID;
    }
}