package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class ALRT_SUB_GRP_TMPVO extends ALRT_SUB_GRP_TMPVOKey {
    /**
     * This field corresponds to the database column ALRT_SUB_GRP_TMP.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column ALRT_SUB_GRP_TMP.GRP_ID
     */
    private BigDecimal GRP_ID;

    /**
     * This field corresponds to the database column ALRT_SUB_GRP_TMP.SUB_TYPE
     */
    private String SUB_TYPE;

    /**
     * This field corresponds to the database column ALRT_SUB_GRP_TMP.DESCRIPTION
     */
    private String DESCRIPTION;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_GRP_TMP.LINE_NO
     *
     * @return the value of ALRT_SUB_GRP_TMP.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_GRP_TMP.LINE_NO
     *
     * @param LINE_NO the value for ALRT_SUB_GRP_TMP.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_GRP_TMP.GRP_ID
     *
     * @return the value of ALRT_SUB_GRP_TMP.GRP_ID
     */
    public BigDecimal getGRP_ID() {
        return GRP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_GRP_TMP.GRP_ID
     *
     * @param GRP_ID the value for ALRT_SUB_GRP_TMP.GRP_ID
     */
    public void setGRP_ID(BigDecimal GRP_ID) {
        this.GRP_ID = GRP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_GRP_TMP.SUB_TYPE
     *
     * @return the value of ALRT_SUB_GRP_TMP.SUB_TYPE
     */
    public String getSUB_TYPE() {
        return SUB_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_GRP_TMP.SUB_TYPE
     *
     * @param SUB_TYPE the value for ALRT_SUB_GRP_TMP.SUB_TYPE
     */
    public void setSUB_TYPE(String SUB_TYPE) {
        this.SUB_TYPE = SUB_TYPE == null ? null : SUB_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_GRP_TMP.DESCRIPTION
     *
     * @return the value of ALRT_SUB_GRP_TMP.DESCRIPTION
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_GRP_TMP.DESCRIPTION
     *
     * @param DESCRIPTION the value for ALRT_SUB_GRP_TMP.DESCRIPTION
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }
}