package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class ALRT_EVT_REPORT_ATTACHVO extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_EVT_REPORT_ATTACH.COMMUNICATION_TYPE
     */
    private String COMMUNICATION_TYPE;

    /**
     * This field corresponds to the database column ALRT_EVT_REPORT_ATTACH.EVT_ID
     */
    private BigDecimal EVT_ID;

    /**
     * This field corresponds to the database column ALRT_EVT_REPORT_ATTACH.REPORT_ID
     */
    private BigDecimal REPORT_ID;

    /**
     * This field corresponds to the database column ALRT_EVT_REPORT_ATTACH.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column ALRT_EVT_REPORT_ATTACH.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column ALRT_EVT_REPORT_ATTACH.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column ALRT_EVT_REPORT_ATTACH.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_REPORT_ATTACH.COMMUNICATION_TYPE
     *
     * @return the value of ALRT_EVT_REPORT_ATTACH.COMMUNICATION_TYPE
     */
    public String getCOMMUNICATION_TYPE() {
        return COMMUNICATION_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_REPORT_ATTACH.COMMUNICATION_TYPE
     *
     * @param COMMUNICATION_TYPE the value for ALRT_EVT_REPORT_ATTACH.COMMUNICATION_TYPE
     */
    public void setCOMMUNICATION_TYPE(String COMMUNICATION_TYPE) {
        this.COMMUNICATION_TYPE = COMMUNICATION_TYPE == null ? null : COMMUNICATION_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_REPORT_ATTACH.EVT_ID
     *
     * @return the value of ALRT_EVT_REPORT_ATTACH.EVT_ID
     */
    public BigDecimal getEVT_ID() {
        return EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_REPORT_ATTACH.EVT_ID
     *
     * @param EVT_ID the value for ALRT_EVT_REPORT_ATTACH.EVT_ID
     */
    public void setEVT_ID(BigDecimal EVT_ID) {
        this.EVT_ID = EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_REPORT_ATTACH.REPORT_ID
     *
     * @return the value of ALRT_EVT_REPORT_ATTACH.REPORT_ID
     */
    public BigDecimal getREPORT_ID() {
        return REPORT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_REPORT_ATTACH.REPORT_ID
     *
     * @param REPORT_ID the value for ALRT_EVT_REPORT_ATTACH.REPORT_ID
     */
    public void setREPORT_ID(BigDecimal REPORT_ID) {
        this.REPORT_ID = REPORT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_REPORT_ATTACH.CREATED_BY
     *
     * @return the value of ALRT_EVT_REPORT_ATTACH.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_REPORT_ATTACH.CREATED_BY
     *
     * @param CREATED_BY the value for ALRT_EVT_REPORT_ATTACH.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_REPORT_ATTACH.CREATED_DATE
     *
     * @return the value of ALRT_EVT_REPORT_ATTACH.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_REPORT_ATTACH.CREATED_DATE
     *
     * @param CREATED_DATE the value for ALRT_EVT_REPORT_ATTACH.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_REPORT_ATTACH.MODIFIED_BY
     *
     * @return the value of ALRT_EVT_REPORT_ATTACH.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_REPORT_ATTACH.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for ALRT_EVT_REPORT_ATTACH.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_REPORT_ATTACH.MODIFIED_DATE
     *
     * @return the value of ALRT_EVT_REPORT_ATTACH.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_REPORT_ATTACH.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for ALRT_EVT_REPORT_ATTACH.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }
}