package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ALRT_TAGSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_TAGS.TAG_ID
     */
    private BigDecimal TAG_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_TAGS.TAG_ID
     *
     * @return the value of ALRT_TAGS.TAG_ID
     */
    public BigDecimal getTAG_ID() {
        return TAG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_TAGS.TAG_ID
     *
     * @param TAG_ID the value for ALRT_TAGS.TAG_ID
     */
    public void setTAG_ID(BigDecimal TAG_ID) {
        this.TAG_ID = TAG_ID;
    }
}