package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class ALRT_EVT_BATCH_ARG_MAPVO extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_EVT_BATCH_ARG_MAP.ARG_NAME
     */
    private String ARG_NAME;

    /**
     * This field corresponds to the database column ALRT_EVT_BATCH_ARG_MAP.EVT_ID
     */
    private BigDecimal EVT_ID;

    /**
     * This field corresponds to the database column ALRT_EVT_BATCH_ARG_MAP.MAPPING_TAG_NAME
     */
    private String MAPPING_TAG_NAME;

    /**
     * This field corresponds to the database column ALRT_EVT_BATCH_ARG_MAP.MAPPING_VALUE
     */
    private String MAPPING_VALUE;

    /**
     * This field corresponds to the database column ALRT_EVT_BATCH_ARG_MAP.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column ALRT_EVT_BATCH_ARG_MAP.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column ALRT_EVT_BATCH_ARG_MAP.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column ALRT_EVT_BATCH_ARG_MAP.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_BATCH_ARG_MAP.ARG_NAME
     *
     * @return the value of ALRT_EVT_BATCH_ARG_MAP.ARG_NAME
     */
    public String getARG_NAME() {
        return ARG_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_BATCH_ARG_MAP.ARG_NAME
     *
     * @param ARG_NAME the value for ALRT_EVT_BATCH_ARG_MAP.ARG_NAME
     */
    public void setARG_NAME(String ARG_NAME) {
        this.ARG_NAME = ARG_NAME == null ? null : ARG_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_BATCH_ARG_MAP.EVT_ID
     *
     * @return the value of ALRT_EVT_BATCH_ARG_MAP.EVT_ID
     */
    public BigDecimal getEVT_ID() {
        return EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_BATCH_ARG_MAP.EVT_ID
     *
     * @param EVT_ID the value for ALRT_EVT_BATCH_ARG_MAP.EVT_ID
     */
    public void setEVT_ID(BigDecimal EVT_ID) {
        this.EVT_ID = EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_BATCH_ARG_MAP.MAPPING_TAG_NAME
     *
     * @return the value of ALRT_EVT_BATCH_ARG_MAP.MAPPING_TAG_NAME
     */
    public String getMAPPING_TAG_NAME() {
        return MAPPING_TAG_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_BATCH_ARG_MAP.MAPPING_TAG_NAME
     *
     * @param MAPPING_TAG_NAME the value for ALRT_EVT_BATCH_ARG_MAP.MAPPING_TAG_NAME
     */
    public void setMAPPING_TAG_NAME(String MAPPING_TAG_NAME) {
        this.MAPPING_TAG_NAME = MAPPING_TAG_NAME == null ? null : MAPPING_TAG_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_BATCH_ARG_MAP.MAPPING_VALUE
     *
     * @return the value of ALRT_EVT_BATCH_ARG_MAP.MAPPING_VALUE
     */
    public String getMAPPING_VALUE() {
        return MAPPING_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_BATCH_ARG_MAP.MAPPING_VALUE
     *
     * @param MAPPING_VALUE the value for ALRT_EVT_BATCH_ARG_MAP.MAPPING_VALUE
     */
    public void setMAPPING_VALUE(String MAPPING_VALUE) {
        this.MAPPING_VALUE = MAPPING_VALUE == null ? null : MAPPING_VALUE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_BATCH_ARG_MAP.CREATED_BY
     *
     * @return the value of ALRT_EVT_BATCH_ARG_MAP.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_BATCH_ARG_MAP.CREATED_BY
     *
     * @param CREATED_BY the value for ALRT_EVT_BATCH_ARG_MAP.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_BATCH_ARG_MAP.CREATED_DATE
     *
     * @return the value of ALRT_EVT_BATCH_ARG_MAP.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_BATCH_ARG_MAP.CREATED_DATE
     *
     * @param CREATED_DATE the value for ALRT_EVT_BATCH_ARG_MAP.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_BATCH_ARG_MAP.MODIFIED_BY
     *
     * @return the value of ALRT_EVT_BATCH_ARG_MAP.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_BATCH_ARG_MAP.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for ALRT_EVT_BATCH_ARG_MAP.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_BATCH_ARG_MAP.MODIFIED_DATE
     *
     * @return the value of ALRT_EVT_BATCH_ARG_MAP.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_BATCH_ARG_MAP.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for ALRT_EVT_BATCH_ARG_MAP.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }
}