package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ALRT_SUB_EVT_COMM_MODE_EXCLVO extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_SUB_EVT_COMM_MODE_EXCL.COMMUNICATION_TYPE
     */
    private String COMMUNICATION_TYPE;

    /**
     * This field corresponds to the database column ALRT_SUB_EVT_COMM_MODE_EXCL.SUBSCRIPTION_ID
     */
    private BigDecimal SUBSCRIPTION_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_COMM_MODE_EXCL.COMMUNICATION_TYPE
     *
     * @return the value of ALRT_SUB_EVT_COMM_MODE_EXCL.COMMUNICATION_TYPE
     */
    public String getCOMMUNICATION_TYPE() {
        return COMMUNICATION_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_COMM_MODE_EXCL.COMMUNICATION_TYPE
     *
     * @param COMMUNICATION_TYPE the value for ALRT_SUB_EVT_COMM_MODE_EXCL.COMMUNICATION_TYPE
     */
    public void setCOMMUNICATION_TYPE(String COMMUNICATION_TYPE) {
        this.COMMUNICATION_TYPE = COMMUNICATION_TYPE == null ? null : COMMUNICATION_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_EVT_COMM_MODE_EXCL.SUBSCRIPTION_ID
     *
     * @return the value of ALRT_SUB_EVT_COMM_MODE_EXCL.SUBSCRIPTION_ID
     */
    public BigDecimal getSUBSCRIPTION_ID() {
        return SUBSCRIPTION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_EVT_COMM_MODE_EXCL.SUBSCRIPTION_ID
     *
     * @param SUBSCRIPTION_ID the value for ALRT_SUB_EVT_COMM_MODE_EXCL.SUBSCRIPTION_ID
     */
    public void setSUBSCRIPTION_ID(BigDecimal SUBSCRIPTION_ID) {
        this.SUBSCRIPTION_ID = SUBSCRIPTION_ID;
    }
}