package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class ALRT_EVT_OL_DATA_TRANSVO extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_EVT_OL_DATA_TRANS.COMMUNICATION_TYPE
     */
    private String COMMUNICATION_TYPE;

    /**
     * This field corresponds to the database column ALRT_EVT_OL_DATA_TRANS.EVT_ID
     */
    private BigDecimal EVT_ID;

    /**
     * This field corresponds to the database column ALRT_EVT_OL_DATA_TRANS.LANG_CODE
     */
    private String LANG_CODE;

    /**
     * This field corresponds to the database column ALRT_EVT_OL_DATA_TRANS.MESSAGE_SUBJECT
     */
    private String MESSAGE_SUBJECT;

    /**
     * This field corresponds to the database column ALRT_EVT_OL_DATA_TRANS.MESSAGE_BODY
     */
    private String MESSAGE_BODY;

    /**
     * This field corresponds to the database column ALRT_EVT_OL_DATA_TRANS.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column ALRT_EVT_OL_DATA_TRANS.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column ALRT_EVT_OL_DATA_TRANS.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column ALRT_EVT_OL_DATA_TRANS.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_OL_DATA_TRANS.COMMUNICATION_TYPE
     *
     * @return the value of ALRT_EVT_OL_DATA_TRANS.COMMUNICATION_TYPE
     */
    public String getCOMMUNICATION_TYPE() {
        return COMMUNICATION_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_OL_DATA_TRANS.COMMUNICATION_TYPE
     *
     * @param COMMUNICATION_TYPE the value for ALRT_EVT_OL_DATA_TRANS.COMMUNICATION_TYPE
     */
    public void setCOMMUNICATION_TYPE(String COMMUNICATION_TYPE) {
        this.COMMUNICATION_TYPE = COMMUNICATION_TYPE == null ? null : COMMUNICATION_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_OL_DATA_TRANS.EVT_ID
     *
     * @return the value of ALRT_EVT_OL_DATA_TRANS.EVT_ID
     */
    public BigDecimal getEVT_ID() {
        return EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_OL_DATA_TRANS.EVT_ID
     *
     * @param EVT_ID the value for ALRT_EVT_OL_DATA_TRANS.EVT_ID
     */
    public void setEVT_ID(BigDecimal EVT_ID) {
        this.EVT_ID = EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_OL_DATA_TRANS.LANG_CODE
     *
     * @return the value of ALRT_EVT_OL_DATA_TRANS.LANG_CODE
     */
    public String getLANG_CODE() {
        return LANG_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_OL_DATA_TRANS.LANG_CODE
     *
     * @param LANG_CODE the value for ALRT_EVT_OL_DATA_TRANS.LANG_CODE
     */
    public void setLANG_CODE(String LANG_CODE) {
        this.LANG_CODE = LANG_CODE == null ? null : LANG_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_OL_DATA_TRANS.MESSAGE_SUBJECT
     *
     * @return the value of ALRT_EVT_OL_DATA_TRANS.MESSAGE_SUBJECT
     */
    public String getMESSAGE_SUBJECT() {
        return MESSAGE_SUBJECT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_OL_DATA_TRANS.MESSAGE_SUBJECT
     *
     * @param MESSAGE_SUBJECT the value for ALRT_EVT_OL_DATA_TRANS.MESSAGE_SUBJECT
     */
    public void setMESSAGE_SUBJECT(String MESSAGE_SUBJECT) {
        this.MESSAGE_SUBJECT = MESSAGE_SUBJECT == null ? null : MESSAGE_SUBJECT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_OL_DATA_TRANS.MESSAGE_BODY
     *
     * @return the value of ALRT_EVT_OL_DATA_TRANS.MESSAGE_BODY
     */
    public String getMESSAGE_BODY() {
        return MESSAGE_BODY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_OL_DATA_TRANS.MESSAGE_BODY
     *
     * @param MESSAGE_BODY the value for ALRT_EVT_OL_DATA_TRANS.MESSAGE_BODY
     */
    public void setMESSAGE_BODY(String MESSAGE_BODY) {
        this.MESSAGE_BODY = MESSAGE_BODY == null ? null : MESSAGE_BODY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_OL_DATA_TRANS.CREATED_BY
     *
     * @return the value of ALRT_EVT_OL_DATA_TRANS.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_OL_DATA_TRANS.CREATED_BY
     *
     * @param CREATED_BY the value for ALRT_EVT_OL_DATA_TRANS.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_OL_DATA_TRANS.CREATED_DATE
     *
     * @return the value of ALRT_EVT_OL_DATA_TRANS.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_OL_DATA_TRANS.CREATED_DATE
     *
     * @param CREATED_DATE the value for ALRT_EVT_OL_DATA_TRANS.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_OL_DATA_TRANS.MODIFIED_BY
     *
     * @return the value of ALRT_EVT_OL_DATA_TRANS.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_OL_DATA_TRANS.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for ALRT_EVT_OL_DATA_TRANS.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_OL_DATA_TRANS.MODIFIED_DATE
     *
     * @return the value of ALRT_EVT_OL_DATA_TRANS.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_OL_DATA_TRANS.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for ALRT_EVT_OL_DATA_TRANS.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }
}