package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ALRT_EMAIL_TEMPLATEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_EMAIL_TEMPLATE.TEMPLATE_ID
     */
    private BigDecimal TEMPLATE_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EMAIL_TEMPLATE.TEMPLATE_ID
     *
     * @return the value of ALRT_EMAIL_TEMPLATE.TEMPLATE_ID
     */
    public BigDecimal getTEMPLATE_ID() {
        return TEMPLATE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EMAIL_TEMPLATE.TEMPLATE_ID
     *
     * @param TEMPLATE_ID the value for ALRT_EMAIL_TEMPLATE.TEMPLATE_ID
     */
    public void setTEMPLATE_ID(BigDecimal TEMPLATE_ID) {
        this.TEMPLATE_ID = TEMPLATE_ID;
    }
}