package com.path.dbmaps.vo;

public class ALRT_SUB_DETVO extends ALRT_SUB_DETVOKey {
    /**
     * This field corresponds to the database column ALRT_SUB_DET.SHORT_NAME_ENG
     */
    private String SHORT_NAME_ENG;

    /**
     * This field corresponds to the database column ALRT_SUB_DET.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column ALRT_SUB_DET.EMAIL_ID
     */
    private String EMAIL_ID;

    /**
     * This field corresponds to the database column ALRT_SUB_DET.MOBILE_PHONE
     */
    private String MOBILE_PHONE;

    /**
     * This field corresponds to the database column ALRT_SUB_DET.SHORT_NAME_ARAB
     */
    private String SHORT_NAME_ARAB;

    /**
     * This field corresponds to the database column ALRT_SUB_DET.LONG_NAME_ARAB
     */
    private String LONG_NAME_ARAB;

    /**
     * This field corresponds to the database column ALRT_SUB_DET.ADDRESS1_ENG
     */
    private String ADDRESS1_ENG;

    /**
     * This field corresponds to the database column ALRT_SUB_DET.ADDRESS2_ENG
     */
    private String ADDRESS2_ENG;

    /**
     * This field corresponds to the database column ALRT_SUB_DET.ADDRESS3_ENG
     */
    private String ADDRESS3_ENG;

    /**
     * This field corresponds to the database column ALRT_SUB_DET.ADDRESS1_ARAB
     */
    private String ADDRESS1_ARAB;

    /**
     * This field corresponds to the database column ALRT_SUB_DET.ADDRESS2_ARAB
     */
    private String ADDRESS2_ARAB;

    /**
     * This field corresponds to the database column ALRT_SUB_DET.ADDRESS3_ARAB
     */
    private String ADDRESS3_ARAB;

    /**
     * This field corresponds to the database column ALRT_SUB_DET.TEL1_NUM
     */
    private String TEL1_NUM;

    /**
     * This field corresponds to the database column ALRT_SUB_DET.TEL2_NUM
     */
    private String TEL2_NUM;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_DET.SHORT_NAME_ENG
     *
     * @return the value of ALRT_SUB_DET.SHORT_NAME_ENG
     */
    public String getSHORT_NAME_ENG() {
        return SHORT_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_DET.SHORT_NAME_ENG
     *
     * @param SHORT_NAME_ENG the value for ALRT_SUB_DET.SHORT_NAME_ENG
     */
    public void setSHORT_NAME_ENG(String SHORT_NAME_ENG) {
        this.SHORT_NAME_ENG = SHORT_NAME_ENG == null ? null : SHORT_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_DET.LONG_NAME_ENG
     *
     * @return the value of ALRT_SUB_DET.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG() {
        return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_DET.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for ALRT_SUB_DET.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG) {
        this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_DET.EMAIL_ID
     *
     * @return the value of ALRT_SUB_DET.EMAIL_ID
     */
    public String getEMAIL_ID() {
        return EMAIL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_DET.EMAIL_ID
     *
     * @param EMAIL_ID the value for ALRT_SUB_DET.EMAIL_ID
     */
    public void setEMAIL_ID(String EMAIL_ID) {
        this.EMAIL_ID = EMAIL_ID == null ? null : EMAIL_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_DET.MOBILE_PHONE
     *
     * @return the value of ALRT_SUB_DET.MOBILE_PHONE
     */
    public String getMOBILE_PHONE() {
        return MOBILE_PHONE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_DET.MOBILE_PHONE
     *
     * @param MOBILE_PHONE the value for ALRT_SUB_DET.MOBILE_PHONE
     */
    public void setMOBILE_PHONE(String MOBILE_PHONE) {
        this.MOBILE_PHONE = MOBILE_PHONE == null ? null : MOBILE_PHONE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_DET.SHORT_NAME_ARAB
     *
     * @return the value of ALRT_SUB_DET.SHORT_NAME_ARAB
     */
    public String getSHORT_NAME_ARAB() {
        return SHORT_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_DET.SHORT_NAME_ARAB
     *
     * @param SHORT_NAME_ARAB the value for ALRT_SUB_DET.SHORT_NAME_ARAB
     */
    public void setSHORT_NAME_ARAB(String SHORT_NAME_ARAB) {
        this.SHORT_NAME_ARAB = SHORT_NAME_ARAB == null ? null : SHORT_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_DET.LONG_NAME_ARAB
     *
     * @return the value of ALRT_SUB_DET.LONG_NAME_ARAB
     */
    public String getLONG_NAME_ARAB() {
        return LONG_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_DET.LONG_NAME_ARAB
     *
     * @param LONG_NAME_ARAB the value for ALRT_SUB_DET.LONG_NAME_ARAB
     */
    public void setLONG_NAME_ARAB(String LONG_NAME_ARAB) {
        this.LONG_NAME_ARAB = LONG_NAME_ARAB == null ? null : LONG_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_DET.ADDRESS1_ENG
     *
     * @return the value of ALRT_SUB_DET.ADDRESS1_ENG
     */
    public String getADDRESS1_ENG() {
        return ADDRESS1_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_DET.ADDRESS1_ENG
     *
     * @param ADDRESS1_ENG the value for ALRT_SUB_DET.ADDRESS1_ENG
     */
    public void setADDRESS1_ENG(String ADDRESS1_ENG) {
        this.ADDRESS1_ENG = ADDRESS1_ENG == null ? null : ADDRESS1_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_DET.ADDRESS2_ENG
     *
     * @return the value of ALRT_SUB_DET.ADDRESS2_ENG
     */
    public String getADDRESS2_ENG() {
        return ADDRESS2_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_DET.ADDRESS2_ENG
     *
     * @param ADDRESS2_ENG the value for ALRT_SUB_DET.ADDRESS2_ENG
     */
    public void setADDRESS2_ENG(String ADDRESS2_ENG) {
        this.ADDRESS2_ENG = ADDRESS2_ENG == null ? null : ADDRESS2_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_DET.ADDRESS3_ENG
     *
     * @return the value of ALRT_SUB_DET.ADDRESS3_ENG
     */
    public String getADDRESS3_ENG() {
        return ADDRESS3_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_DET.ADDRESS3_ENG
     *
     * @param ADDRESS3_ENG the value for ALRT_SUB_DET.ADDRESS3_ENG
     */
    public void setADDRESS3_ENG(String ADDRESS3_ENG) {
        this.ADDRESS3_ENG = ADDRESS3_ENG == null ? null : ADDRESS3_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_DET.ADDRESS1_ARAB
     *
     * @return the value of ALRT_SUB_DET.ADDRESS1_ARAB
     */
    public String getADDRESS1_ARAB() {
        return ADDRESS1_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_DET.ADDRESS1_ARAB
     *
     * @param ADDRESS1_ARAB the value for ALRT_SUB_DET.ADDRESS1_ARAB
     */
    public void setADDRESS1_ARAB(String ADDRESS1_ARAB) {
        this.ADDRESS1_ARAB = ADDRESS1_ARAB == null ? null : ADDRESS1_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_DET.ADDRESS2_ARAB
     *
     * @return the value of ALRT_SUB_DET.ADDRESS2_ARAB
     */
    public String getADDRESS2_ARAB() {
        return ADDRESS2_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_DET.ADDRESS2_ARAB
     *
     * @param ADDRESS2_ARAB the value for ALRT_SUB_DET.ADDRESS2_ARAB
     */
    public void setADDRESS2_ARAB(String ADDRESS2_ARAB) {
        this.ADDRESS2_ARAB = ADDRESS2_ARAB == null ? null : ADDRESS2_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_DET.ADDRESS3_ARAB
     *
     * @return the value of ALRT_SUB_DET.ADDRESS3_ARAB
     */
    public String getADDRESS3_ARAB() {
        return ADDRESS3_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_DET.ADDRESS3_ARAB
     *
     * @param ADDRESS3_ARAB the value for ALRT_SUB_DET.ADDRESS3_ARAB
     */
    public void setADDRESS3_ARAB(String ADDRESS3_ARAB) {
        this.ADDRESS3_ARAB = ADDRESS3_ARAB == null ? null : ADDRESS3_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_DET.TEL1_NUM
     *
     * @return the value of ALRT_SUB_DET.TEL1_NUM
     */
    public String getTEL1_NUM() {
        return TEL1_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_DET.TEL1_NUM
     *
     * @param TEL1_NUM the value for ALRT_SUB_DET.TEL1_NUM
     */
    public void setTEL1_NUM(String TEL1_NUM) {
        this.TEL1_NUM = TEL1_NUM == null ? null : TEL1_NUM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_DET.TEL2_NUM
     *
     * @return the value of ALRT_SUB_DET.TEL2_NUM
     */
    public String getTEL2_NUM() {
        return TEL2_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_DET.TEL2_NUM
     *
     * @param TEL2_NUM the value for ALRT_SUB_DET.TEL2_NUM
     */
    public void setTEL2_NUM(String TEL2_NUM) {
        this.TEL2_NUM = TEL2_NUM == null ? null : TEL2_NUM.trim();
    }
}