package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class ALRT_NOT_IN_PKG_TMPVO extends ALRT_NOT_IN_PKG_TMPVOKey {
    /**
     * This field corresponds to the database column ALRT_NOT_IN_PKG_TMP.EVT_TYPE
     */
    private String EVT_TYPE;

    /**
     * This field corresponds to the database column ALRT_NOT_IN_PKG_TMP.DESCRIPTION
     */
    private String DESCRIPTION;

    /**
     * This field corresponds to the database column ALRT_NOT_IN_PKG_TMP.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column ALRT_NOT_IN_PKG_TMP.EVT_MODE
     */
    private String EVT_MODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_NOT_IN_PKG_TMP.EVT_TYPE
     *
     * @return the value of ALRT_NOT_IN_PKG_TMP.EVT_TYPE
     */
    public String getEVT_TYPE() {
        return EVT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_NOT_IN_PKG_TMP.EVT_TYPE
     *
     * @param EVT_TYPE the value for ALRT_NOT_IN_PKG_TMP.EVT_TYPE
     */
    public void setEVT_TYPE(String EVT_TYPE) {
        this.EVT_TYPE = EVT_TYPE == null ? null : EVT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_NOT_IN_PKG_TMP.DESCRIPTION
     *
     * @return the value of ALRT_NOT_IN_PKG_TMP.DESCRIPTION
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_NOT_IN_PKG_TMP.DESCRIPTION
     *
     * @param DESCRIPTION the value for ALRT_NOT_IN_PKG_TMP.DESCRIPTION
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_NOT_IN_PKG_TMP.LINE_NO
     *
     * @return the value of ALRT_NOT_IN_PKG_TMP.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_NOT_IN_PKG_TMP.LINE_NO
     *
     * @param LINE_NO the value for ALRT_NOT_IN_PKG_TMP.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_NOT_IN_PKG_TMP.EVT_MODE
     *
     * @return the value of ALRT_NOT_IN_PKG_TMP.EVT_MODE
     */
    public String getEVT_MODE() {
        return EVT_MODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_NOT_IN_PKG_TMP.EVT_MODE
     *
     * @param EVT_MODE the value for ALRT_NOT_IN_PKG_TMP.EVT_MODE
     */
    public void setEVT_MODE(String EVT_MODE) {
        this.EVT_MODE = EVT_MODE == null ? null : EVT_MODE.trim();
    }
}