package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class ALRT_SUB_TMPVO extends ALRT_SUB_TMPVOKey {
    /**
     * This field corresponds to the database column ALRT_SUB_TMP.SUB_TYPE
     */
    private String SUB_TYPE;

    /**
     * This field corresponds to the database column ALRT_SUB_TMP.MOBILE_PHONE
     */
    private String MOBILE_PHONE;

    /**
     * This field corresponds to the database column ALRT_SUB_TMP.EMAIL_ID
     */
    private String EMAIL_ID;

    /**
     * This field corresponds to the database column ALRT_SUB_TMP.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column ALRT_SUB_TMP.DESCRIPTION
     */
    private String DESCRIPTION;

    /**
     * This field corresponds to the database column ALRT_SUB_TMP.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_TMP.SUB_TYPE
     *
     * @return the value of ALRT_SUB_TMP.SUB_TYPE
     */
    public String getSUB_TYPE() {
        return SUB_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_TMP.SUB_TYPE
     *
     * @param SUB_TYPE the value for ALRT_SUB_TMP.SUB_TYPE
     */
    public void setSUB_TYPE(String SUB_TYPE) {
        this.SUB_TYPE = SUB_TYPE == null ? null : SUB_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_TMP.MOBILE_PHONE
     *
     * @return the value of ALRT_SUB_TMP.MOBILE_PHONE
     */
    public String getMOBILE_PHONE() {
        return MOBILE_PHONE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_TMP.MOBILE_PHONE
     *
     * @param MOBILE_PHONE the value for ALRT_SUB_TMP.MOBILE_PHONE
     */
    public void setMOBILE_PHONE(String MOBILE_PHONE) {
        this.MOBILE_PHONE = MOBILE_PHONE == null ? null : MOBILE_PHONE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_TMP.EMAIL_ID
     *
     * @return the value of ALRT_SUB_TMP.EMAIL_ID
     */
    public String getEMAIL_ID() {
        return EMAIL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_TMP.EMAIL_ID
     *
     * @param EMAIL_ID the value for ALRT_SUB_TMP.EMAIL_ID
     */
    public void setEMAIL_ID(String EMAIL_ID) {
        this.EMAIL_ID = EMAIL_ID == null ? null : EMAIL_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_TMP.DATE_UPDATED
     *
     * @return the value of ALRT_SUB_TMP.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_TMP.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for ALRT_SUB_TMP.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_TMP.DESCRIPTION
     *
     * @return the value of ALRT_SUB_TMP.DESCRIPTION
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_TMP.DESCRIPTION
     *
     * @param DESCRIPTION the value for ALRT_SUB_TMP.DESCRIPTION
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_TMP.LINE_NO
     *
     * @return the value of ALRT_SUB_TMP.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_TMP.LINE_NO
     *
     * @param LINE_NO the value for ALRT_SUB_TMP.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }
}