package com.path.dbmaps.vo;

import java.util.Date;

public class ALRT_PKGVO extends ALRT_PKGVOKey {
    /**
     * This field corresponds to the database column ALRT_PKG.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column ALRT_PKG.BRIEF_DESC_ENG
     */
    private String BRIEF_DESC_ENG;

    /**
     * This field corresponds to the database column ALRT_PKG.LONG_DESC_ENG
     */
    private String LONG_DESC_ENG;

    /**
     * This field corresponds to the database column ALRT_PKG.BRIEF_DESC_ARAB
     */
    private String BRIEF_DESC_ARAB;

    /**
     * This field corresponds to the database column ALRT_PKG.LONG_DESC_ARAB
     */
    private String LONG_DESC_ARAB;

    /**
     * This field corresponds to the database column ALRT_PKG.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column ALRT_PKG.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column ALRT_PKG.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column ALRT_PKG.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column ALRT_PKG.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column ALRT_PKG.DATE_DELETED
     */
    private Date DATE_DELETED;

    /**
     * This field corresponds to the database column ALRT_PKG.AUTHORIZED_BY
     */
    private String AUTHORIZED_BY;

    /**
     * This field corresponds to the database column ALRT_PKG.DATE_AUTHORIZED
     */
    private Date DATE_AUTHORIZED;
    
    /**
     * This field corresponds to the database column ALRT_PKG.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PKG.STATUS
     *
     * @return the value of ALRT_PKG.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PKG.STATUS
     *
     * @param STATUS the value for ALRT_PKG.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PKG.BRIEF_DESC_ENG
     *
     * @return the value of ALRT_PKG.BRIEF_DESC_ENG
     */
    public String getBRIEF_DESC_ENG() {
        return BRIEF_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PKG.BRIEF_DESC_ENG
     *
     * @param BRIEF_DESC_ENG the value for ALRT_PKG.BRIEF_DESC_ENG
     */
    public void setBRIEF_DESC_ENG(String BRIEF_DESC_ENG) {
        this.BRIEF_DESC_ENG = BRIEF_DESC_ENG == null ? null : BRIEF_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PKG.LONG_DESC_ENG
     *
     * @return the value of ALRT_PKG.LONG_DESC_ENG
     */
    public String getLONG_DESC_ENG() {
        return LONG_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PKG.LONG_DESC_ENG
     *
     * @param LONG_DESC_ENG the value for ALRT_PKG.LONG_DESC_ENG
     */
    public void setLONG_DESC_ENG(String LONG_DESC_ENG) {
        this.LONG_DESC_ENG = LONG_DESC_ENG == null ? null : LONG_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PKG.BRIEF_DESC_ARAB
     *
     * @return the value of ALRT_PKG.BRIEF_DESC_ARAB
     */
    public String getBRIEF_DESC_ARAB() {
        return BRIEF_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PKG.BRIEF_DESC_ARAB
     *
     * @param BRIEF_DESC_ARAB the value for ALRT_PKG.BRIEF_DESC_ARAB
     */
    public void setBRIEF_DESC_ARAB(String BRIEF_DESC_ARAB) {
        this.BRIEF_DESC_ARAB = BRIEF_DESC_ARAB == null ? null : BRIEF_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PKG.LONG_DESC_ARAB
     *
     * @return the value of ALRT_PKG.LONG_DESC_ARAB
     */
    public String getLONG_DESC_ARAB() {
        return LONG_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PKG.LONG_DESC_ARAB
     *
     * @param LONG_DESC_ARAB the value for ALRT_PKG.LONG_DESC_ARAB
     */
    public void setLONG_DESC_ARAB(String LONG_DESC_ARAB) {
        this.LONG_DESC_ARAB = LONG_DESC_ARAB == null ? null : LONG_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PKG.CREATED_BY
     *
     * @return the value of ALRT_PKG.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PKG.CREATED_BY
     *
     * @param CREATED_BY the value for ALRT_PKG.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PKG.DATE_CREATED
     *
     * @return the value of ALRT_PKG.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PKG.DATE_CREATED
     *
     * @param DATE_CREATED the value for ALRT_PKG.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PKG.MODIFIED_BY
     *
     * @return the value of ALRT_PKG.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PKG.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for ALRT_PKG.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PKG.DATE_MODIFIED
     *
     * @return the value of ALRT_PKG.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PKG.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for ALRT_PKG.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PKG.DELETED_BY
     *
     * @return the value of ALRT_PKG.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PKG.DELETED_BY
     *
     * @param DELETED_BY the value for ALRT_PKG.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PKG.DATE_DELETED
     *
     * @return the value of ALRT_PKG.DATE_DELETED
     */
    public Date getDATE_DELETED() {
        return DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PKG.DATE_DELETED
     *
     * @param DATE_DELETED the value for ALRT_PKG.DATE_DELETED
     */
    public void setDATE_DELETED(Date DATE_DELETED) {
        this.DATE_DELETED = DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PKG.AUTHORIZED_BY
     *
     * @return the value of ALRT_PKG.AUTHORIZED_BY
     */
    public String getAUTHORIZED_BY() {
        return AUTHORIZED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PKG.AUTHORIZED_BY
     *
     * @param AUTHORIZED_BY the value for ALRT_PKG.AUTHORIZED_BY
     */
    public void setAUTHORIZED_BY(String AUTHORIZED_BY) {
        this.AUTHORIZED_BY = AUTHORIZED_BY == null ? null : AUTHORIZED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PKG.DATE_AUTHORIZED
     *
     * @return the value of ALRT_PKG.DATE_AUTHORIZED
     */
    public Date getDATE_AUTHORIZED() {
        return DATE_AUTHORIZED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PKG.DATE_AUTHORIZED
     *
     * @param DATE_AUTHORIZED the value for ALRT_PKG.DATE_AUTHORIZED
     */
    public void setDATE_AUTHORIZED(Date DATE_AUTHORIZED) {
        this.DATE_AUTHORIZED = DATE_AUTHORIZED;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PKG.DATE_UPDATED
     *
     * @return the value of ALRT_PKG.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PKG.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for ALRT_PKG.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}