package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class ALRT_EVT_COMM_MODEVO extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_EVT_COMM_MODE.COMMUNICATION_TYPE
     */
    private String COMMUNICATION_TYPE;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_MODE.EVT_ID
     */
    private BigDecimal EVT_ID;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_MODE.DEFAULT_MESSAGE_BODY
     */
    private String DEFAULT_MESSAGE_BODY;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_MODE.DEFAULT_MESSAGE_SUBJECT
     */
    private String DEFAULT_MESSAGE_SUBJECT;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_MODE.TEMPLATE_TYPE
     */
    private String TEMPLATE_TYPE;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_MODE.REPORT_ID
     */
    private BigDecimal REPORT_ID;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_MODE.QUERY_ID
     */
    private BigDecimal QUERY_ID;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_MODE.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_MODE.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_MODE.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_MODE.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column ALRT_EVT_COMM_MODE.ACTIVATED_YN
     */
    private String ACTIVATED_YN;
    
//    private String SEND_TO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_MODE.COMMUNICATION_TYPE
     *
     * @return the value of ALRT_EVT_COMM_MODE.COMMUNICATION_TYPE
     */
    public String getCOMMUNICATION_TYPE() {
        return COMMUNICATION_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_MODE.COMMUNICATION_TYPE
     *
     * @param COMMUNICATION_TYPE the value for ALRT_EVT_COMM_MODE.COMMUNICATION_TYPE
     */
    public void setCOMMUNICATION_TYPE(String COMMUNICATION_TYPE) {
        this.COMMUNICATION_TYPE = COMMUNICATION_TYPE == null ? null : COMMUNICATION_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_MODE.EVT_ID
     *
     * @return the value of ALRT_EVT_COMM_MODE.EVT_ID
     */
    public BigDecimal getEVT_ID() {
        return EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_MODE.EVT_ID
     *
     * @param EVT_ID the value for ALRT_EVT_COMM_MODE.EVT_ID
     */
    public void setEVT_ID(BigDecimal EVT_ID) {
        this.EVT_ID = EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_MODE.DEFAULT_MESSAGE_BODY
     *
     * @return the value of ALRT_EVT_COMM_MODE.DEFAULT_MESSAGE_BODY
     */
    public String getDEFAULT_MESSAGE_BODY() {
        return DEFAULT_MESSAGE_BODY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_MODE.DEFAULT_MESSAGE_BODY
     *
     * @param DEFAULT_MESSAGE_BODY the value for ALRT_EVT_COMM_MODE.DEFAULT_MESSAGE_BODY
     */
    public void setDEFAULT_MESSAGE_BODY(String DEFAULT_MESSAGE_BODY) {
        this.DEFAULT_MESSAGE_BODY = DEFAULT_MESSAGE_BODY == null ? null : DEFAULT_MESSAGE_BODY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_MODE.DEFAULT_MESSAGE_SUBJECT
     *
     * @return the value of ALRT_EVT_COMM_MODE.DEFAULT_MESSAGE_SUBJECT
     */
    public String getDEFAULT_MESSAGE_SUBJECT() {
        return DEFAULT_MESSAGE_SUBJECT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_MODE.DEFAULT_MESSAGE_SUBJECT
     *
     * @param DEFAULT_MESSAGE_SUBJECT the value for ALRT_EVT_COMM_MODE.DEFAULT_MESSAGE_SUBJECT
     */
    public void setDEFAULT_MESSAGE_SUBJECT(String DEFAULT_MESSAGE_SUBJECT) {
        this.DEFAULT_MESSAGE_SUBJECT = DEFAULT_MESSAGE_SUBJECT == null ? null : DEFAULT_MESSAGE_SUBJECT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_MODE.TEMPLATE_TYPE
     *
     * @return the value of ALRT_EVT_COMM_MODE.TEMPLATE_TYPE
     */
    public String getTEMPLATE_TYPE() {
        return TEMPLATE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_MODE.TEMPLATE_TYPE
     *
     * @param TEMPLATE_TYPE the value for ALRT_EVT_COMM_MODE.TEMPLATE_TYPE
     */
    public void setTEMPLATE_TYPE(String TEMPLATE_TYPE) {
        this.TEMPLATE_TYPE = TEMPLATE_TYPE == null ? null : TEMPLATE_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_MODE.REPORT_ID
     *
     * @return the value of ALRT_EVT_COMM_MODE.REPORT_ID
     */
    public BigDecimal getREPORT_ID() {
        return REPORT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_MODE.REPORT_ID
     *
     * @param REPORT_ID the value for ALRT_EVT_COMM_MODE.REPORT_ID
     */
    public void setREPORT_ID(BigDecimal REPORT_ID) {
        this.REPORT_ID = REPORT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_MODE.QUERY_ID
     *
     * @return the value of ALRT_EVT_COMM_MODE.QUERY_ID
     */
    public BigDecimal getQUERY_ID() {
        return QUERY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_MODE.QUERY_ID
     *
     * @param QUERY_ID the value for ALRT_EVT_COMM_MODE.QUERY_ID
     */
    public void setQUERY_ID(BigDecimal QUERY_ID) {
        this.QUERY_ID = QUERY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_MODE.CREATED_BY
     *
     * @return the value of ALRT_EVT_COMM_MODE.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_MODE.CREATED_BY
     *
     * @param CREATED_BY the value for ALRT_EVT_COMM_MODE.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_MODE.CREATED_DATE
     *
     * @return the value of ALRT_EVT_COMM_MODE.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_MODE.CREATED_DATE
     *
     * @param CREATED_DATE the value for ALRT_EVT_COMM_MODE.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_MODE.MODIFIED_BY
     *
     * @return the value of ALRT_EVT_COMM_MODE.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_MODE.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for ALRT_EVT_COMM_MODE.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_MODE.MODIFIED_DATE
     *
     * @return the value of ALRT_EVT_COMM_MODE.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_MODE.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for ALRT_EVT_COMM_MODE.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_EVT_COMM_MODE.ACTIVATED_YN
     *
     * @return the value of ALRT_EVT_COMM_MODE.ACTIVATED_YN
     */
    public String getACTIVATED_YN() {
        return ACTIVATED_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_EVT_COMM_MODE.ACTIVATED_YN
     *
     * @param ACTIVATED_YN the value for ALRT_EVT_COMM_MODE.ACTIVATED_YN
     */
    public void setACTIVATED_YN(String ACTIVATED_YN) {
        this.ACTIVATED_YN = ACTIVATED_YN == null ? null : ACTIVATED_YN.trim();
    }
    
//    public String getSEND_TO() {
//        return SEND_TO;
//    }
//
//    public void setSEND_TO(String SEND_TO) {
//        this.SEND_TO = SEND_TO == null ? null : SEND_TO.trim();
//    }
}