package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class ALRT_QUEUEVO extends ALRT_QUEUEVOKey {
    /**
     * This field corresponds to the database column ALRT_QUEUE.MESSAGE_SUBJECT_ENG
     */
    private String MESSAGE_SUBJECT_ENG;

    /**
     * This field corresponds to the database column ALRT_QUEUE.MESSAGE_TEXT_ENG
     */
    private String MESSAGE_TEXT_ENG;

    /**
     * This field corresponds to the database column ALRT_QUEUE.ALRT_DATE
     */
    private Date ALRT_DATE;

    /**
     * This field corresponds to the database column ALRT_QUEUE.STOP_AFTER
     */
    private BigDecimal STOP_AFTER;

    /**
     * This field corresponds to the database column ALRT_QUEUE.MOBILE_PHONE
     */
    private String MOBILE_PHONE;

    /**
     * This field corresponds to the database column ALRT_QUEUE.EMAIL_ID
     */
    private String EMAIL_ID;

    /**
     * This field corresponds to the database column ALRT_QUEUE.EVT_MODE
     */
    private String EVT_MODE;

    /**
     * This field corresponds to the database column ALRT_QUEUE.PERIOD
     */
    private BigDecimal PERIOD;

    /**
     * This field corresponds to the database column ALRT_QUEUE.PERIOD_TYPE
     */
    private String PERIOD_TYPE;

    /**
     * This field corresponds to the database column ALRT_QUEUE.EVT_ID
     */
    private BigDecimal EVT_ID;

    /**
     * This field corresponds to the database column ALRT_QUEUE.MESSAGE_TEXT_TAG
     */
    private String MESSAGE_TEXT_TAG;

    /**
     * This field corresponds to the database column ALRT_QUEUE.TRX_OP_NO
     */
    private BigDecimal TRX_OP_NO;

    /**
     * This field corresponds to the database column ALRT_QUEUE.MSG_LANG
     */
    private String MSG_LANG;

    /**
     * This field corresponds to the database column ALRT_QUEUE.SUB_ID
     */
    private BigDecimal SUB_ID;

    /**
     * This field corresponds to the database column ALRT_QUEUE.SBT_ID
     */
    private BigDecimal SBT_ID;

    /*
       This field corresponds to the database column ALRT_QUEUE.EVT_PRIORITY
     */
    private BigDecimal EVT_PRIORITY;
    
    
    public BigDecimal getEVT_PRIORITY() {
		return EVT_PRIORITY;
	}

	public void setEVT_PRIORITY(BigDecimal EVT_PRIORITY) {
		this.EVT_PRIORITY = EVT_PRIORITY;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_QUEUE.MESSAGE_SUBJECT_ENG
     *
     * @return the value of ALRT_QUEUE.MESSAGE_SUBJECT_ENG
     */
    public String getMESSAGE_SUBJECT_ENG() {
        return MESSAGE_SUBJECT_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_QUEUE.MESSAGE_SUBJECT_ENG
     *
     * @param MESSAGE_SUBJECT_ENG the value for ALRT_QUEUE.MESSAGE_SUBJECT_ENG
     */
    public void setMESSAGE_SUBJECT_ENG(String MESSAGE_SUBJECT_ENG) {
        this.MESSAGE_SUBJECT_ENG = MESSAGE_SUBJECT_ENG == null ? null : MESSAGE_SUBJECT_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_QUEUE.MESSAGE_TEXT_ENG
     *
     * @return the value of ALRT_QUEUE.MESSAGE_TEXT_ENG
     */
    public String getMESSAGE_TEXT_ENG() {
        return MESSAGE_TEXT_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_QUEUE.MESSAGE_TEXT_ENG
     *
     * @param MESSAGE_TEXT_ENG the value for ALRT_QUEUE.MESSAGE_TEXT_ENG
     */
    public void setMESSAGE_TEXT_ENG(String MESSAGE_TEXT_ENG) {
        this.MESSAGE_TEXT_ENG = MESSAGE_TEXT_ENG == null ? null : MESSAGE_TEXT_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_QUEUE.ALRT_DATE
     *
     * @return the value of ALRT_QUEUE.ALRT_DATE
     */
    public Date getALRT_DATE() {
        return ALRT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_QUEUE.ALRT_DATE
     *
     * @param ALRT_DATE the value for ALRT_QUEUE.ALRT_DATE
     */
    public void setALRT_DATE(Date ALRT_DATE) {
        this.ALRT_DATE = ALRT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_QUEUE.STOP_AFTER
     *
     * @return the value of ALRT_QUEUE.STOP_AFTER
     */
    public BigDecimal getSTOP_AFTER() {
        return STOP_AFTER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_QUEUE.STOP_AFTER
     *
     * @param STOP_AFTER the value for ALRT_QUEUE.STOP_AFTER
     */
    public void setSTOP_AFTER(BigDecimal STOP_AFTER) {
        this.STOP_AFTER = STOP_AFTER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_QUEUE.MOBILE_PHONE
     *
     * @return the value of ALRT_QUEUE.MOBILE_PHONE
     */
    public String getMOBILE_PHONE() {
        return MOBILE_PHONE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_QUEUE.MOBILE_PHONE
     *
     * @param MOBILE_PHONE the value for ALRT_QUEUE.MOBILE_PHONE
     */
    public void setMOBILE_PHONE(String MOBILE_PHONE) {
        this.MOBILE_PHONE = MOBILE_PHONE == null ? null : MOBILE_PHONE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_QUEUE.EMAIL_ID
     *
     * @return the value of ALRT_QUEUE.EMAIL_ID
     */
    public String getEMAIL_ID() {
        return EMAIL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_QUEUE.EMAIL_ID
     *
     * @param EMAIL_ID the value for ALRT_QUEUE.EMAIL_ID
     */
    public void setEMAIL_ID(String EMAIL_ID) {
        this.EMAIL_ID = EMAIL_ID == null ? null : EMAIL_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_QUEUE.EVT_MODE
     *
     * @return the value of ALRT_QUEUE.EVT_MODE
     */
    public String getEVT_MODE() {
        return EVT_MODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_QUEUE.EVT_MODE
     *
     * @param EVT_MODE the value for ALRT_QUEUE.EVT_MODE
     */
    public void setEVT_MODE(String EVT_MODE) {
        this.EVT_MODE = EVT_MODE == null ? null : EVT_MODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_QUEUE.PERIOD
     *
     * @return the value of ALRT_QUEUE.PERIOD
     */
    public BigDecimal getPERIOD() {
        return PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_QUEUE.PERIOD
     *
     * @param PERIOD the value for ALRT_QUEUE.PERIOD
     */
    public void setPERIOD(BigDecimal PERIOD) {
        this.PERIOD = PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_QUEUE.PERIOD_TYPE
     *
     * @return the value of ALRT_QUEUE.PERIOD_TYPE
     */
    public String getPERIOD_TYPE() {
        return PERIOD_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_QUEUE.PERIOD_TYPE
     *
     * @param PERIOD_TYPE the value for ALRT_QUEUE.PERIOD_TYPE
     */
    public void setPERIOD_TYPE(String PERIOD_TYPE) {
        this.PERIOD_TYPE = PERIOD_TYPE == null ? null : PERIOD_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_QUEUE.EVT_ID
     *
     * @return the value of ALRT_QUEUE.EVT_ID
     */
    public BigDecimal getEVT_ID() {
        return EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_QUEUE.EVT_ID
     *
     * @param EVT_ID the value for ALRT_QUEUE.EVT_ID
     */
    public void setEVT_ID(BigDecimal EVT_ID) {
        this.EVT_ID = EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_QUEUE.MESSAGE_TEXT_TAG
     *
     * @return the value of ALRT_QUEUE.MESSAGE_TEXT_TAG
     */
    public String getMESSAGE_TEXT_TAG() {
        return MESSAGE_TEXT_TAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_QUEUE.MESSAGE_TEXT_TAG
     *
     * @param MESSAGE_TEXT_TAG the value for ALRT_QUEUE.MESSAGE_TEXT_TAG
     */
    public void setMESSAGE_TEXT_TAG(String MESSAGE_TEXT_TAG) {
        this.MESSAGE_TEXT_TAG = MESSAGE_TEXT_TAG == null ? null : MESSAGE_TEXT_TAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_QUEUE.TRX_OP_NO
     *
     * @return the value of ALRT_QUEUE.TRX_OP_NO
     */
    public BigDecimal getTRX_OP_NO() {
        return TRX_OP_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_QUEUE.TRX_OP_NO
     *
     * @param TRX_OP_NO the value for ALRT_QUEUE.TRX_OP_NO
     */
    public void setTRX_OP_NO(BigDecimal TRX_OP_NO) {
        this.TRX_OP_NO = TRX_OP_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_QUEUE.MSG_LANG
     *
     * @return the value of ALRT_QUEUE.MSG_LANG
     */
    public String getMSG_LANG() {
        return MSG_LANG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_QUEUE.MSG_LANG
     *
     * @param MSG_LANG the value for ALRT_QUEUE.MSG_LANG
     */
    public void setMSG_LANG(String MSG_LANG) {
        this.MSG_LANG = MSG_LANG == null ? null : MSG_LANG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_QUEUE.SUB_ID
     *
     * @return the value of ALRT_QUEUE.SUB_ID
     */
    public BigDecimal getSUB_ID() {
        return SUB_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_QUEUE.SUB_ID
     *
     * @param SUB_ID the value for ALRT_QUEUE.SUB_ID
     */
    public void setSUB_ID(BigDecimal SUB_ID) {
        this.SUB_ID = SUB_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_QUEUE.SBT_ID
     *
     * @return the value of ALRT_QUEUE.SBT_ID
     */
    public BigDecimal getSBT_ID() {
        return SBT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_QUEUE.SBT_ID
     *
     * @param SBT_ID the value for ALRT_QUEUE.SBT_ID
     */
    public void setSBT_ID(BigDecimal SBT_ID) {
        this.SBT_ID = SBT_ID;
    }
}