package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class ALRT_SUB_ACC_EXCLVO extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_SUB_ACC_EXCL.ALRT_SUB_ID
     */
    private BigDecimal ALRT_SUB_ID;

    /**
     * This field corresponds to the database column ALRT_SUB_ACC_EXCL.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column ALRT_SUB_ACC_EXCL.CIF_SUB_NO
     */
    private BigDecimal CIF_SUB_NO;

    /**
     * This field corresponds to the database column ALRT_SUB_ACC_EXCL.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column ALRT_SUB_ACC_EXCL.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column ALRT_SUB_ACC_EXCL.EVT_PKG_ID
     */
    private BigDecimal EVT_PKG_ID;

    /**
     * This field corresponds to the database column ALRT_SUB_ACC_EXCL.GL_CODE
     */
    private BigDecimal GL_CODE;

    /**
     * This field corresponds to the database column ALRT_SUB_ACC_EXCL.REL_TYPE
     */
    private String REL_TYPE;

    /**
     * This field corresponds to the database column ALRT_SUB_ACC_EXCL.SL_NO
     */
    private BigDecimal SL_NO;

    /**
     * This field corresponds to the database column ALRT_SUB_ACC_EXCL.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column ALRT_SUB_ACC_EXCL.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column ALRT_SUB_ACC_EXCL.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column ALRT_SUB_ACC_EXCL.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column ALRT_SUB_ACC_EXCL.ADDITIONAL_REFERENCE
     */
    private String ADDITIONAL_REFERENCE;

    /**
     * This field corresponds to the database column ALRT_SUB_ACC_EXCL.IBAN_ACC_NO
     */
    private String IBAN_ACC_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_ACC_EXCL.ALRT_SUB_ID
     *
     * @return the value of ALRT_SUB_ACC_EXCL.ALRT_SUB_ID
     */
    public BigDecimal getALRT_SUB_ID() {
        return ALRT_SUB_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_ACC_EXCL.ALRT_SUB_ID
     *
     * @param ALRT_SUB_ID the value for ALRT_SUB_ACC_EXCL.ALRT_SUB_ID
     */
    public void setALRT_SUB_ID(BigDecimal ALRT_SUB_ID) {
        this.ALRT_SUB_ID = ALRT_SUB_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_ACC_EXCL.BRANCH_CODE
     *
     * @return the value of ALRT_SUB_ACC_EXCL.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_ACC_EXCL.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for ALRT_SUB_ACC_EXCL.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_ACC_EXCL.CIF_SUB_NO
     *
     * @return the value of ALRT_SUB_ACC_EXCL.CIF_SUB_NO
     */
    public BigDecimal getCIF_SUB_NO() {
        return CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_ACC_EXCL.CIF_SUB_NO
     *
     * @param CIF_SUB_NO the value for ALRT_SUB_ACC_EXCL.CIF_SUB_NO
     */
    public void setCIF_SUB_NO(BigDecimal CIF_SUB_NO) {
        this.CIF_SUB_NO = CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_ACC_EXCL.COMP_CODE
     *
     * @return the value of ALRT_SUB_ACC_EXCL.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_ACC_EXCL.COMP_CODE
     *
     * @param COMP_CODE the value for ALRT_SUB_ACC_EXCL.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_ACC_EXCL.CURRENCY_CODE
     *
     * @return the value of ALRT_SUB_ACC_EXCL.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_ACC_EXCL.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for ALRT_SUB_ACC_EXCL.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_ACC_EXCL.EVT_PKG_ID
     *
     * @return the value of ALRT_SUB_ACC_EXCL.EVT_PKG_ID
     */
    public BigDecimal getEVT_PKG_ID() {
        return EVT_PKG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_ACC_EXCL.EVT_PKG_ID
     *
     * @param EVT_PKG_ID the value for ALRT_SUB_ACC_EXCL.EVT_PKG_ID
     */
    public void setEVT_PKG_ID(BigDecimal EVT_PKG_ID) {
        this.EVT_PKG_ID = EVT_PKG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_ACC_EXCL.GL_CODE
     *
     * @return the value of ALRT_SUB_ACC_EXCL.GL_CODE
     */
    public BigDecimal getGL_CODE() {
        return GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_ACC_EXCL.GL_CODE
     *
     * @param GL_CODE the value for ALRT_SUB_ACC_EXCL.GL_CODE
     */
    public void setGL_CODE(BigDecimal GL_CODE) {
        this.GL_CODE = GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_ACC_EXCL.REL_TYPE
     *
     * @return the value of ALRT_SUB_ACC_EXCL.REL_TYPE
     */
    public String getREL_TYPE() {
        return REL_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_ACC_EXCL.REL_TYPE
     *
     * @param REL_TYPE the value for ALRT_SUB_ACC_EXCL.REL_TYPE
     */
    public void setREL_TYPE(String REL_TYPE) {
        this.REL_TYPE = REL_TYPE == null ? null : REL_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_ACC_EXCL.SL_NO
     *
     * @return the value of ALRT_SUB_ACC_EXCL.SL_NO
     */
    public BigDecimal getSL_NO() {
        return SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_ACC_EXCL.SL_NO
     *
     * @param SL_NO the value for ALRT_SUB_ACC_EXCL.SL_NO
     */
    public void setSL_NO(BigDecimal SL_NO) {
        this.SL_NO = SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_ACC_EXCL.CREATED_BY
     *
     * @return the value of ALRT_SUB_ACC_EXCL.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_ACC_EXCL.CREATED_BY
     *
     * @param CREATED_BY the value for ALRT_SUB_ACC_EXCL.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_ACC_EXCL.CREATED_DATE
     *
     * @return the value of ALRT_SUB_ACC_EXCL.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_ACC_EXCL.CREATED_DATE
     *
     * @param CREATED_DATE the value for ALRT_SUB_ACC_EXCL.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_ACC_EXCL.MODIFIED_BY
     *
     * @return the value of ALRT_SUB_ACC_EXCL.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_ACC_EXCL.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for ALRT_SUB_ACC_EXCL.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_ACC_EXCL.MODIFIED_DATE
     *
     * @return the value of ALRT_SUB_ACC_EXCL.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_ACC_EXCL.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for ALRT_SUB_ACC_EXCL.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_ACC_EXCL.ADDITIONAL_REFERENCE
     *
     * @return the value of ALRT_SUB_ACC_EXCL.ADDITIONAL_REFERENCE
     */
    public String getADDITIONAL_REFERENCE() {
        return ADDITIONAL_REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_ACC_EXCL.ADDITIONAL_REFERENCE
     *
     * @param ADDITIONAL_REFERENCE the value for ALRT_SUB_ACC_EXCL.ADDITIONAL_REFERENCE
     */
    public void setADDITIONAL_REFERENCE(String ADDITIONAL_REFERENCE) {
        this.ADDITIONAL_REFERENCE = ADDITIONAL_REFERENCE == null ? null : ADDITIONAL_REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_ACC_EXCL.IBAN_ACC_NO
     *
     * @return the value of ALRT_SUB_ACC_EXCL.IBAN_ACC_NO
     */
    public String getIBAN_ACC_NO() {
        return IBAN_ACC_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_ACC_EXCL.IBAN_ACC_NO
     *
     * @param IBAN_ACC_NO the value for ALRT_SUB_ACC_EXCL.IBAN_ACC_NO
     */
    public void setIBAN_ACC_NO(String IBAN_ACC_NO) {
        this.IBAN_ACC_NO = IBAN_ACC_NO == null ? null : IBAN_ACC_NO.trim();
    }
}