package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ALRT_SUB_GRP_TMPVOKey extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_SUB_GRP_TMP.SESSION_ID
     */
    private String SESSION_ID;

    /**
     * This field corresponds to the database column ALRT_SUB_GRP_TMP.SUB_ID
     */
    private BigDecimal SUB_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_GRP_TMP.SESSION_ID
     *
     * @return the value of ALRT_SUB_GRP_TMP.SESSION_ID
     */
    public String getSESSION_ID() {
        return SESSION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_GRP_TMP.SESSION_ID
     *
     * @param SESSION_ID the value for ALRT_SUB_GRP_TMP.SESSION_ID
     */
    public void setSESSION_ID(String SESSION_ID) {
        this.SESSION_ID = SESSION_ID == null ? null : SESSION_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_SUB_GRP_TMP.SUB_ID
     *
     * @return the value of ALRT_SUB_GRP_TMP.SUB_ID
     */
    public BigDecimal getSUB_ID() {
        return SUB_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_SUB_GRP_TMP.SUB_ID
     *
     * @param SUB_ID the value for ALRT_SUB_GRP_TMP.SUB_ID
     */
    public void setSUB_ID(BigDecimal SUB_ID) {
        this.SUB_ID = SUB_ID;
    }
}