package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class ALRT_GRP_PKGVO extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_GRP_PKG.GRP_ID
     */
    private BigDecimal GRP_ID;

    /**
     * This field corresponds to the database column ALRT_GRP_PKG.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column ALRT_GRP_PKG.PKG_ID
     */
    private BigDecimal PKG_ID;

    /**
     * This field corresponds to the database column ALRT_GRP_PKG.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column ALRT_GRP_PKG.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column ALRT_GRP_PKG.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column ALRT_GRP_PKG.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column ALRT_GRP_PKG.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column ALRT_GRP_PKG.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column ALRT_GRP_PKG.DATE_DELETED
     */
    private Date DATE_DELETED;

    /**
     * This field corresponds to the database column ALRT_GRP_PKG.AUTHORIZED_BY
     */
    private String AUTHORIZED_BY;

    /**
     * This field corresponds to the database column ALRT_GRP_PKG.DATE_AUTHORIZED
     */
    private Date DATE_AUTHORIZED;

    /**
     * This field corresponds to the database column ALRT_GRP_PKG.SUSPENDED_BY
     */
    private String SUSPENDED_BY;

    /**
     * This field corresponds to the database column ALRT_GRP_PKG.DATE_SUSPENDED
     */
    private Date DATE_SUSPENDED;

    /**
     * This field corresponds to the database column ALRT_GRP_PKG.OLD_STATUS
     */
    private String OLD_STATUS;

    /**
     * This field corresponds to the database column ALRT_GRP_PKG.DATE_UPDATED
     */
    private Date DATE_UPDATED;
    
    /**
     * This field corresponds to the database column ALRT_GRP_PKG.STATUS
     */
    private String TO_BE_STATUS;
    
    /**
     * This field corresponds to the database column ALRT_GRP_PKG.STATUS_BY
     */
    private String TO_BE_STATUS_BY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_GRP_PKG.GRP_ID
     *
     * @return the value of ALRT_GRP_PKG.GRP_ID
     */
    public BigDecimal getGRP_ID() {
        return GRP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_GRP_PKG.GRP_ID
     *
     * @param GRP_ID the value for ALRT_GRP_PKG.GRP_ID
     */
    public void setGRP_ID(BigDecimal GRP_ID) {
        this.GRP_ID = GRP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_GRP_PKG.LINE_NO
     *
     * @return the value of ALRT_GRP_PKG.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_GRP_PKG.LINE_NO
     *
     * @param LINE_NO the value for ALRT_GRP_PKG.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_GRP_PKG.PKG_ID
     *
     * @return the value of ALRT_GRP_PKG.PKG_ID
     */
    public BigDecimal getPKG_ID() {
        return PKG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_GRP_PKG.PKG_ID
     *
     * @param PKG_ID the value for ALRT_GRP_PKG.PKG_ID
     */
    public void setPKG_ID(BigDecimal PKG_ID) {
        this.PKG_ID = PKG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_GRP_PKG.STATUS
     *
     * @return the value of ALRT_GRP_PKG.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_GRP_PKG.STATUS
     *
     * @param STATUS the value for ALRT_GRP_PKG.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_GRP_PKG.CREATED_BY
     *
     * @return the value of ALRT_GRP_PKG.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_GRP_PKG.CREATED_BY
     *
     * @param CREATED_BY the value for ALRT_GRP_PKG.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_GRP_PKG.DATE_CREATED
     *
     * @return the value of ALRT_GRP_PKG.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_GRP_PKG.DATE_CREATED
     *
     * @param DATE_CREATED the value for ALRT_GRP_PKG.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_GRP_PKG.MODIFIED_BY
     *
     * @return the value of ALRT_GRP_PKG.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_GRP_PKG.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for ALRT_GRP_PKG.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_GRP_PKG.DATE_MODIFIED
     *
     * @return the value of ALRT_GRP_PKG.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_GRP_PKG.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for ALRT_GRP_PKG.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_GRP_PKG.DELETED_BY
     *
     * @return the value of ALRT_GRP_PKG.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_GRP_PKG.DELETED_BY
     *
     * @param DELETED_BY the value for ALRT_GRP_PKG.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_GRP_PKG.DATE_DELETED
     *
     * @return the value of ALRT_GRP_PKG.DATE_DELETED
     */
    public Date getDATE_DELETED() {
        return DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_GRP_PKG.DATE_DELETED
     *
     * @param DATE_DELETED the value for ALRT_GRP_PKG.DATE_DELETED
     */
    public void setDATE_DELETED(Date DATE_DELETED) {
        this.DATE_DELETED = DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_GRP_PKG.AUTHORIZED_BY
     *
     * @return the value of ALRT_GRP_PKG.AUTHORIZED_BY
     */
    public String getAUTHORIZED_BY() {
        return AUTHORIZED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_GRP_PKG.AUTHORIZED_BY
     *
     * @param AUTHORIZED_BY the value for ALRT_GRP_PKG.AUTHORIZED_BY
     */
    public void setAUTHORIZED_BY(String AUTHORIZED_BY) {
        this.AUTHORIZED_BY = AUTHORIZED_BY == null ? null : AUTHORIZED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_GRP_PKG.DATE_AUTHORIZED
     *
     * @return the value of ALRT_GRP_PKG.DATE_AUTHORIZED
     */
    public Date getDATE_AUTHORIZED() {
        return DATE_AUTHORIZED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_GRP_PKG.DATE_AUTHORIZED
     *
     * @param DATE_AUTHORIZED the value for ALRT_GRP_PKG.DATE_AUTHORIZED
     */
    public void setDATE_AUTHORIZED(Date DATE_AUTHORIZED) {
        this.DATE_AUTHORIZED = DATE_AUTHORIZED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_GRP_PKG.SUSPENDED_BY
     *
     * @return the value of ALRT_GRP_PKG.SUSPENDED_BY
     */
    public String getSUSPENDED_BY() {
        return SUSPENDED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_GRP_PKG.SUSPENDED_BY
     *
     * @param SUSPENDED_BY the value for ALRT_GRP_PKG.SUSPENDED_BY
     */
    public void setSUSPENDED_BY(String SUSPENDED_BY) {
        this.SUSPENDED_BY = SUSPENDED_BY == null ? null : SUSPENDED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_GRP_PKG.DATE_SUSPENDED
     *
     * @return the value of ALRT_GRP_PKG.DATE_SUSPENDED
     */
    public Date getDATE_SUSPENDED() {
        return DATE_SUSPENDED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_GRP_PKG.DATE_SUSPENDED
     *
     * @param DATE_SUSPENDED the value for ALRT_GRP_PKG.DATE_SUSPENDED
     */
    public void setDATE_SUSPENDED(Date DATE_SUSPENDED) {
        this.DATE_SUSPENDED = DATE_SUSPENDED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_GRP_PKG.OLD_STATUS
     *
     * @return the value of ALRT_GRP_PKG.OLD_STATUS
     */
    public String getOLD_STATUS() {
        return OLD_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_GRP_PKG.OLD_STATUS
     *
     * @param OLD_STATUS the value for ALRT_GRP_PKG.OLD_STATUS
     */
    public void setOLD_STATUS(String OLD_STATUS) {
        this.OLD_STATUS = OLD_STATUS == null ? null : OLD_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_GRP_PKG.DATE_UPDATED
     *
     * @return the value of ALRT_GRP_PKG.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_GRP_PKG.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for ALRT_GRP_PKG.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
    
    public String getTO_BE_STATUS()
	{
	    return TO_BE_STATUS;
	}

	public void setTO_BE_STATUS(String tO_BE_STATUS)
	{
	    TO_BE_STATUS = tO_BE_STATUS;
	}

	public String getTO_BE_STATUS_BY()
	{
	    return TO_BE_STATUS_BY;
	}

	public void setTO_BE_STATUS_BY(String tO_BE_STATUS_BY)
	{
	    TO_BE_STATUS_BY = tO_BE_STATUS_BY;
	}
}