package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class REP_INFOVOKey extends BaseVO {
    /**
     * This field corresponds to the database column REP_INFO.REP_ID
     */
    private BigDecimal REP_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_INFO.REP_ID
     *
     * @return the value of REP_INFO.REP_ID
     */
    public BigDecimal getREP_ID() {
        return REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_INFO.REP_ID
     *
     * @param REP_ID the value for REP_INFO.REP_ID
     */
    public void setREP_ID(BigDecimal REP_ID) {
        this.REP_ID = REP_ID;
    }
}