package com.path.vo.alert.subscription;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.path.vo.common.ImBaseRequest;
import com.path.vo.common.header.ServiceContextAllVO;

/**
 * @AutoGenerated Code
 * @description class CreateSingleSubscriptionSEReq extends ImBaseRequest
 */
@XmlType(propOrder={})
@XmlRootElement(name="createSingleSubscriptionSEReq")
public class CreateSingleSubscriptionSEReq extends ImBaseRequest
{
	private ServiceContextAllVO serviceContext = new ServiceContextAllVO();
	private BigDecimal companyCode;
	private BigDecimal subscriberId;
	private BigDecimal subscriptionEventId;
	private List<String> excludedModesList = new ArrayList<String>();
	private String autoApproveFlag;
	private List<Account> exludeAccountList = new ArrayList<Account>();

	public void setServiceContext(ServiceContextAllVO serviceContext)
	{
	   this.serviceContext = serviceContext;
	}
	public ServiceContextAllVO getServiceContext()
	{
	   return serviceContext;
	}
	public void setCompanyCode(BigDecimal companyCode)
	{
	   this.companyCode = companyCode;
	}
	@XmlElement(required = true)
	public BigDecimal getCompanyCode()
	{
	   return companyCode;
	}
	public void setSubscriberId(BigDecimal subscriberId)
	{
	   this.subscriberId = subscriberId;
	}
	@XmlElement(required = true)
	public BigDecimal getSubscriberId()
	{
	   return subscriberId;
	}
	public void setSubscriptionEventId(BigDecimal subscriptionEventId)
	{
	   this.subscriptionEventId = subscriptionEventId;
	}
	@XmlElement(required = true)
	public BigDecimal getSubscriptionEventId()
	{
	   return subscriptionEventId;
	}
	public void setExcludedModesList(List<String> excludedModesList)
	{
	   this.excludedModesList = excludedModesList;
	}
	@XmlElementWrapper(name = "excludedModesList")
  	@XmlElement(name = "mode")
	public List<String> getExcludedModesList()
	{
	   return excludedModesList;
	}
	public void setAutoApproveFlag(String autoApproveFlag)
	{
	   this.autoApproveFlag = autoApproveFlag;
	}
	public String getAutoApproveFlag()
	{
	   return autoApproveFlag;
	}
	public void setExludeAccountList(List<Account> exludeAccountList)
	{
	   this.exludeAccountList = exludeAccountList;
	}
	@XmlElementWrapper(name = "exludeAccountList")
  	@XmlElement(name = "account")
	public List<Account> getExludeAccountList()
	{
	   return exludeAccountList;
	}
}
