package com.path.vo.alert.packages;
import com.path.vo.common.header.ServiceResponseVO;
import com.path.vo.common.header.ResponseContextVO;
import com.path.vo.common.header.ResponseServiceContextVO;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlElement;

import java.util.ArrayList;
import java.util.List;
import com.path.vo.alert.packages.Packages;
import com.path.vo.common.DynamicFilter;
import com.path.vo.common.ImBaseRequest;
import javax.xml.bind.annotation.XmlType;

/**
 * @AutoGenerated Code
 * @description class ReturnPackageListResp extends ImBaseRequest
 */

@XmlType(propOrder={})
public class ReturnPackageListResp extends ImBaseRequest
{
	private ServiceResponseVO serviceResponse = new ServiceResponseVO();
	private ResponseContextVO responseContext = new ResponseContextVO();
	private ResponseServiceContextVO responseServiceContext = new ResponseServiceContextVO();
	private String briefDescriptionEnglish;
	private String briefDescriptionArabic;
	private String longDescriptionEnglish;
	private String longDescriptionArabic;
	private String status;
	private DynamicFilter dynamicFilter = new DynamicFilter();
	private List<Packages> packageEventList = new ArrayList<Packages>();

	public void setServiceResponse(ServiceResponseVO serviceResponse)
	{
	   this.serviceResponse = serviceResponse;
	}
	public ServiceResponseVO getServiceResponse()
	{
	   return serviceResponse;
	}
	public void setResponseContext(ResponseContextVO responseContext)
	{
	   this.responseContext = responseContext;
	}
	public ResponseContextVO getResponseContext()
	{
	   return responseContext;
	}
	public void setResponseServiceContext(ResponseServiceContextVO responseServiceContext)
	{
	   this.responseServiceContext = responseServiceContext;
	}
	public ResponseServiceContextVO getResponseServiceContext()
	{
	   return responseServiceContext;
	}
	public void setBriefDescriptionEnglish(String briefDescriptionEnglish)
	{
	   this.briefDescriptionEnglish = briefDescriptionEnglish;
	}
	public String getBriefDescriptionEnglish()
	{
	   return briefDescriptionEnglish;
	}
	public void setBriefDescriptionArabic(String briefDescriptionArabic)
	{
	   this.briefDescriptionArabic = briefDescriptionArabic;
	}
	public String getBriefDescriptionArabic()
	{
	   return briefDescriptionArabic;
	}
	public void setLongDescriptionEnglish(String longDescriptionEnglish)
	{
	   this.longDescriptionEnglish = longDescriptionEnglish;
	}
	public String getLongDescriptionEnglish()
	{
	   return longDescriptionEnglish;
	}
	public void setLongDescriptionArabic(String longDescriptionArabic)
	{
	   this.longDescriptionArabic = longDescriptionArabic;
	}
	public String getLongDescriptionArabic()
	{
	   return longDescriptionArabic;
	}
	public void setStatus(String status)
	{
	   this.status = status;
	}
	public String getStatus()
	{
	   return status;
	}
	public void setDynamicFilter(DynamicFilter dynamicFilter)
	{
	   this.dynamicFilter = dynamicFilter;
	}
	public DynamicFilter getDynamicFilter()
	{
	   return dynamicFilter;
	}
	public void setPackageEventList(List<Packages> packageEventList)
	{
	   this.packageEventList = packageEventList;
	}
	@XmlElementWrapper(name = "packageEventList")
  	@XmlElement(name = "packages")
	public List<Packages> getPackageEventList()
	{
	   return packageEventList;
	}
}
