package com.path.vo.alert.subscription;
import java.math.BigDecimal;
import com.path.vo.common.header.ServiceResponseVO;
import com.path.vo.common.header.ResponseContextVO;
import com.path.vo.common.header.ResponseServiceContextVO;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlElement;

import java.util.ArrayList;
import java.util.List;
import com.path.vo.alert.subscription.Subscription;
import com.path.vo.common.DynamicFilter;
import com.path.vo.common.ImBaseRequest;
import javax.xml.bind.annotation.XmlType;

/**
 * @AutoGenerated Code
 * @description class ReturnSubscriptionListResp extends ImBaseRequest
 */

@XmlType(propOrder={})
public class ReturnSubscriptionListResp extends ImBaseRequest
{
	private ServiceResponseVO serviceResponse = new ServiceResponseVO();
	private ResponseContextVO responseContext = new ResponseContextVO();
	private ResponseServiceContextVO responseServiceContext = new ResponseServiceContextVO();
	private BigDecimal companyCode;
	private BigDecimal subscriberId;
	private BigDecimal eventId;
	private BigDecimal packageId;
	private String pacakgeName;
	private String eventDescription;
	private String subscriberBriefName;
	private String communicationMode;
	private BigDecimal groupId;
	private String groupName;
	private String subscriptionType;
	private String status;
	private DynamicFilter dynamicFilter = new DynamicFilter();
	private List<Subscription> subscriptionList = new ArrayList<Subscription>();

	public void setServiceResponse(ServiceResponseVO serviceResponse)
	{
	   this.serviceResponse = serviceResponse;
	}
	public ServiceResponseVO getServiceResponse()
	{
	   return serviceResponse;
	}
	public void setResponseContext(ResponseContextVO responseContext)
	{
	   this.responseContext = responseContext;
	}
	public ResponseContextVO getResponseContext()
	{
	   return responseContext;
	}
	public void setResponseServiceContext(ResponseServiceContextVO responseServiceContext)
	{
	   this.responseServiceContext = responseServiceContext;
	}
	public ResponseServiceContextVO getResponseServiceContext()
	{
	   return responseServiceContext;
	}
	public void setCompanyCode(BigDecimal companyCode)
	{
	   this.companyCode = companyCode;
	}
	public BigDecimal getCompanyCode()
	{
	   return companyCode;
	}
	public void setSubscriberId(BigDecimal subscriberId)
	{
	   this.subscriberId = subscriberId;
	}
	public BigDecimal getSubscriberId()
	{
	   return subscriberId;
	}
	public void setEventId(BigDecimal eventId)
	{
	   this.eventId = eventId;
	}
	public BigDecimal getEventId()
	{
	   return eventId;
	}
	public void setPackageId(BigDecimal packageId)
	{
	   this.packageId = packageId;
	}
	public BigDecimal getPackageId()
	{
	   return packageId;
	}
	public void setPacakgeName(String pacakgeName)
	{
	   this.pacakgeName = pacakgeName;
	}
	public String getPacakgeName()
	{
	   return pacakgeName;
	}
	public void setEventDescription(String eventDescription)
	{
	   this.eventDescription = eventDescription;
	}
	public String getEventDescription()
	{
	   return eventDescription;
	}
	public void setSubscriberBriefName(String subscriberBriefName)
	{
	   this.subscriberBriefName = subscriberBriefName;
	}
	public String getSubscriberBriefName()
	{
	   return subscriberBriefName;
	}
	public void setCommunicationMode(String communicationMode)
	{
	   this.communicationMode = communicationMode;
	}
	public String getCommunicationMode()
	{
	   return communicationMode;
	}
	public void setGroupId(BigDecimal groupId)
	{
	   this.groupId = groupId;
	}
	public BigDecimal getGroupId()
	{
	   return groupId;
	}
	public void setGroupName(String groupName)
	{
	   this.groupName = groupName;
	}
	public String getGroupName()
	{
	   return groupName;
	}
	public void setSubscriptionType(String subscriptionType)
	{
	   this.subscriptionType = subscriptionType;
	}
	public String getSubscriptionType()
	{
	   return subscriptionType;
	}
	public void setStatus(String status)
	{
	   this.status = status;
	}
	public String getStatus()
	{
	   return status;
	}
	public void setDynamicFilter(DynamicFilter dynamicFilter)
	{
	   this.dynamicFilter = dynamicFilter;
	}
	public DynamicFilter getDynamicFilter()
	{
	   return dynamicFilter;
	}
	public void setSubscriptionList(List<Subscription> subscriptionList)
	{
	   this.subscriptionList = subscriptionList;
	}
	@XmlElementWrapper(name = "subscriptionList")
  	@XmlElement(name = "subscription")
	public List<Subscription> getSubscriptionList()
	{
	   return subscriptionList;
	}
}
