package com.path.vo.alert.subscriber;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.path.vo.common.ImBaseRequest;
import com.path.vo.common.header.ResponseContextVO;
import com.path.vo.common.header.ResponseServiceContextVO;
import com.path.vo.common.header.ServiceResponseVO;

/**
 * @AutoGenerated Code
 * @description class CreateSubscriberResp extends ImBaseRequest
 */
@XmlType(propOrder={})
@XmlRootElement(name="createSubscriberResp")
public class CreateSubscriberResp extends ImBaseRequest
{
	private ServiceResponseVO serviceResponse = new ServiceResponseVO();
	private ResponseContextVO responseContext = new ResponseContextVO();
	private ResponseServiceContextVO responseServiceContext = new ResponseServiceContextVO();
	private BigDecimal cifNo;
	private String imalUserId;
	private BigDecimal companyCode;
	private String defaultLanguage;
	private String defaultBriefName;
	private String defaultMiddleName;
	private String defaultLongName;
	private String defaultAddress;
	private List<String> mobilePhonesList = new ArrayList<String>();
	private List<String> emailIdsList = new ArrayList<String>();
	private String channelEndUserId;
	private List<OtherLanguage> otherLanguagesList = new ArrayList<OtherLanguage>();
	private BigDecimal subscriberId;
	private String autoApproveFlag;

	public void setServiceResponse(ServiceResponseVO serviceResponse)
	{
	   this.serviceResponse = serviceResponse;
	}
	public ServiceResponseVO getServiceResponse()
	{
	   return serviceResponse;
	}
	public void setResponseContext(ResponseContextVO responseContext)
	{
	   this.responseContext = responseContext;
	}
	public ResponseContextVO getResponseContext()
	{
	   return responseContext;
	}
	public void setResponseServiceContext(ResponseServiceContextVO responseServiceContext)
	{
	   this.responseServiceContext = responseServiceContext;
	}
	public ResponseServiceContextVO getResponseServiceContext()
	{
	   return responseServiceContext;
	}
	public void setCifNo(BigDecimal cifNo)
	{
	   this.cifNo = cifNo;
	}
	public BigDecimal getCifNo()
	{
	   return cifNo;
	}
	public void setImalUserId(String imalUserId)
	{
	   this.imalUserId = imalUserId;
	}
	public String getImalUserId()
	{
	   return imalUserId;
	}
	public void setCompanyCode(BigDecimal companyCode)
	{
	   this.companyCode = companyCode;
	}
	public BigDecimal getCompanyCode()
	{
	   return companyCode;
	}
	public void setDefaultLanguage(String defaultLanguage)
	{
	   this.defaultLanguage = defaultLanguage;
	}
	public String getDefaultLanguage()
	{
	   return defaultLanguage;
	}
	public void setDefaultBriefName(String defaultBriefName)
	{
	   this.defaultBriefName = defaultBriefName;
	}
	public String getDefaultBriefName()
	{
	   return defaultBriefName;
	}
	public void setDefaultMiddleName(String defaultMiddleName)
	{
	   this.defaultMiddleName = defaultMiddleName;
	}
	public String getDefaultMiddleName()
	{
	   return defaultMiddleName;
	}
	public void setDefaultLongName(String defaultLongName)
	{
	   this.defaultLongName = defaultLongName;
	}
	public String getDefaultLongName()
	{
	   return defaultLongName;
	}
	public void setDefaultAddress(String defaultAddress)
	{
	   this.defaultAddress = defaultAddress;
	}
	public String getDefaultAddress()
	{
	   return defaultAddress;
	}
	public void setMobilePhonesList(List<String> mobilePhonesList)
	{
	   this.mobilePhonesList = mobilePhonesList;
	}
	@XmlElementWrapper(name = "mobilePhonesList")
  	@XmlElement(name = "mobile")
	public List<String> getMobilePhonesList()
	{
	   return mobilePhonesList;
	}
	public void setEmailIdsList(List<String> emailIdsList)
	{
	   this.emailIdsList = emailIdsList;
	}
	@XmlElementWrapper(name = "emailIdsList")
  	@XmlElement(name = "email")
	public List<String> getEmailIdsList()
	{
	   return emailIdsList;
	}
	public void setChannelEndUserId(String channelEndUserId)
	{
	   this.channelEndUserId = channelEndUserId;
	}
	public String getChannelEndUserId()
	{
	   return channelEndUserId;
	}
	public void setOtherLanguagesList(List<OtherLanguage> otherLanguagesList)
	{
	   this.otherLanguagesList = otherLanguagesList;
	}
  	@XmlElementWrapper(name = "otherLanguagesList")
  	@XmlElement(name = "otherLanguage")
	public List<OtherLanguage> getOtherLanguagesList()
	{
	   return otherLanguagesList;
	}
	public void setAutoApproveFlag(String autoApproveFlag)
	{
	   this.autoApproveFlag = autoApproveFlag;
	}
	public String getAutoApproveFlag()
	{
	   return autoApproveFlag;
	}
	public void setSubscriberId(BigDecimal subscriberId)
	{
	   this.subscriberId = subscriberId;
	}
	public BigDecimal getSubscriberId()
	{
	   return subscriberId;
	}
}
