package com.path.vo.alert.subscriber;
import javax.xml.bind.annotation.XmlType;

/**
 * @AutoGenerated Code
 * @description class OtherLanguage
 */

@XmlType(propOrder={})
public class OtherLanguage 
{
	private String language;
	private String briefName;
	private String middleName;
	private String longName;
	private String address;

	public void setLanguage(String language)
	{
	   this.language = language;
	}
	public String getLanguage()
	{
	   return language;
	}
	public void setBriefName(String briefName)
	{
	   this.briefName = briefName;
	}
	public String getBriefName()
	{
	   return briefName;
	}
	public void setMiddleName(String middleName)
	{
	   this.middleName = middleName;
	}
	public String getMiddleName()
	{
	   return middleName;
	}
	public void setLongName(String longName)
	{
	   this.longName = longName;
	}
	public String getLongName()
	{
	   return longName;
	}
	public void setAddress(String address)
	{
	   this.address = address;
	}
	public String getAddress()
	{
	   return address;
	}
}
