package com.path.vo.alert.subscriber;
import java.math.BigDecimal;
import com.path.vo.common.header.ServiceContextAllVO;
import javax.xml.bind.annotation.XmlElement;

import com.path.vo.common.DynamicFilter;
import com.path.vo.common.ImBaseRequest;
import javax.xml.bind.annotation.XmlType;

/**
 * @AutoGenerated Code
 * @description class ReturnSubscribersListReq extends ImBaseRequest
 */

@XmlType(propOrder={})
public class ReturnSubscribersListReq extends ImBaseRequest
{
	private ServiceContextAllVO serviceContext = new ServiceContextAllVO();
	private BigDecimal companyCode;
	private BigDecimal cifNo;
	private String imalUserId;
	private String channelEndUserId;
	private String briefNameEnglish;
	private String status;
	private DynamicFilter dynamicFilter = new DynamicFilter();

	public void setServiceContext(ServiceContextAllVO serviceContext)
	{
	   this.serviceContext = serviceContext;
	}
	public ServiceContextAllVO getServiceContext()
	{
	   return serviceContext;
	}
	public void setCompanyCode(BigDecimal companyCode)
	{
	   this.companyCode = companyCode;
	}
	@XmlElement(required = true)
	public BigDecimal getCompanyCode()
	{
	   return companyCode;
	}
	public void setCifNo(BigDecimal cifNo)
	{
	   this.cifNo = cifNo;
	}
	public BigDecimal getCifNo()
	{
	   return cifNo;
	}
	public void setImalUserId(String imalUserId)
	{
	   this.imalUserId = imalUserId;
	}
	public String getImalUserId()
	{
	   return imalUserId;
	}
	public void setChannelEndUserId(String channelEndUserId)
	{
	   this.channelEndUserId = channelEndUserId;
	}
	public String getChannelEndUserId()
	{
	   return channelEndUserId;
	}
	public void setBriefNameEnglish(String briefNameEnglish)
	{
	   this.briefNameEnglish = briefNameEnglish;
	}
	public String getBriefNameEnglish()
	{
	   return briefNameEnglish;
	}
	public void setStatus(String status)
	{
	   this.status = status;
	}
	public String getStatus()
	{
	   return status;
	}
	public void setDynamicFilter(DynamicFilter dynamicFilter)
	{
	   this.dynamicFilter = dynamicFilter;
	}
	public DynamicFilter getDynamicFilter()
	{
	   return dynamicFilter;
	}
}
