package com.path.vo.alert.subscriber;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;

import com.path.vo.common.ImBaseRequest;
import com.path.vo.common.header.ResponseContextVO;
import com.path.vo.common.header.ResponseServiceContextVO;
import com.path.vo.common.header.ServiceResponseVO;

/**
 * @AutoGenerated Code
 * @description class UpdateSubscriberResp extends ImBaseRequest
 */

@XmlType(propOrder={})
public class UpdateSubscriberResp extends ImBaseRequest
{
	private ServiceResponseVO serviceResponse = new ServiceResponseVO();
	private ResponseContextVO responseContext = new ResponseContextVO();
	private ResponseServiceContextVO responseServiceContext = new ResponseServiceContextVO();
	private BigDecimal subscriberId;
	private BigDecimal companyCode;
	private String defaultLanguage;
	private String defaultBriefName;
	private String defaultMiddleName;
	private String defaultLongName;
	private String defaultAddress;
	private List<String> newMobilePhonesList = new ArrayList<String>();
	private List<String> deletedMobilePhonesList = new ArrayList<String>();
	private List<String> newEmailIdsList = new ArrayList<String>();
	private List<String> deletedEmailIdsList = new ArrayList<String>();
	private String channelEndUserId;
	private List<OtherLanguage> newOtherLanguagesList = new ArrayList<OtherLanguage>();
	private List<OtherLanguage> updatedOtherLanguagesList = new ArrayList<OtherLanguage>();
	private List<OtherLanguage> deletedOtherLanguagesList = new ArrayList<OtherLanguage>();
	private String autoApproveFlag;
	private List<Account> exludeAccountList = new ArrayList<Account>();

	public void setServiceResponse(ServiceResponseVO serviceResponse)
	{
	   this.serviceResponse = serviceResponse;
	}
	public ServiceResponseVO getServiceResponse()
	{
	   return serviceResponse;
	}
	public void setResponseContext(ResponseContextVO responseContext)
	{
	   this.responseContext = responseContext;
	}
	public ResponseContextVO getResponseContext()
	{
	   return responseContext;
	}
	public void setResponseServiceContext(ResponseServiceContextVO responseServiceContext)
	{
	   this.responseServiceContext = responseServiceContext;
	}
	public ResponseServiceContextVO getResponseServiceContext()
	{
	   return responseServiceContext;
	}
	public void setSubscriberId(BigDecimal subscriberId)
	{
	   this.subscriberId = subscriberId;
	}
	public BigDecimal getSubscriberId()
	{
	   return subscriberId;
	}
	public void setCompanyCode(BigDecimal companyCode)
	{
	   this.companyCode = companyCode;
	}
	public BigDecimal getCompanyCode()
	{
	   return companyCode;
	}
	public void setDefaultLanguage(String defaultLanguage)
	{
	   this.defaultLanguage = defaultLanguage;
	}
	public String getDefaultLanguage()
	{
	   return defaultLanguage;
	}
	public void setDefaultBriefName(String defaultBriefName)
	{
	   this.defaultBriefName = defaultBriefName;
	}
	public String getDefaultBriefName()
	{
	   return defaultBriefName;
	}
	public void setDefaultMiddleName(String defaultMiddleName)
	{
	   this.defaultMiddleName = defaultMiddleName;
	}
	public String getDefaultMiddleName()
	{
	   return defaultMiddleName;
	}
	public void setDefaultLongName(String defaultLongName)
	{
	   this.defaultLongName = defaultLongName;
	}
	public String getDefaultLongName()
	{
	   return defaultLongName;
	}
	public void setDefaultAddress(String defaultAddress)
	{
	   this.defaultAddress = defaultAddress;
	}
	public String getDefaultAddress()
	{
	   return defaultAddress;
	}
	public void setNewMobilePhonesList(List<String> newMobilePhonesList)
	{
	   this.newMobilePhonesList = newMobilePhonesList;
	}
	@XmlElementWrapper(name = "newMobilePhonesList")
  	@XmlElement(name = "mobile")
	public List<String> getNewMobilePhonesList()
	{
	   return newMobilePhonesList;
	}
	public void setDeletedMobilePhonesList(List<String> deletedMobilePhonesList)
	{
	   this.deletedMobilePhonesList = deletedMobilePhonesList;
	}
	@XmlElementWrapper(name = "deletedMobilePhonesList")
  	@XmlElement(name = "mobile")
	public List<String> getDeletedMobilePhonesList()
	{
	   return deletedMobilePhonesList;
	}
	public void setNewEmailIdsList(List<String> newEmailIdsList)
	{
	   this.newEmailIdsList = newEmailIdsList;
	}
	@XmlElementWrapper(name = "newEmailIdsList")
  	@XmlElement(name = "email")
	public List<String> getNewEmailIdsList()
	{
	   return newEmailIdsList;
	}
	public void setDeletedEmailIdsList(List<String> deletedEmailIdsList)
	{
	   this.deletedEmailIdsList = deletedEmailIdsList;
	}
	@XmlElementWrapper(name = "deletedEmailIdsList")
  	@XmlElement(name = "email")
	public List<String> getDeletedEmailIdsList()
	{
	   return deletedEmailIdsList;
	}
	public void setChannelEndUserId(String channelEndUserId)
	{
	   this.channelEndUserId = channelEndUserId;
	}
	public String getChannelEndUserId()
	{
	   return channelEndUserId;
	}
	public void setNewOtherLanguagesList(List<OtherLanguage> newOtherLanguagesList)
	{
	   this.newOtherLanguagesList = newOtherLanguagesList;
	}
	@XmlElementWrapper(name = "newOtherLanguagesList")
  	@XmlElement(name = "otherLanguage")
	public List<OtherLanguage> getNewOtherLanguagesList()
	{
	   return newOtherLanguagesList;
	}
	public void setUpdatedOtherLanguagesList(List<OtherLanguage> updatedOtherLanguagesList)
	{
	   this.updatedOtherLanguagesList = updatedOtherLanguagesList;
	}
	@XmlElementWrapper(name = "updatedOtherLanguagesList")
  	@XmlElement(name = "otherLanguage")
	public List<OtherLanguage> getUpdatedOtherLanguagesList()
	{
	   return updatedOtherLanguagesList;
	}
	public void setDeletedOtherLanguagesList(List<OtherLanguage> deletedOtherLanguagesList)
	{
	   this.deletedOtherLanguagesList = deletedOtherLanguagesList;
	}
	@XmlElementWrapper(name = "deletedOtherLanguagesList")
  	@XmlElement(name = "otherLanguage")
	public List<OtherLanguage> getDeletedOtherLanguagesList()
	{
	   return deletedOtherLanguagesList;
	}
	public void setAutoApproveFlag(String autoApproveFlag)
	{
	   this.autoApproveFlag = autoApproveFlag;
	}
	public String getAutoApproveFlag()
	{
	   return autoApproveFlag;
	}
	public void setExludeAccountList(List<Account> exludeAccountList)
	{
	   this.exludeAccountList = exludeAccountList;
	}
	@XmlElementWrapper(name = "exludeAccountList")
  	@XmlElement(name = "account")
	public List<Account> getExludeAccountList()
	{
	   return exludeAccountList;
	}
}
