package com.path.vo.alert.subscriber;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlType;

/**
 * @AutoGenerated Code
 * @description class Subscriber
 */

@XmlType(propOrder={})
public class Subscriber 
{
	private BigDecimal subscriberId;
	private BigDecimal cifNo;
	private String imalUserId;
	private String channelEndUserId;
	private String briefNameEnglish;
	private String status;

	public void setSubscriberId(BigDecimal subscriberId)
	{
	   this.subscriberId = subscriberId;
	}
	public BigDecimal getSubscriberId()
	{
	   return subscriberId;
	}
	public void setCifNo(BigDecimal cifNo)
	{
	   this.cifNo = cifNo;
	}
	public BigDecimal getCifNo()
	{
	   return cifNo;
	}
	public void setImalUserId(String imalUserId)
	{
	   this.imalUserId = imalUserId;
	}
	public String getImalUserId()
	{
	   return imalUserId;
	}
	public void setChannelEndUserId(String channelEndUserId)
	{
	   this.channelEndUserId = channelEndUserId;
	}
	public String getChannelEndUserId()
	{
	   return channelEndUserId;
	}
	public void setBriefNameEnglish(String briefNameEnglish)
	{
	   this.briefNameEnglish = briefNameEnglish;
	}
	public String getBriefNameEnglish()
	{
	   return briefNameEnglish;
	}
	public void setStatus(String status)
	{
	   this.status = status;
	}
	public String getStatus()
	{
	   return status;
	}
}
