package com.path.vo.alert.subscription;
import java.math.BigDecimal;
import com.path.vo.common.header.ServiceResponseVO;
import com.path.vo.common.header.ResponseContextVO;
import com.path.vo.common.header.ResponseServiceContextVO;
import com.path.vo.common.ImBaseRequest;
import javax.xml.bind.annotation.XmlType;

/**
 * @AutoGenerated Code
 * @description class ReactiveSingleSubscriptionResp extends ImBaseRequest
 */

@XmlType(propOrder={})
public class ReactiveSingleSubscriptionResp extends ImBaseRequest
{
	private ServiceResponseVO serviceResponse = new ServiceResponseVO();
	private ResponseContextVO responseContext = new ResponseContextVO();
	private ResponseServiceContextVO responseServiceContext = new ResponseServiceContextVO();
	private BigDecimal subscriptionId;
	private String subscriptionType;
	private BigDecimal companyCode;

	public void setServiceResponse(ServiceResponseVO serviceResponse)
	{
	   this.serviceResponse = serviceResponse;
	}
	public ServiceResponseVO getServiceResponse()
	{
	   return serviceResponse;
	}
	public void setResponseContext(ResponseContextVO responseContext)
	{
	   this.responseContext = responseContext;
	}
	public ResponseContextVO getResponseContext()
	{
	   return responseContext;
	}
	public void setResponseServiceContext(ResponseServiceContextVO responseServiceContext)
	{
	   this.responseServiceContext = responseServiceContext;
	}
	public ResponseServiceContextVO getResponseServiceContext()
	{
	   return responseServiceContext;
	}
	public void setSubscriptionId(BigDecimal subscriptionId)
	{
	   this.subscriptionId = subscriptionId;
	}
	public BigDecimal getSubscriptionId()
	{
	   return subscriptionId;
	}
	public void setSubscriptionType(String subscriptionType)
	{
	   this.subscriptionType = subscriptionType;
	}
	public String getSubscriptionType()
	{
	   return subscriptionType;
	}
	public void setCompanyCode(BigDecimal companyCode)
	{
	   this.companyCode = companyCode;
	}
	public BigDecimal getCompanyCode()
	{
	   return companyCode;
	}
}
