package com.path.vo.alert.packages;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlType;

/**
 * @AutoGenerated Code
 * @description class Packages
 */

@XmlType(propOrder={})
public class Packages 
{
	private BigDecimal packageId;
	private String briefDescriptionEnglish;
	private String briefDescriptionArabic;
	private String longDescriptionEnglish;
	private String longDescriptionArabic;
	private String status;

	public void setPackageId(BigDecimal packageId)
	{
	   this.packageId = packageId;
	}
	public BigDecimal getPackageId()
	{
	   return packageId;
	}
	public void setBriefDescriptionEnglish(String briefDescriptionEnglish)
	{
	   this.briefDescriptionEnglish = briefDescriptionEnglish;
	}
	public String getBriefDescriptionEnglish()
	{
	   return briefDescriptionEnglish;
	}
	public void setBriefDescriptionArabic(String briefDescriptionArabic)
	{
	   this.briefDescriptionArabic = briefDescriptionArabic;
	}
	public String getBriefDescriptionArabic()
	{
	   return briefDescriptionArabic;
	}
	public void setLongDescriptionEnglish(String longDescriptionEnglish)
	{
	   this.longDescriptionEnglish = longDescriptionEnglish;
	}
	public String getLongDescriptionEnglish()
	{
	   return longDescriptionEnglish;
	}
	public void setLongDescriptionArabic(String longDescriptionArabic)
	{
	   this.longDescriptionArabic = longDescriptionArabic;
	}
	public String getLongDescriptionArabic()
	{
	   return longDescriptionArabic;
	}
	public void setStatus(String status)
	{
	   this.status = status;
	}
	public String getStatus()
	{
	   return status;
	}
}
