package com.path.vo.alert.packages;
import com.path.vo.common.header.ServiceContextAllVO;
import com.path.vo.common.DynamicFilter;
import com.path.vo.common.ImBaseRequest;
import javax.xml.bind.annotation.XmlType;

/**
 * @AutoGenerated Code
 * @description class ReturnPackageListReq extends ImBaseRequest
 */

@XmlType(propOrder={})
public class ReturnPackageListReq extends ImBaseRequest
{
	private ServiceContextAllVO serviceContext = new ServiceContextAllVO();
	private String briefDescriptionEnglish;
	private String briefDescriptionArabic;
	private String longDescriptionEnglish;
	private String longDescriptionArabic;
	private String status;
	private DynamicFilter dynamicFilter = new DynamicFilter();

	public void setServiceContext(ServiceContextAllVO serviceContext)
	{
	   this.serviceContext = serviceContext;
	}
	public ServiceContextAllVO getServiceContext()
	{
	   return serviceContext;
	}
	public void setBriefDescriptionEnglish(String briefDescriptionEnglish)
	{
	   this.briefDescriptionEnglish = briefDescriptionEnglish;
	}
	public String getBriefDescriptionEnglish()
	{
	   return briefDescriptionEnglish;
	}
	public void setBriefDescriptionArabic(String briefDescriptionArabic)
	{
	   this.briefDescriptionArabic = briefDescriptionArabic;
	}
	public String getBriefDescriptionArabic()
	{
	   return briefDescriptionArabic;
	}
	public void setLongDescriptionEnglish(String longDescriptionEnglish)
	{
	   this.longDescriptionEnglish = longDescriptionEnglish;
	}
	public String getLongDescriptionEnglish()
	{
	   return longDescriptionEnglish;
	}
	public void setLongDescriptionArabic(String longDescriptionArabic)
	{
	   this.longDescriptionArabic = longDescriptionArabic;
	}
	public String getLongDescriptionArabic()
	{
	   return longDescriptionArabic;
	}
	public void setStatus(String status)
	{
	   this.status = status;
	}
	public String getStatus()
	{
	   return status;
	}
	public void setDynamicFilter(DynamicFilter dynamicFilter)
	{
	   this.dynamicFilter = dynamicFilter;
	}
	public DynamicFilter getDynamicFilter()
	{
	   return dynamicFilter;
	}
}
