package com.path.vo.alert.subscriber;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlType;

import com.path.vo.common.ImBaseRequest;
import com.path.vo.common.header.ResponseContextVO;
import com.path.vo.common.header.ResponseServiceContextVO;
import com.path.vo.common.header.ServiceResponseVO;

/**
 * @AutoGenerated Code
 * @description class ApproveSubscriberResp extends ImBaseRequest
 */

@XmlType(propOrder={})
public class ApproveSubscriberResp extends ImBaseRequest
{
	private ServiceResponseVO serviceResponse = new ServiceResponseVO();
	private ResponseContextVO responseContext = new ResponseContextVO();
	private ResponseServiceContextVO responseServiceContext = new ResponseServiceContextVO();
	private BigDecimal subscriberId;
	private BigDecimal companyCode;

	public void setServiceResponse(ServiceResponseVO serviceResponse)
	{
	   this.serviceResponse = serviceResponse;
	}
	public ServiceResponseVO getServiceResponse()
	{
	   return serviceResponse;
	}
	public void setResponseContext(ResponseContextVO responseContext)
	{
	   this.responseContext = responseContext;
	}
	public ResponseContextVO getResponseContext()
	{
	   return responseContext;
	}
	public void setResponseServiceContext(ResponseServiceContextVO responseServiceContext)
	{
	   this.responseServiceContext = responseServiceContext;
	}
	public ResponseServiceContextVO getResponseServiceContext()
	{
	   return responseServiceContext;
	}
	public void setSubscriberId(BigDecimal subscriberId)
	{
	   this.subscriberId = subscriberId;
	}
	public BigDecimal getSubscriberId()
	{
	   return subscriberId;
	}
	public void setCompanyCode(BigDecimal companyCode)
	{
	   this.companyCode = companyCode;
	}
	public BigDecimal getCompanyCode()
	{
	   return companyCode;
	}
}
